// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.cosmo.ContractArgs;
import com.pulumi.cosmo.Utilities;
import com.pulumi.cosmo.inputs.ContractState;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="cosmo:index/contract:Contract")
public class Contract extends com.pulumi.resources.CustomResource {
    @Export(name="admissionWebhookSecret", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> admissionWebhookSecret;

    public Output<Optional<String>> admissionWebhookSecret() {
        return Codegen.optional(this.admissionWebhookSecret);
    }
    @Export(name="admissionWebhookUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> admissionWebhookUrl;

    public Output<Optional<String>> admissionWebhookUrl() {
        return Codegen.optional(this.admissionWebhookUrl);
    }
    @Export(name="excludeTags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> excludeTags;

    public Output<Optional<List<String>>> excludeTags() {
        return Codegen.optional(this.excludeTags);
    }
    @Export(name="includeTags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> includeTags;

    public Output<Optional<List<String>>> includeTags() {
        return Codegen.optional(this.includeTags);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="namespace", refs={String.class}, tree="[0]")
    private Output<String> namespace;

    public Output<String> namespace() {
        return this.namespace;
    }
    @Export(name="readme", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> readme;

    public Output<Optional<String>> readme() {
        return Codegen.optional(this.readme);
    }
    @Export(name="routingUrl", refs={String.class}, tree="[0]")
    private Output<String> routingUrl;

    public Output<String> routingUrl() {
        return this.routingUrl;
    }
    @Export(name="source", refs={String.class}, tree="[0]")
    private Output<String> source;

    public Output<String> source() {
        return this.source;
    }
    @Export(name="supportsFederation", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> supportsFederation;

    public Output<Boolean> supportsFederation() {
        return this.supportsFederation;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Contract(java.lang.String name) {
        this(name, ContractArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Contract(java.lang.String name, ContractArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Contract(java.lang.String name, ContractArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cosmo:index/contract:Contract", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Contract(java.lang.String name, Output<java.lang.String> id, @Nullable ContractState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cosmo:index/contract:Contract", name, state, makeResourceOptions(options, id), false);
    }

    private static ContractArgs makeArgs(ContractArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ContractArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://github.com/primait/pulumi-cosmo/releases/download/v${VERSION}/")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Contract get(java.lang.String name, Output<java.lang.String> id, @Nullable ContractState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Contract(name, id, state, options);
    }
}
