// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.cosmo.FederatedGraphArgs;
import com.pulumi.cosmo.Utilities;
import com.pulumi.cosmo.inputs.FederatedGraphState;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="cosmo:index/federatedGraph:FederatedGraph")
public class FederatedGraph extends com.pulumi.resources.CustomResource {
    /**
     * The secret token used to authenticate the admission webhook requests.
     * 
     */
    @Export(name="admissionWebhookSecret", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> admissionWebhookSecret;

    /**
     * @return The secret token used to authenticate the admission webhook requests.
     * 
     */
    public Output<Optional<String>> admissionWebhookSecret() {
        return Codegen.optional(this.admissionWebhookSecret);
    }
    /**
     * The URL for the admission webhook that will be triggered during graph operations.
     * 
     */
    @Export(name="admissionWebhookUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> admissionWebhookUrl;

    /**
     * @return The URL for the admission webhook that will be triggered during graph operations.
     * 
     */
    public Output<Optional<String>> admissionWebhookUrl() {
        return Codegen.optional(this.admissionWebhookUrl);
    }
    /**
     * A list of label matchers used to select the services that will form the federated graph.
     * 
     */
    @Export(name="labelMatchers", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> labelMatchers;

    /**
     * @return A list of label matchers used to select the services that will form the federated graph.
     * 
     */
    public Output<List<String>> labelMatchers() {
        return this.labelMatchers;
    }
    /**
     * The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The namespace in which the federated graph is located. Defaults to &#39;default&#39; if not provided.
     * 
     */
    @Export(name="namespace", refs={String.class}, tree="[0]")
    private Output<String> namespace;

    /**
     * @return The namespace in which the federated graph is located. Defaults to &#39;default&#39; if not provided.
     * 
     */
    public Output<String> namespace() {
        return this.namespace;
    }
    /**
     * Readme content for the federated graph.
     * 
     */
    @Export(name="readme", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> readme;

    /**
     * @return Readme content for the federated graph.
     * 
     */
    public Output<Optional<String>> readme() {
        return Codegen.optional(this.readme);
    }
    /**
     * The URL of the service that routes requests to the federated graph.
     * 
     */
    @Export(name="routingUrl", refs={String.class}, tree="[0]")
    private Output<String> routingUrl;

    /**
     * @return The URL of the service that routes requests to the federated graph.
     * 
     */
    public Output<String> routingUrl() {
        return this.routingUrl;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public FederatedGraph(java.lang.String name) {
        this(name, FederatedGraphArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public FederatedGraph(java.lang.String name, FederatedGraphArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public FederatedGraph(java.lang.String name, FederatedGraphArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cosmo:index/federatedGraph:FederatedGraph", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private FederatedGraph(java.lang.String name, Output<java.lang.String> id, @Nullable FederatedGraphState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cosmo:index/federatedGraph:FederatedGraph", name, state, makeResourceOptions(options, id), false);
    }

    private static FederatedGraphArgs makeArgs(FederatedGraphArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? FederatedGraphArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://github.com/primait/pulumi-cosmo/releases/download/v${VERSION}/")
            .additionalSecretOutputs(List.of(
                "admissionWebhookSecret"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static FederatedGraph get(java.lang.String name, Output<java.lang.String> id, @Nullable FederatedGraphState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new FederatedGraph(name, id, state, options);
    }
}
