// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MonographArgs extends com.pulumi.resources.ResourceArgs {

    public static final MonographArgs Empty = new MonographArgs();

    /**
     * The admission webhook secret for the monograph.
     * 
     */
    @Import(name="admissionWebhookSecret")
    private @Nullable Output<String> admissionWebhookSecret;

    /**
     * @return The admission webhook secret for the monograph.
     * 
     */
    public Optional<Output<String>> admissionWebhookSecret() {
        return Optional.ofNullable(this.admissionWebhookSecret);
    }

    /**
     * The admission webhook URL for the monograph.
     * 
     */
    @Import(name="admissionWebhookUrl")
    private @Nullable Output<String> admissionWebhookUrl;

    /**
     * @return The admission webhook URL for the monograph.
     * 
     */
    public Optional<Output<String>> admissionWebhookUrl() {
        return Optional.ofNullable(this.admissionWebhookUrl);
    }

    /**
     * The GraphQL endpoint URL of the monograph.
     * 
     */
    @Import(name="graphUrl", required=true)
    private Output<String> graphUrl;

    /**
     * @return The GraphQL endpoint URL of the monograph.
     * 
     */
    public Output<String> graphUrl() {
        return this.graphUrl;
    }

    /**
     * The name of the monograph.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the monograph.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The namespace in which the monograph is located.
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return The namespace in which the monograph is located.
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    /**
     * The readme for the subgraph.
     * 
     */
    @Import(name="readme")
    private @Nullable Output<String> readme;

    /**
     * @return The readme for the subgraph.
     * 
     */
    public Optional<Output<String>> readme() {
        return Optional.ofNullable(this.readme);
    }

    /**
     * The routing URL for the monograph.
     * 
     */
    @Import(name="routingUrl", required=true)
    private Output<String> routingUrl;

    /**
     * @return The routing URL for the monograph.
     * 
     */
    public Output<String> routingUrl() {
        return this.routingUrl;
    }

    /**
     * The schema for the subgraph.
     * 
     */
    @Import(name="schema")
    private @Nullable Output<String> schema;

    /**
     * @return The schema for the subgraph.
     * 
     */
    public Optional<Output<String>> schema() {
        return Optional.ofNullable(this.schema);
    }

    /**
     * The subscription protocol for the subgraph.
     * 
     */
    @Import(name="subscriptionProtocol")
    private @Nullable Output<String> subscriptionProtocol;

    /**
     * @return The subscription protocol for the subgraph.
     * 
     */
    public Optional<Output<String>> subscriptionProtocol() {
        return Optional.ofNullable(this.subscriptionProtocol);
    }

    /**
     * The subscription URL for the subgraph.
     * 
     */
    @Import(name="subscriptionUrl")
    private @Nullable Output<String> subscriptionUrl;

    /**
     * @return The subscription URL for the subgraph.
     * 
     */
    public Optional<Output<String>> subscriptionUrl() {
        return Optional.ofNullable(this.subscriptionUrl);
    }

    /**
     * The websocket subprotocol for the subgraph.
     * 
     */
    @Import(name="websocketSubprotocol")
    private @Nullable Output<String> websocketSubprotocol;

    /**
     * @return The websocket subprotocol for the subgraph.
     * 
     */
    public Optional<Output<String>> websocketSubprotocol() {
        return Optional.ofNullable(this.websocketSubprotocol);
    }

    private MonographArgs() {}

    private MonographArgs(MonographArgs $) {
        this.admissionWebhookSecret = $.admissionWebhookSecret;
        this.admissionWebhookUrl = $.admissionWebhookUrl;
        this.graphUrl = $.graphUrl;
        this.name = $.name;
        this.namespace = $.namespace;
        this.readme = $.readme;
        this.routingUrl = $.routingUrl;
        this.schema = $.schema;
        this.subscriptionProtocol = $.subscriptionProtocol;
        this.subscriptionUrl = $.subscriptionUrl;
        this.websocketSubprotocol = $.websocketSubprotocol;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MonographArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MonographArgs $;

        public Builder() {
            $ = new MonographArgs();
        }

        public Builder(MonographArgs defaults) {
            $ = new MonographArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param admissionWebhookSecret The admission webhook secret for the monograph.
         * 
         * @return builder
         * 
         */
        public Builder admissionWebhookSecret(@Nullable Output<String> admissionWebhookSecret) {
            $.admissionWebhookSecret = admissionWebhookSecret;
            return this;
        }

        /**
         * @param admissionWebhookSecret The admission webhook secret for the monograph.
         * 
         * @return builder
         * 
         */
        public Builder admissionWebhookSecret(String admissionWebhookSecret) {
            return admissionWebhookSecret(Output.of(admissionWebhookSecret));
        }

        /**
         * @param admissionWebhookUrl The admission webhook URL for the monograph.
         * 
         * @return builder
         * 
         */
        public Builder admissionWebhookUrl(@Nullable Output<String> admissionWebhookUrl) {
            $.admissionWebhookUrl = admissionWebhookUrl;
            return this;
        }

        /**
         * @param admissionWebhookUrl The admission webhook URL for the monograph.
         * 
         * @return builder
         * 
         */
        public Builder admissionWebhookUrl(String admissionWebhookUrl) {
            return admissionWebhookUrl(Output.of(admissionWebhookUrl));
        }

        /**
         * @param graphUrl The GraphQL endpoint URL of the monograph.
         * 
         * @return builder
         * 
         */
        public Builder graphUrl(Output<String> graphUrl) {
            $.graphUrl = graphUrl;
            return this;
        }

        /**
         * @param graphUrl The GraphQL endpoint URL of the monograph.
         * 
         * @return builder
         * 
         */
        public Builder graphUrl(String graphUrl) {
            return graphUrl(Output.of(graphUrl));
        }

        /**
         * @param name The name of the monograph.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the monograph.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param namespace The namespace in which the monograph is located.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace The namespace in which the monograph is located.
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        /**
         * @param readme The readme for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder readme(@Nullable Output<String> readme) {
            $.readme = readme;
            return this;
        }

        /**
         * @param readme The readme for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder readme(String readme) {
            return readme(Output.of(readme));
        }

        /**
         * @param routingUrl The routing URL for the monograph.
         * 
         * @return builder
         * 
         */
        public Builder routingUrl(Output<String> routingUrl) {
            $.routingUrl = routingUrl;
            return this;
        }

        /**
         * @param routingUrl The routing URL for the monograph.
         * 
         * @return builder
         * 
         */
        public Builder routingUrl(String routingUrl) {
            return routingUrl(Output.of(routingUrl));
        }

        /**
         * @param schema The schema for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder schema(@Nullable Output<String> schema) {
            $.schema = schema;
            return this;
        }

        /**
         * @param schema The schema for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder schema(String schema) {
            return schema(Output.of(schema));
        }

        /**
         * @param subscriptionProtocol The subscription protocol for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionProtocol(@Nullable Output<String> subscriptionProtocol) {
            $.subscriptionProtocol = subscriptionProtocol;
            return this;
        }

        /**
         * @param subscriptionProtocol The subscription protocol for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionProtocol(String subscriptionProtocol) {
            return subscriptionProtocol(Output.of(subscriptionProtocol));
        }

        /**
         * @param subscriptionUrl The subscription URL for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionUrl(@Nullable Output<String> subscriptionUrl) {
            $.subscriptionUrl = subscriptionUrl;
            return this;
        }

        /**
         * @param subscriptionUrl The subscription URL for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionUrl(String subscriptionUrl) {
            return subscriptionUrl(Output.of(subscriptionUrl));
        }

        /**
         * @param websocketSubprotocol The websocket subprotocol for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder websocketSubprotocol(@Nullable Output<String> websocketSubprotocol) {
            $.websocketSubprotocol = websocketSubprotocol;
            return this;
        }

        /**
         * @param websocketSubprotocol The websocket subprotocol for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder websocketSubprotocol(String websocketSubprotocol) {
            return websocketSubprotocol(Output.of(websocketSubprotocol));
        }

        public MonographArgs build() {
            if ($.graphUrl == null) {
                throw new MissingRequiredPropertyException("MonographArgs", "graphUrl");
            }
            if ($.routingUrl == null) {
                throw new MissingRequiredPropertyException("MonographArgs", "routingUrl");
            }
            return $;
        }
    }

}
