// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.cosmo.MonographArgs;
import com.pulumi.cosmo.Utilities;
import com.pulumi.cosmo.inputs.MonographState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="cosmo:index/monograph:Monograph")
public class Monograph extends com.pulumi.resources.CustomResource {
    /**
     * The admission webhook secret for the monograph.
     * 
     */
    @Export(name="admissionWebhookSecret", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> admissionWebhookSecret;

    /**
     * @return The admission webhook secret for the monograph.
     * 
     */
    public Output<Optional<String>> admissionWebhookSecret() {
        return Codegen.optional(this.admissionWebhookSecret);
    }
    /**
     * The admission webhook URL for the monograph.
     * 
     */
    @Export(name="admissionWebhookUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> admissionWebhookUrl;

    /**
     * @return The admission webhook URL for the monograph.
     * 
     */
    public Output<Optional<String>> admissionWebhookUrl() {
        return Codegen.optional(this.admissionWebhookUrl);
    }
    /**
     * The GraphQL endpoint URL of the monograph.
     * 
     */
    @Export(name="graphUrl", refs={String.class}, tree="[0]")
    private Output<String> graphUrl;

    /**
     * @return The GraphQL endpoint URL of the monograph.
     * 
     */
    public Output<String> graphUrl() {
        return this.graphUrl;
    }
    /**
     * The name of the monograph.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the monograph.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The namespace in which the monograph is located.
     * 
     */
    @Export(name="namespace", refs={String.class}, tree="[0]")
    private Output<String> namespace;

    /**
     * @return The namespace in which the monograph is located.
     * 
     */
    public Output<String> namespace() {
        return this.namespace;
    }
    /**
     * The readme for the subgraph.
     * 
     */
    @Export(name="readme", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> readme;

    /**
     * @return The readme for the subgraph.
     * 
     */
    public Output<Optional<String>> readme() {
        return Codegen.optional(this.readme);
    }
    /**
     * The routing URL for the monograph.
     * 
     */
    @Export(name="routingUrl", refs={String.class}, tree="[0]")
    private Output<String> routingUrl;

    /**
     * @return The routing URL for the monograph.
     * 
     */
    public Output<String> routingUrl() {
        return this.routingUrl;
    }
    /**
     * The schema for the subgraph.
     * 
     */
    @Export(name="schema", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> schema;

    /**
     * @return The schema for the subgraph.
     * 
     */
    public Output<Optional<String>> schema() {
        return Codegen.optional(this.schema);
    }
    /**
     * The subscription protocol for the subgraph.
     * 
     */
    @Export(name="subscriptionProtocol", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> subscriptionProtocol;

    /**
     * @return The subscription protocol for the subgraph.
     * 
     */
    public Output<Optional<String>> subscriptionProtocol() {
        return Codegen.optional(this.subscriptionProtocol);
    }
    /**
     * The subscription URL for the subgraph.
     * 
     */
    @Export(name="subscriptionUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> subscriptionUrl;

    /**
     * @return The subscription URL for the subgraph.
     * 
     */
    public Output<Optional<String>> subscriptionUrl() {
        return Codegen.optional(this.subscriptionUrl);
    }
    /**
     * The websocket subprotocol for the subgraph.
     * 
     */
    @Export(name="websocketSubprotocol", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> websocketSubprotocol;

    /**
     * @return The websocket subprotocol for the subgraph.
     * 
     */
    public Output<Optional<String>> websocketSubprotocol() {
        return Codegen.optional(this.websocketSubprotocol);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Monograph(java.lang.String name) {
        this(name, MonographArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Monograph(java.lang.String name, MonographArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Monograph(java.lang.String name, MonographArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cosmo:index/monograph:Monograph", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Monograph(java.lang.String name, Output<java.lang.String> id, @Nullable MonographState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cosmo:index/monograph:Monograph", name, state, makeResourceOptions(options, id), false);
    }

    private static MonographArgs makeArgs(MonographArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? MonographArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://github.com/primait/pulumi-cosmo/releases/download/v${VERSION}/")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Monograph get(java.lang.String name, Output<java.lang.String> id, @Nullable MonographState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Monograph(name, id, state, options);
    }
}
