// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.cosmo.RouterTokenArgs;
import com.pulumi.cosmo.Utilities;
import com.pulumi.cosmo.inputs.RouterTokenState;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="cosmo:index/routerToken:RouterToken")
public class RouterToken extends com.pulumi.resources.CustomResource {
    /**
     * The name of the graph to create the token for.
     * 
     */
    @Export(name="graphName", refs={String.class}, tree="[0]")
    private Output<String> graphName;

    /**
     * @return The name of the graph to create the token for.
     * 
     */
    public Output<String> graphName() {
        return this.graphName;
    }
    /**
     * The name of the router token.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the router token.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The namespace to create the token in.
     * 
     */
    @Export(name="namespace", refs={String.class}, tree="[0]")
    private Output<String> namespace;

    /**
     * @return The namespace to create the token in.
     * 
     */
    public Output<String> namespace() {
        return this.namespace;
    }
    /**
     * The token to be used for the router.
     * 
     */
    @Export(name="token", refs={String.class}, tree="[0]")
    private Output<String> token;

    /**
     * @return The token to be used for the router.
     * 
     */
    public Output<String> token() {
        return this.token;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RouterToken(java.lang.String name) {
        this(name, RouterTokenArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RouterToken(java.lang.String name, RouterTokenArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RouterToken(java.lang.String name, RouterTokenArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cosmo:index/routerToken:RouterToken", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RouterToken(java.lang.String name, Output<java.lang.String> id, @Nullable RouterTokenState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cosmo:index/routerToken:RouterToken", name, state, makeResourceOptions(options, id), false);
    }

    private static RouterTokenArgs makeArgs(RouterTokenArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RouterTokenArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://github.com/primait/pulumi-cosmo/releases/download/v${VERSION}/")
            .additionalSecretOutputs(List.of(
                "token"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RouterToken get(java.lang.String name, Output<java.lang.String> id, @Nullable RouterTokenState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RouterToken(name, id, state, options);
    }
}
