// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo
{
    [CosmoResourceType("cosmo:index/contract:Contract")]
    public partial class Contract : global::Pulumi.CustomResource
    {
        [Output("admissionWebhookSecret")]
        public Output<string?> AdmissionWebhookSecret { get; private set; } = null!;

        [Output("admissionWebhookUrl")]
        public Output<string?> AdmissionWebhookUrl { get; private set; } = null!;

        [Output("excludeTags")]
        public Output<ImmutableArray<string>> ExcludeTags { get; private set; } = null!;

        [Output("includeTags")]
        public Output<ImmutableArray<string>> IncludeTags { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("namespace")]
        public Output<string> Namespace { get; private set; } = null!;

        [Output("readme")]
        public Output<string?> Readme { get; private set; } = null!;

        [Output("routingUrl")]
        public Output<string> RoutingUrl { get; private set; } = null!;

        [Output("source")]
        public Output<string> Source { get; private set; } = null!;

        [Output("supportsFederation")]
        public Output<bool> SupportsFederation { get; private set; } = null!;


        /// <summary>
        /// Create a Contract resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Contract(string name, ContractArgs args, CustomResourceOptions? options = null)
            : base("cosmo:index/contract:Contract", name, args ?? new ContractArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Contract(string name, Input<string> id, ContractState? state = null, CustomResourceOptions? options = null)
            : base("cosmo:index/contract:Contract", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/wundergraph/pulumi-cosmo/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Contract resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Contract Get(string name, Input<string> id, ContractState? state = null, CustomResourceOptions? options = null)
        {
            return new Contract(name, id, state, options);
        }
    }

    public sealed class ContractArgs : global::Pulumi.ResourceArgs
    {
        [Input("admissionWebhookSecret")]
        public Input<string>? AdmissionWebhookSecret { get; set; }

        [Input("admissionWebhookUrl")]
        public Input<string>? AdmissionWebhookUrl { get; set; }

        [Input("excludeTags")]
        private InputList<string>? _excludeTags;
        public InputList<string> ExcludeTags
        {
            get => _excludeTags ?? (_excludeTags = new InputList<string>());
            set => _excludeTags = value;
        }

        [Input("includeTags")]
        private InputList<string>? _includeTags;
        public InputList<string> IncludeTags
        {
            get => _includeTags ?? (_includeTags = new InputList<string>());
            set => _includeTags = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        [Input("readme")]
        public Input<string>? Readme { get; set; }

        [Input("routingUrl", required: true)]
        public Input<string> RoutingUrl { get; set; } = null!;

        [Input("source", required: true)]
        public Input<string> Source { get; set; } = null!;

        [Input("supportsFederation")]
        public Input<bool>? SupportsFederation { get; set; }

        public ContractArgs()
        {
        }
        public static new ContractArgs Empty => new ContractArgs();
    }

    public sealed class ContractState : global::Pulumi.ResourceArgs
    {
        [Input("admissionWebhookSecret")]
        public Input<string>? AdmissionWebhookSecret { get; set; }

        [Input("admissionWebhookUrl")]
        public Input<string>? AdmissionWebhookUrl { get; set; }

        [Input("excludeTags")]
        private InputList<string>? _excludeTags;
        public InputList<string> ExcludeTags
        {
            get => _excludeTags ?? (_excludeTags = new InputList<string>());
            set => _excludeTags = value;
        }

        [Input("includeTags")]
        private InputList<string>? _includeTags;
        public InputList<string> IncludeTags
        {
            get => _includeTags ?? (_includeTags = new InputList<string>());
            set => _includeTags = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        [Input("readme")]
        public Input<string>? Readme { get; set; }

        [Input("routingUrl")]
        public Input<string>? RoutingUrl { get; set; }

        [Input("source")]
        public Input<string>? Source { get; set; }

        [Input("supportsFederation")]
        public Input<bool>? SupportsFederation { get; set; }

        public ContractState()
        {
        }
        public static new ContractState Empty => new ContractState();
    }
}
