// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo
{
    [CosmoResourceType("cosmo:index/featureFlag:FeatureFlag")]
    public partial class FeatureFlag : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp when the feature flag was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The user who created the feature flag.
        /// </summary>
        [Output("createdBy")]
        public Output<string> CreatedBy { get; private set; } = null!;

        /// <summary>
        /// The list of feature subgraphs associated with the feature flag. 
        /// At least one feature subgraph must be provided.
        /// </summary>
        [Output("featureSubgraphs")]
        public Output<ImmutableArray<string>> FeatureSubgraphs { get; private set; } = null!;

        /// <summary>
        /// Indicates whether the feature flag is enabled.
        /// </summary>
        [Output("isEnabled")]
        public Output<bool?> IsEnabled { get; private set; } = null!;

        /// <summary>
        /// The labels associated with the feature flag. These labels indicate which 
        /// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// The name of the feature flag.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The namespace of the feature flag.
        /// </summary>
        [Output("namespace")]
        public Output<string> Namespace { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the feature flag was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a FeatureFlag resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FeatureFlag(string name, FeatureFlagArgs args, CustomResourceOptions? options = null)
            : base("cosmo:index/featureFlag:FeatureFlag", name, args ?? new FeatureFlagArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FeatureFlag(string name, Input<string> id, FeatureFlagState? state = null, CustomResourceOptions? options = null)
            : base("cosmo:index/featureFlag:FeatureFlag", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/primait/pulumi-cosmo/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FeatureFlag resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FeatureFlag Get(string name, Input<string> id, FeatureFlagState? state = null, CustomResourceOptions? options = null)
        {
            return new FeatureFlag(name, id, state, options);
        }
    }

    public sealed class FeatureFlagArgs : global::Pulumi.ResourceArgs
    {
        [Input("featureSubgraphs", required: true)]
        private InputList<string>? _featureSubgraphs;

        /// <summary>
        /// The list of feature subgraphs associated with the feature flag. 
        /// At least one feature subgraph must be provided.
        /// </summary>
        public InputList<string> FeatureSubgraphs
        {
            get => _featureSubgraphs ?? (_featureSubgraphs = new InputList<string>());
            set => _featureSubgraphs = value;
        }

        /// <summary>
        /// Indicates whether the feature flag is enabled.
        /// </summary>
        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// The labels associated with the feature flag. These labels indicate which 
        /// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The name of the feature flag.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The namespace of the feature flag.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public FeatureFlagArgs()
        {
        }
        public static new FeatureFlagArgs Empty => new FeatureFlagArgs();
    }

    public sealed class FeatureFlagState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The timestamp when the feature flag was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// The user who created the feature flag.
        /// </summary>
        [Input("createdBy")]
        public Input<string>? CreatedBy { get; set; }

        [Input("featureSubgraphs")]
        private InputList<string>? _featureSubgraphs;

        /// <summary>
        /// The list of feature subgraphs associated with the feature flag. 
        /// At least one feature subgraph must be provided.
        /// </summary>
        public InputList<string> FeatureSubgraphs
        {
            get => _featureSubgraphs ?? (_featureSubgraphs = new InputList<string>());
            set => _featureSubgraphs = value;
        }

        /// <summary>
        /// Indicates whether the feature flag is enabled.
        /// </summary>
        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// The labels associated with the feature flag. These labels indicate which 
        /// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The name of the feature flag.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The namespace of the feature flag.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// The timestamp when the feature flag was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public FeatureFlagState()
        {
        }
        public static new FeatureFlagState Empty => new FeatureFlagState();
    }
}
