// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo
{
    public static class GetClients
    {
        public static Task<GetClientsResult> InvokeAsync(GetClientsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetClientsResult>("cosmo:index/getClients:getClients", args ?? new GetClientsArgs(), options.WithDefaults());

        public static Output<GetClientsResult> Invoke(GetClientsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetClientsResult>("cosmo:index/getClients:getClients", args ?? new GetClientsInvokeArgs(), options.WithDefaults());

        public static Output<GetClientsResult> Invoke(GetClientsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetClientsResult>("cosmo:index/getClients:getClients", args ?? new GetClientsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetClientsArgs : global::Pulumi.InvokeArgs
    {
        [Input("federatedGraphName", required: true)]
        public string FederatedGraphName { get; set; } = null!;

        [Input("namespace")]
        public string? Namespace { get; set; }

        public GetClientsArgs()
        {
        }
        public static new GetClientsArgs Empty => new GetClientsArgs();
    }

    public sealed class GetClientsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("federatedGraphName", required: true)]
        public Input<string> FederatedGraphName { get; set; } = null!;

        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public GetClientsInvokeArgs()
        {
        }
        public static new GetClientsInvokeArgs Empty => new GetClientsInvokeArgs();
    }


    [OutputType]
    public sealed class GetClientsResult
    {
        public readonly ImmutableArray<Outputs.GetClientsClientResult> Clients;
        public readonly string FederatedGraphName;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Namespace;

        [OutputConstructor]
        private GetClientsResult(
            ImmutableArray<Outputs.GetClientsClientResult> clients,

            string federatedGraphName,

            string id,

            string @namespace)
        {
            Clients = clients;
            FederatedGraphName = federatedGraphName;
            Id = id;
            Namespace = @namespace;
        }
    }
}
