// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo
{
    public static class GetFederatedGraph
    {
        public static Task<GetFederatedGraphResult> InvokeAsync(GetFederatedGraphArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetFederatedGraphResult>("cosmo:index/getFederatedGraph:getFederatedGraph", args ?? new GetFederatedGraphArgs(), options.WithDefaults());

        public static Output<GetFederatedGraphResult> Invoke(GetFederatedGraphInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetFederatedGraphResult>("cosmo:index/getFederatedGraph:getFederatedGraph", args ?? new GetFederatedGraphInvokeArgs(), options.WithDefaults());

        public static Output<GetFederatedGraphResult> Invoke(GetFederatedGraphInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetFederatedGraphResult>("cosmo:index/getFederatedGraph:getFederatedGraph", args ?? new GetFederatedGraphInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetFederatedGraphArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("namespace", required: true)]
        public string Namespace { get; set; } = null!;

        public GetFederatedGraphArgs()
        {
        }
        public static new GetFederatedGraphArgs Empty => new GetFederatedGraphArgs();
    }

    public sealed class GetFederatedGraphInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        public GetFederatedGraphInvokeArgs()
        {
        }
        public static new GetFederatedGraphInvokeArgs Empty => new GetFederatedGraphInvokeArgs();
    }


    [OutputType]
    public sealed class GetFederatedGraphResult
    {
        public readonly string AdmissionWebhookSecret;
        public readonly string AdmissionWebhookUrl;
        public readonly string Id;
        public readonly ImmutableDictionary<string, string> LabelMatchers;
        public readonly string Name;
        public readonly string Namespace;
        public readonly string Readme;
        public readonly string RoutingUrl;

        [OutputConstructor]
        private GetFederatedGraphResult(
            string admissionWebhookSecret,

            string admissionWebhookUrl,

            string id,

            ImmutableDictionary<string, string> labelMatchers,

            string name,

            string @namespace,

            string readme,

            string routingUrl)
        {
            AdmissionWebhookSecret = admissionWebhookSecret;
            AdmissionWebhookUrl = admissionWebhookUrl;
            Id = id;
            LabelMatchers = labelMatchers;
            Name = name;
            Namespace = @namespace;
            Readme = readme;
            RoutingUrl = routingUrl;
        }
    }
}
