// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo
{
    public static class GetSubgraph
    {
        public static Task<GetSubgraphResult> InvokeAsync(GetSubgraphArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSubgraphResult>("cosmo:index/getSubgraph:getSubgraph", args ?? new GetSubgraphArgs(), options.WithDefaults());

        public static Output<GetSubgraphResult> Invoke(GetSubgraphInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSubgraphResult>("cosmo:index/getSubgraph:getSubgraph", args ?? new GetSubgraphInvokeArgs(), options.WithDefaults());

        public static Output<GetSubgraphResult> Invoke(GetSubgraphInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSubgraphResult>("cosmo:index/getSubgraph:getSubgraph", args ?? new GetSubgraphInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSubgraphArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("namespace", required: true)]
        public string Namespace { get; set; } = null!;

        public GetSubgraphArgs()
        {
        }
        public static new GetSubgraphArgs Empty => new GetSubgraphArgs();
    }

    public sealed class GetSubgraphInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        public GetSubgraphInvokeArgs()
        {
        }
        public static new GetSubgraphInvokeArgs Empty => new GetSubgraphInvokeArgs();
    }


    [OutputType]
    public sealed class GetSubgraphResult
    {
        public readonly string BaseSubgraphName;
        public readonly ImmutableArray<string> Headers;
        public readonly string Id;
        public readonly bool IsEventDrivenGraph;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string Name;
        public readonly string Namespace;
        public readonly string Readme;
        public readonly string RoutingUrl;
        public readonly string Schema;
        public readonly string SubscriptionProtocol;
        public readonly string SubscriptionUrl;
        public readonly string WebsocketSubprotocol;

        [OutputConstructor]
        private GetSubgraphResult(
            string baseSubgraphName,

            ImmutableArray<string> headers,

            string id,

            bool isEventDrivenGraph,

            ImmutableDictionary<string, string> labels,

            string name,

            string @namespace,

            string readme,

            string routingUrl,

            string schema,

            string subscriptionProtocol,

            string subscriptionUrl,

            string websocketSubprotocol)
        {
            BaseSubgraphName = baseSubgraphName;
            Headers = headers;
            Id = id;
            IsEventDrivenGraph = isEventDrivenGraph;
            Labels = labels;
            Name = name;
            Namespace = @namespace;
            Readme = readme;
            RoutingUrl = routingUrl;
            Schema = schema;
            SubscriptionProtocol = subscriptionProtocol;
            SubscriptionUrl = subscriptionUrl;
            WebsocketSubprotocol = websocketSubprotocol;
        }
    }
}
