// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo
{
    [CosmoResourceType("cosmo:index/monograph:Monograph")]
    public partial class Monograph : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The admission webhook secret for the monograph.
        /// </summary>
        [Output("admissionWebhookSecret")]
        public Output<string?> AdmissionWebhookSecret { get; private set; } = null!;

        /// <summary>
        /// The admission webhook URL for the monograph.
        /// </summary>
        [Output("admissionWebhookUrl")]
        public Output<string?> AdmissionWebhookUrl { get; private set; } = null!;

        /// <summary>
        /// The GraphQL endpoint URL of the monograph.
        /// </summary>
        [Output("graphUrl")]
        public Output<string> GraphUrl { get; private set; } = null!;

        /// <summary>
        /// The name of the monograph.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The namespace in which the monograph is located.
        /// </summary>
        [Output("namespace")]
        public Output<string> Namespace { get; private set; } = null!;

        /// <summary>
        /// The readme for the subgraph.
        /// </summary>
        [Output("readme")]
        public Output<string?> Readme { get; private set; } = null!;

        /// <summary>
        /// The routing URL for the monograph.
        /// </summary>
        [Output("routingUrl")]
        public Output<string> RoutingUrl { get; private set; } = null!;

        /// <summary>
        /// The schema for the subgraph.
        /// </summary>
        [Output("schema")]
        public Output<string?> Schema { get; private set; } = null!;

        /// <summary>
        /// The subscription protocol for the subgraph.
        /// </summary>
        [Output("subscriptionProtocol")]
        public Output<string?> SubscriptionProtocol { get; private set; } = null!;

        /// <summary>
        /// The subscription URL for the subgraph.
        /// </summary>
        [Output("subscriptionUrl")]
        public Output<string?> SubscriptionUrl { get; private set; } = null!;

        /// <summary>
        /// The websocket subprotocol for the subgraph.
        /// </summary>
        [Output("websocketSubprotocol")]
        public Output<string?> WebsocketSubprotocol { get; private set; } = null!;


        /// <summary>
        /// Create a Monograph resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Monograph(string name, MonographArgs args, CustomResourceOptions? options = null)
            : base("cosmo:index/monograph:Monograph", name, args ?? new MonographArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Monograph(string name, Input<string> id, MonographState? state = null, CustomResourceOptions? options = null)
            : base("cosmo:index/monograph:Monograph", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/wundergraph/pulumi-cosmo/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Monograph resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Monograph Get(string name, Input<string> id, MonographState? state = null, CustomResourceOptions? options = null)
        {
            return new Monograph(name, id, state, options);
        }
    }

    public sealed class MonographArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The admission webhook secret for the monograph.
        /// </summary>
        [Input("admissionWebhookSecret")]
        public Input<string>? AdmissionWebhookSecret { get; set; }

        /// <summary>
        /// The admission webhook URL for the monograph.
        /// </summary>
        [Input("admissionWebhookUrl")]
        public Input<string>? AdmissionWebhookUrl { get; set; }

        /// <summary>
        /// The GraphQL endpoint URL of the monograph.
        /// </summary>
        [Input("graphUrl", required: true)]
        public Input<string> GraphUrl { get; set; } = null!;

        /// <summary>
        /// The name of the monograph.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The namespace in which the monograph is located.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// The readme for the subgraph.
        /// </summary>
        [Input("readme")]
        public Input<string>? Readme { get; set; }

        /// <summary>
        /// The routing URL for the monograph.
        /// </summary>
        [Input("routingUrl", required: true)]
        public Input<string> RoutingUrl { get; set; } = null!;

        /// <summary>
        /// The schema for the subgraph.
        /// </summary>
        [Input("schema")]
        public Input<string>? Schema { get; set; }

        /// <summary>
        /// The subscription protocol for the subgraph.
        /// </summary>
        [Input("subscriptionProtocol")]
        public Input<string>? SubscriptionProtocol { get; set; }

        /// <summary>
        /// The subscription URL for the subgraph.
        /// </summary>
        [Input("subscriptionUrl")]
        public Input<string>? SubscriptionUrl { get; set; }

        /// <summary>
        /// The websocket subprotocol for the subgraph.
        /// </summary>
        [Input("websocketSubprotocol")]
        public Input<string>? WebsocketSubprotocol { get; set; }

        public MonographArgs()
        {
        }
        public static new MonographArgs Empty => new MonographArgs();
    }

    public sealed class MonographState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The admission webhook secret for the monograph.
        /// </summary>
        [Input("admissionWebhookSecret")]
        public Input<string>? AdmissionWebhookSecret { get; set; }

        /// <summary>
        /// The admission webhook URL for the monograph.
        /// </summary>
        [Input("admissionWebhookUrl")]
        public Input<string>? AdmissionWebhookUrl { get; set; }

        /// <summary>
        /// The GraphQL endpoint URL of the monograph.
        /// </summary>
        [Input("graphUrl")]
        public Input<string>? GraphUrl { get; set; }

        /// <summary>
        /// The name of the monograph.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The namespace in which the monograph is located.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// The readme for the subgraph.
        /// </summary>
        [Input("readme")]
        public Input<string>? Readme { get; set; }

        /// <summary>
        /// The routing URL for the monograph.
        /// </summary>
        [Input("routingUrl")]
        public Input<string>? RoutingUrl { get; set; }

        /// <summary>
        /// The schema for the subgraph.
        /// </summary>
        [Input("schema")]
        public Input<string>? Schema { get; set; }

        /// <summary>
        /// The subscription protocol for the subgraph.
        /// </summary>
        [Input("subscriptionProtocol")]
        public Input<string>? SubscriptionProtocol { get; set; }

        /// <summary>
        /// The subscription URL for the subgraph.
        /// </summary>
        [Input("subscriptionUrl")]
        public Input<string>? SubscriptionUrl { get; set; }

        /// <summary>
        /// The websocket subprotocol for the subgraph.
        /// </summary>
        [Input("websocketSubprotocol")]
        public Input<string>? WebsocketSubprotocol { get; set; }

        public MonographState()
        {
        }
        public static new MonographState Empty => new MonographState();
    }
}
