// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo
{
    [CosmoResourceType("cosmo:index/persistedOperations:PersistedOperations")]
    public partial class PersistedOperations : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the client the operations belong to (e.g. `Web`, `Ios`). The client is created on first publish.
        /// </summary>
        [Output("clientName")]
        public Output<string> ClientName { get; private set; } = null!;

        /// <summary>
        /// The name of the federated graph to register the operations on.
        /// </summary>
        [Output("federatedGraphName")]
        public Output<string> FederatedGraphName { get; private set; } = null!;

        /// <summary>
        /// The namespace of the federated graph.
        /// </summary>
        [Output("namespace")]
        public Output<string> Namespace { get; private set; } = null!;

        /// <summary>
        /// The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        /// </summary>
        [Output("operations")]
        public Output<ImmutableDictionary<string, string>> Operations { get; private set; } = null!;


        /// <summary>
        /// Create a PersistedOperations resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PersistedOperations(string name, PersistedOperationsArgs args, CustomResourceOptions? options = null)
            : base("cosmo:index/persistedOperations:PersistedOperations", name, args ?? new PersistedOperationsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PersistedOperations(string name, Input<string> id, PersistedOperationsState? state = null, CustomResourceOptions? options = null)
            : base("cosmo:index/persistedOperations:PersistedOperations", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/primait/pulumi-cosmo/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PersistedOperations resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PersistedOperations Get(string name, Input<string> id, PersistedOperationsState? state = null, CustomResourceOptions? options = null)
        {
            return new PersistedOperations(name, id, state, options);
        }
    }

    public sealed class PersistedOperationsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the client the operations belong to (e.g. `Web`, `Ios`). The client is created on first publish.
        /// </summary>
        [Input("clientName", required: true)]
        public Input<string> ClientName { get; set; } = null!;

        /// <summary>
        /// The name of the federated graph to register the operations on.
        /// </summary>
        [Input("federatedGraphName", required: true)]
        public Input<string> FederatedGraphName { get; set; } = null!;

        /// <summary>
        /// The namespace of the federated graph.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        [Input("operations", required: true)]
        private InputMap<string>? _operations;

        /// <summary>
        /// The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        /// </summary>
        public InputMap<string> Operations
        {
            get => _operations ?? (_operations = new InputMap<string>());
            set => _operations = value;
        }

        public PersistedOperationsArgs()
        {
        }
        public static new PersistedOperationsArgs Empty => new PersistedOperationsArgs();
    }

    public sealed class PersistedOperationsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the client the operations belong to (e.g. `Web`, `Ios`). The client is created on first publish.
        /// </summary>
        [Input("clientName")]
        public Input<string>? ClientName { get; set; }

        /// <summary>
        /// The name of the federated graph to register the operations on.
        /// </summary>
        [Input("federatedGraphName")]
        public Input<string>? FederatedGraphName { get; set; }

        /// <summary>
        /// The namespace of the federated graph.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        [Input("operations")]
        private InputMap<string>? _operations;

        /// <summary>
        /// The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        /// </summary>
        public InputMap<string> Operations
        {
            get => _operations ?? (_operations = new InputMap<string>());
            set => _operations = value;
        }

        public PersistedOperationsState()
        {
        }
        public static new PersistedOperationsState Empty => new PersistedOperationsState();
    }
}
