// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

var _ = internal.GetEnvOrDefault

// The Api Key to be used: Leave blank to use the COSMO_API_KEY environment variable
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "cosmo:apiKey")
}

// The Api Url to be used: Leave blank to use: https://cosmo-cp.wundergraph.com or use the COSMO_API_URL environment variable
func GetApiUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "cosmo:apiUrl")
}
