// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContractState extends com.pulumi.resources.ResourceArgs {

    public static final ContractState Empty = new ContractState();

    @Import(name="admissionWebhookSecret")
    private @Nullable Output<String> admissionWebhookSecret;

    public Optional<Output<String>> admissionWebhookSecret() {
        return Optional.ofNullable(this.admissionWebhookSecret);
    }

    @Import(name="admissionWebhookUrl")
    private @Nullable Output<String> admissionWebhookUrl;

    public Optional<Output<String>> admissionWebhookUrl() {
        return Optional.ofNullable(this.admissionWebhookUrl);
    }

    @Import(name="excludeTags")
    private @Nullable Output<List<String>> excludeTags;

    public Optional<Output<List<String>>> excludeTags() {
        return Optional.ofNullable(this.excludeTags);
    }

    @Import(name="includeTags")
    private @Nullable Output<List<String>> includeTags;

    public Optional<Output<List<String>>> includeTags() {
        return Optional.ofNullable(this.includeTags);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    @Import(name="readme")
    private @Nullable Output<String> readme;

    public Optional<Output<String>> readme() {
        return Optional.ofNullable(this.readme);
    }

    @Import(name="routingUrl")
    private @Nullable Output<String> routingUrl;

    public Optional<Output<String>> routingUrl() {
        return Optional.ofNullable(this.routingUrl);
    }

    @Import(name="source")
    private @Nullable Output<String> source;

    public Optional<Output<String>> source() {
        return Optional.ofNullable(this.source);
    }

    @Import(name="supportsFederation")
    private @Nullable Output<Boolean> supportsFederation;

    public Optional<Output<Boolean>> supportsFederation() {
        return Optional.ofNullable(this.supportsFederation);
    }

    private ContractState() {}

    private ContractState(ContractState $) {
        this.admissionWebhookSecret = $.admissionWebhookSecret;
        this.admissionWebhookUrl = $.admissionWebhookUrl;
        this.excludeTags = $.excludeTags;
        this.includeTags = $.includeTags;
        this.name = $.name;
        this.namespace = $.namespace;
        this.readme = $.readme;
        this.routingUrl = $.routingUrl;
        this.source = $.source;
        this.supportsFederation = $.supportsFederation;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContractState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContractState $;

        public Builder() {
            $ = new ContractState();
        }

        public Builder(ContractState defaults) {
            $ = new ContractState(Objects.requireNonNull(defaults));
        }

        public Builder admissionWebhookSecret(@Nullable Output<String> admissionWebhookSecret) {
            $.admissionWebhookSecret = admissionWebhookSecret;
            return this;
        }

        public Builder admissionWebhookSecret(String admissionWebhookSecret) {
            return admissionWebhookSecret(Output.of(admissionWebhookSecret));
        }

        public Builder admissionWebhookUrl(@Nullable Output<String> admissionWebhookUrl) {
            $.admissionWebhookUrl = admissionWebhookUrl;
            return this;
        }

        public Builder admissionWebhookUrl(String admissionWebhookUrl) {
            return admissionWebhookUrl(Output.of(admissionWebhookUrl));
        }

        public Builder excludeTags(@Nullable Output<List<String>> excludeTags) {
            $.excludeTags = excludeTags;
            return this;
        }

        public Builder excludeTags(List<String> excludeTags) {
            return excludeTags(Output.of(excludeTags));
        }

        public Builder excludeTags(String... excludeTags) {
            return excludeTags(List.of(excludeTags));
        }

        public Builder includeTags(@Nullable Output<List<String>> includeTags) {
            $.includeTags = includeTags;
            return this;
        }

        public Builder includeTags(List<String> includeTags) {
            return includeTags(Output.of(includeTags));
        }

        public Builder includeTags(String... includeTags) {
            return includeTags(List.of(includeTags));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        public Builder readme(@Nullable Output<String> readme) {
            $.readme = readme;
            return this;
        }

        public Builder readme(String readme) {
            return readme(Output.of(readme));
        }

        public Builder routingUrl(@Nullable Output<String> routingUrl) {
            $.routingUrl = routingUrl;
            return this;
        }

        public Builder routingUrl(String routingUrl) {
            return routingUrl(Output.of(routingUrl));
        }

        public Builder source(@Nullable Output<String> source) {
            $.source = source;
            return this;
        }

        public Builder source(String source) {
            return source(Output.of(source));
        }

        public Builder supportsFederation(@Nullable Output<Boolean> supportsFederation) {
            $.supportsFederation = supportsFederation;
            return this;
        }

        public Builder supportsFederation(Boolean supportsFederation) {
            return supportsFederation(Output.of(supportsFederation));
        }

        public ContractState build() {
            return $;
        }
    }

}
