// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FeatureSubgraphState extends com.pulumi.resources.ResourceArgs {

    public static final FeatureSubgraphState Empty = new FeatureSubgraphState();

    /**
     * The name of the base subgraph that this feature subgraph extends.
     * 
     */
    @Import(name="baseSubgraphName")
    private @Nullable Output<String> baseSubgraphName;

    /**
     * @return The name of the base subgraph that this feature subgraph extends.
     * 
     */
    public Optional<Output<String>> baseSubgraphName() {
        return Optional.ofNullable(this.baseSubgraphName);
    }

    /**
     * The name of the feature subgraph.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the feature subgraph.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The namespace to create the feature subgraph in.
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return The namespace to create the feature subgraph in.
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    /**
     * The readme for the subgraph.
     * 
     */
    @Import(name="readme")
    private @Nullable Output<String> readme;

    /**
     * @return The readme for the subgraph.
     * 
     */
    public Optional<Output<String>> readme() {
        return Optional.ofNullable(this.readme);
    }

    /**
     * The routing URL of the feature subgraph.
     * 
     */
    @Import(name="routingUrl")
    private @Nullable Output<String> routingUrl;

    /**
     * @return The routing URL of the feature subgraph.
     * 
     */
    public Optional<Output<String>> routingUrl() {
        return Optional.ofNullable(this.routingUrl);
    }

    /**
     * The schema for the subgraph.
     * 
     */
    @Import(name="schema")
    private @Nullable Output<String> schema;

    /**
     * @return The schema for the subgraph.
     * 
     */
    public Optional<Output<String>> schema() {
        return Optional.ofNullable(this.schema);
    }

    /**
     * The subscription protocol for the subgraph.
     * 
     */
    @Import(name="subscriptionProtocol")
    private @Nullable Output<String> subscriptionProtocol;

    /**
     * @return The subscription protocol for the subgraph.
     * 
     */
    public Optional<Output<String>> subscriptionProtocol() {
        return Optional.ofNullable(this.subscriptionProtocol);
    }

    /**
     * The subscription URL for the subgraph.
     * 
     */
    @Import(name="subscriptionUrl")
    private @Nullable Output<String> subscriptionUrl;

    /**
     * @return The subscription URL for the subgraph.
     * 
     */
    public Optional<Output<String>> subscriptionUrl() {
        return Optional.ofNullable(this.subscriptionUrl);
    }

    /**
     * The websocket subprotocol for the subgraph.
     * 
     */
    @Import(name="websocketSubprotocol")
    private @Nullable Output<String> websocketSubprotocol;

    /**
     * @return The websocket subprotocol for the subgraph.
     * 
     */
    public Optional<Output<String>> websocketSubprotocol() {
        return Optional.ofNullable(this.websocketSubprotocol);
    }

    private FeatureSubgraphState() {}

    private FeatureSubgraphState(FeatureSubgraphState $) {
        this.baseSubgraphName = $.baseSubgraphName;
        this.name = $.name;
        this.namespace = $.namespace;
        this.readme = $.readme;
        this.routingUrl = $.routingUrl;
        this.schema = $.schema;
        this.subscriptionProtocol = $.subscriptionProtocol;
        this.subscriptionUrl = $.subscriptionUrl;
        this.websocketSubprotocol = $.websocketSubprotocol;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FeatureSubgraphState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FeatureSubgraphState $;

        public Builder() {
            $ = new FeatureSubgraphState();
        }

        public Builder(FeatureSubgraphState defaults) {
            $ = new FeatureSubgraphState(Objects.requireNonNull(defaults));
        }

        /**
         * @param baseSubgraphName The name of the base subgraph that this feature subgraph extends.
         * 
         * @return builder
         * 
         */
        public Builder baseSubgraphName(@Nullable Output<String> baseSubgraphName) {
            $.baseSubgraphName = baseSubgraphName;
            return this;
        }

        /**
         * @param baseSubgraphName The name of the base subgraph that this feature subgraph extends.
         * 
         * @return builder
         * 
         */
        public Builder baseSubgraphName(String baseSubgraphName) {
            return baseSubgraphName(Output.of(baseSubgraphName));
        }

        /**
         * @param name The name of the feature subgraph.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the feature subgraph.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param namespace The namespace to create the feature subgraph in.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace The namespace to create the feature subgraph in.
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        /**
         * @param readme The readme for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder readme(@Nullable Output<String> readme) {
            $.readme = readme;
            return this;
        }

        /**
         * @param readme The readme for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder readme(String readme) {
            return readme(Output.of(readme));
        }

        /**
         * @param routingUrl The routing URL of the feature subgraph.
         * 
         * @return builder
         * 
         */
        public Builder routingUrl(@Nullable Output<String> routingUrl) {
            $.routingUrl = routingUrl;
            return this;
        }

        /**
         * @param routingUrl The routing URL of the feature subgraph.
         * 
         * @return builder
         * 
         */
        public Builder routingUrl(String routingUrl) {
            return routingUrl(Output.of(routingUrl));
        }

        /**
         * @param schema The schema for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder schema(@Nullable Output<String> schema) {
            $.schema = schema;
            return this;
        }

        /**
         * @param schema The schema for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder schema(String schema) {
            return schema(Output.of(schema));
        }

        /**
         * @param subscriptionProtocol The subscription protocol for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionProtocol(@Nullable Output<String> subscriptionProtocol) {
            $.subscriptionProtocol = subscriptionProtocol;
            return this;
        }

        /**
         * @param subscriptionProtocol The subscription protocol for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionProtocol(String subscriptionProtocol) {
            return subscriptionProtocol(Output.of(subscriptionProtocol));
        }

        /**
         * @param subscriptionUrl The subscription URL for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionUrl(@Nullable Output<String> subscriptionUrl) {
            $.subscriptionUrl = subscriptionUrl;
            return this;
        }

        /**
         * @param subscriptionUrl The subscription URL for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder subscriptionUrl(String subscriptionUrl) {
            return subscriptionUrl(Output.of(subscriptionUrl));
        }

        /**
         * @param websocketSubprotocol The websocket subprotocol for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder websocketSubprotocol(@Nullable Output<String> websocketSubprotocol) {
            $.websocketSubprotocol = websocketSubprotocol;
            return this;
        }

        /**
         * @param websocketSubprotocol The websocket subprotocol for the subgraph.
         * 
         * @return builder
         * 
         */
        public Builder websocketSubprotocol(String websocketSubprotocol) {
            return websocketSubprotocol(Output.of(websocketSubprotocol));
        }

        public FeatureSubgraphState build() {
            return $;
        }
    }

}
