// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FeatureFlagState extends com.pulumi.resources.ResourceArgs {

    public static final FeatureFlagState Empty = new FeatureFlagState();

    /**
     * The timestamp when the feature flag was created.
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return The timestamp when the feature flag was created.
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * The user who created the feature flag.
     * 
     */
    @Import(name="createdBy")
    private @Nullable Output<String> createdBy;

    /**
     * @return The user who created the feature flag.
     * 
     */
    public Optional<Output<String>> createdBy() {
        return Optional.ofNullable(this.createdBy);
    }

    /**
     * The list of feature subgraphs associated with the feature flag.
     * At least one feature subgraph must be provided.
     * 
     */
    @Import(name="featureSubgraphs")
    private @Nullable Output<List<String>> featureSubgraphs;

    /**
     * @return The list of feature subgraphs associated with the feature flag.
     * At least one feature subgraph must be provided.
     * 
     */
    public Optional<Output<List<String>>> featureSubgraphs() {
        return Optional.ofNullable(this.featureSubgraphs);
    }

    /**
     * Indicates whether the feature flag is enabled.
     * 
     */
    @Import(name="isEnabled")
    private @Nullable Output<Boolean> isEnabled;

    /**
     * @return Indicates whether the feature flag is enabled.
     * 
     */
    public Optional<Output<Boolean>> isEnabled() {
        return Optional.ofNullable(this.isEnabled);
    }

    /**
     * The labels associated with the feature flag. These labels indicate which
     * federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
     * 
     */
    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    /**
     * @return The labels associated with the feature flag. These labels indicate which
     * federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
     * 
     */
    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * The name of the feature flag.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the feature flag.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The namespace of the feature flag.
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return The namespace of the feature flag.
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    /**
     * The timestamp when the feature flag was last updated.
     * 
     */
    @Import(name="updatedAt")
    private @Nullable Output<String> updatedAt;

    /**
     * @return The timestamp when the feature flag was last updated.
     * 
     */
    public Optional<Output<String>> updatedAt() {
        return Optional.ofNullable(this.updatedAt);
    }

    private FeatureFlagState() {}

    private FeatureFlagState(FeatureFlagState $) {
        this.createdAt = $.createdAt;
        this.createdBy = $.createdBy;
        this.featureSubgraphs = $.featureSubgraphs;
        this.isEnabled = $.isEnabled;
        this.labels = $.labels;
        this.name = $.name;
        this.namespace = $.namespace;
        this.updatedAt = $.updatedAt;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FeatureFlagState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FeatureFlagState $;

        public Builder() {
            $ = new FeatureFlagState();
        }

        public Builder(FeatureFlagState defaults) {
            $ = new FeatureFlagState(Objects.requireNonNull(defaults));
        }

        /**
         * @param createdAt The timestamp when the feature flag was created.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt The timestamp when the feature flag was created.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param createdBy The user who created the feature flag.
         * 
         * @return builder
         * 
         */
        public Builder createdBy(@Nullable Output<String> createdBy) {
            $.createdBy = createdBy;
            return this;
        }

        /**
         * @param createdBy The user who created the feature flag.
         * 
         * @return builder
         * 
         */
        public Builder createdBy(String createdBy) {
            return createdBy(Output.of(createdBy));
        }

        /**
         * @param featureSubgraphs The list of feature subgraphs associated with the feature flag.
         * At least one feature subgraph must be provided.
         * 
         * @return builder
         * 
         */
        public Builder featureSubgraphs(@Nullable Output<List<String>> featureSubgraphs) {
            $.featureSubgraphs = featureSubgraphs;
            return this;
        }

        /**
         * @param featureSubgraphs The list of feature subgraphs associated with the feature flag.
         * At least one feature subgraph must be provided.
         * 
         * @return builder
         * 
         */
        public Builder featureSubgraphs(List<String> featureSubgraphs) {
            return featureSubgraphs(Output.of(featureSubgraphs));
        }

        /**
         * @param featureSubgraphs The list of feature subgraphs associated with the feature flag.
         * At least one feature subgraph must be provided.
         * 
         * @return builder
         * 
         */
        public Builder featureSubgraphs(String... featureSubgraphs) {
            return featureSubgraphs(List.of(featureSubgraphs));
        }

        /**
         * @param isEnabled Indicates whether the feature flag is enabled.
         * 
         * @return builder
         * 
         */
        public Builder isEnabled(@Nullable Output<Boolean> isEnabled) {
            $.isEnabled = isEnabled;
            return this;
        }

        /**
         * @param isEnabled Indicates whether the feature flag is enabled.
         * 
         * @return builder
         * 
         */
        public Builder isEnabled(Boolean isEnabled) {
            return isEnabled(Output.of(isEnabled));
        }

        /**
         * @param labels The labels associated with the feature flag. These labels indicate which
         * federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
         * 
         * @return builder
         * 
         */
        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        /**
         * @param labels The labels associated with the feature flag. These labels indicate which
         * federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
         * 
         * @return builder
         * 
         */
        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        /**
         * @param name The name of the feature flag.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the feature flag.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param namespace The namespace of the feature flag.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace The namespace of the feature flag.
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        /**
         * @param updatedAt The timestamp when the feature flag was last updated.
         * 
         * @return builder
         * 
         */
        public Builder updatedAt(@Nullable Output<String> updatedAt) {
            $.updatedAt = updatedAt;
            return this;
        }

        /**
         * @param updatedAt The timestamp when the feature flag was last updated.
         * 
         * @return builder
         * 
         */
        public Builder updatedAt(String updatedAt) {
            return updatedAt(Output.of(updatedAt));
        }

        public FeatureFlagState build() {
            return $;
        }
    }

}
