// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetContractArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetContractArgs Empty = new GetContractArgs();

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="namespace", required=true)
    private Output<String> namespace;

    public Output<String> namespace() {
        return this.namespace;
    }

    private GetContractArgs() {}

    private GetContractArgs(GetContractArgs $) {
        this.name = $.name;
        this.namespace = $.namespace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetContractArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetContractArgs $;

        public Builder() {
            $ = new GetContractArgs();
        }

        public Builder(GetContractArgs defaults) {
            $ = new GetContractArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder namespace(Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        public GetContractArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetContractArgs", "name");
            }
            if ($.namespace == null) {
                throw new MissingRequiredPropertyException("GetContractArgs", "namespace");
            }
            return $;
        }
    }

}
