// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetContractPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetContractPlainArgs Empty = new GetContractPlainArgs();

    @Import(name="name", required=true)
    private String name;

    public String name() {
        return this.name;
    }

    @Import(name="namespace", required=true)
    private String namespace;

    public String namespace() {
        return this.namespace;
    }

    private GetContractPlainArgs() {}

    private GetContractPlainArgs(GetContractPlainArgs $) {
        this.name = $.name;
        this.namespace = $.namespace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetContractPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetContractPlainArgs $;

        public Builder() {
            $ = new GetContractPlainArgs();
        }

        public Builder(GetContractPlainArgs defaults) {
            $ = new GetContractPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public Builder namespace(String namespace) {
            $.namespace = namespace;
            return this;
        }

        public GetContractPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetContractPlainArgs", "name");
            }
            if ($.namespace == null) {
                throw new MissingRequiredPropertyException("GetContractPlainArgs", "namespace");
            }
            return $;
        }
    }

}
