// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetFeatureSubgraphArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetFeatureSubgraphArgs Empty = new GetFeatureSubgraphArgs();

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    private GetFeatureSubgraphArgs() {}

    private GetFeatureSubgraphArgs(GetFeatureSubgraphArgs $) {
        this.name = $.name;
        this.namespace = $.namespace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetFeatureSubgraphArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetFeatureSubgraphArgs $;

        public Builder() {
            $ = new GetFeatureSubgraphArgs();
        }

        public Builder(GetFeatureSubgraphArgs defaults) {
            $ = new GetFeatureSubgraphArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        public GetFeatureSubgraphArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetFeatureSubgraphArgs", "name");
            }
            return $;
        }
    }

}
