// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetFeatureSubgraphPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetFeatureSubgraphPlainArgs Empty = new GetFeatureSubgraphPlainArgs();

    @Import(name="name", required=true)
    private String name;

    public String name() {
        return this.name;
    }

    @Import(name="namespace")
    private @Nullable String namespace;

    public Optional<String> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    private GetFeatureSubgraphPlainArgs() {}

    private GetFeatureSubgraphPlainArgs(GetFeatureSubgraphPlainArgs $) {
        this.name = $.name;
        this.namespace = $.namespace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetFeatureSubgraphPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetFeatureSubgraphPlainArgs $;

        public Builder() {
            $ = new GetFeatureSubgraphPlainArgs();
        }

        public Builder(GetFeatureSubgraphPlainArgs defaults) {
            $ = new GetFeatureSubgraphPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public Builder namespace(@Nullable String namespace) {
            $.namespace = namespace;
            return this;
        }

        public GetFeatureSubgraphPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetFeatureSubgraphPlainArgs", "name");
            }
            return $;
        }
    }

}
