// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo.Outputs
{

    [OutputType]
    public sealed class GetClientsClientResult
    {
        /// <summary>
        /// The time the client was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The user that created the client.
        /// </summary>
        public readonly string CreatedBy;
        /// <summary>
        /// The unique identifier of the client.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The time the client was last updated.
        /// </summary>
        public readonly string LastUpdatedAt;
        /// <summary>
        /// The user that last updated the client.
        /// </summary>
        public readonly string LastUpdatedBy;
        /// <summary>
        /// The name of the client.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The number of persisted operations registered for the client.
        /// </summary>
        public readonly int PersistedOperationsCount;

        [OutputConstructor]
        private GetClientsClientResult(
            string createdAt,

            string createdBy,

            string id,

            string lastUpdatedAt,

            string lastUpdatedBy,

            string name,

            int persistedOperationsCount)
        {
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            Id = id;
            LastUpdatedAt = lastUpdatedAt;
            LastUpdatedBy = lastUpdatedBy;
            Name = name;
            PersistedOperationsCount = persistedOperationsCount;
        }
    }
}
