// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cosmo.Outputs
{

    [OutputType]
    public sealed class GetPersistedOperationsOperationResult
    {
        /// <summary>
        /// The GraphQL operation contents.
        /// </summary>
        public readonly string Contents;
        /// <summary>
        /// The time the operation was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The unique identifier of the operation (the SHA-256 hash of its contents).
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The time the operation was last updated.
        /// </summary>
        public readonly string LastUpdatedAt;
        /// <summary>
        /// The names of the operations contained in the document.
        /// </summary>
        public readonly ImmutableArray<string> OperationNames;

        [OutputConstructor]
        private GetPersistedOperationsOperationResult(
            string contents,

            string createdAt,

            string id,

            string lastUpdatedAt,

            ImmutableArray<string> operationNames)
        {
            Contents = contents;
            CreatedAt = createdAt;
            Id = id;
            LastUpdatedAt = lastUpdatedAt;
            OperationNames = operationNames;
        }
    }
}
