// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetContractResult {
    private String admissionWebhookSecret;
    private String admissionWebhookUrl;
    private List<String> excludeTags;
    private String id;
    private List<String> includeTags;
    private Map<String,String> labelMatchers;
    private String name;
    private String namespace;
    private String readme;
    private String routingUrl;
    private Boolean supportsFederation;

    private GetContractResult() {}
    public String admissionWebhookSecret() {
        return this.admissionWebhookSecret;
    }
    public String admissionWebhookUrl() {
        return this.admissionWebhookUrl;
    }
    public List<String> excludeTags() {
        return this.excludeTags;
    }
    public String id() {
        return this.id;
    }
    public List<String> includeTags() {
        return this.includeTags;
    }
    public Map<String,String> labelMatchers() {
        return this.labelMatchers;
    }
    public String name() {
        return this.name;
    }
    public String namespace() {
        return this.namespace;
    }
    public String readme() {
        return this.readme;
    }
    public String routingUrl() {
        return this.routingUrl;
    }
    public Boolean supportsFederation() {
        return this.supportsFederation;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetContractResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String admissionWebhookSecret;
        private String admissionWebhookUrl;
        private List<String> excludeTags;
        private String id;
        private List<String> includeTags;
        private Map<String,String> labelMatchers;
        private String name;
        private String namespace;
        private String readme;
        private String routingUrl;
        private Boolean supportsFederation;
        public Builder() {}
        public Builder(GetContractResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.admissionWebhookSecret = defaults.admissionWebhookSecret;
    	      this.admissionWebhookUrl = defaults.admissionWebhookUrl;
    	      this.excludeTags = defaults.excludeTags;
    	      this.id = defaults.id;
    	      this.includeTags = defaults.includeTags;
    	      this.labelMatchers = defaults.labelMatchers;
    	      this.name = defaults.name;
    	      this.namespace = defaults.namespace;
    	      this.readme = defaults.readme;
    	      this.routingUrl = defaults.routingUrl;
    	      this.supportsFederation = defaults.supportsFederation;
        }

        @CustomType.Setter
        public Builder admissionWebhookSecret(String admissionWebhookSecret) {
            if (admissionWebhookSecret == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "admissionWebhookSecret");
            }
            this.admissionWebhookSecret = admissionWebhookSecret;
            return this;
        }
        @CustomType.Setter
        public Builder admissionWebhookUrl(String admissionWebhookUrl) {
            if (admissionWebhookUrl == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "admissionWebhookUrl");
            }
            this.admissionWebhookUrl = admissionWebhookUrl;
            return this;
        }
        @CustomType.Setter
        public Builder excludeTags(List<String> excludeTags) {
            if (excludeTags == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "excludeTags");
            }
            this.excludeTags = excludeTags;
            return this;
        }
        public Builder excludeTags(String... excludeTags) {
            return excludeTags(List.of(excludeTags));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder includeTags(List<String> includeTags) {
            if (includeTags == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "includeTags");
            }
            this.includeTags = includeTags;
            return this;
        }
        public Builder includeTags(String... includeTags) {
            return includeTags(List.of(includeTags));
        }
        @CustomType.Setter
        public Builder labelMatchers(Map<String,String> labelMatchers) {
            if (labelMatchers == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "labelMatchers");
            }
            this.labelMatchers = labelMatchers;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder namespace(String namespace) {
            if (namespace == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "namespace");
            }
            this.namespace = namespace;
            return this;
        }
        @CustomType.Setter
        public Builder readme(String readme) {
            if (readme == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "readme");
            }
            this.readme = readme;
            return this;
        }
        @CustomType.Setter
        public Builder routingUrl(String routingUrl) {
            if (routingUrl == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "routingUrl");
            }
            this.routingUrl = routingUrl;
            return this;
        }
        @CustomType.Setter
        public Builder supportsFederation(Boolean supportsFederation) {
            if (supportsFederation == null) {
              throw new MissingRequiredPropertyException("GetContractResult", "supportsFederation");
            }
            this.supportsFederation = supportsFederation;
            return this;
        }
        public GetContractResult build() {
            final var _resultValue = new GetContractResult();
            _resultValue.admissionWebhookSecret = admissionWebhookSecret;
            _resultValue.admissionWebhookUrl = admissionWebhookUrl;
            _resultValue.excludeTags = excludeTags;
            _resultValue.id = id;
            _resultValue.includeTags = includeTags;
            _resultValue.labelMatchers = labelMatchers;
            _resultValue.name = name;
            _resultValue.namespace = namespace;
            _resultValue.readme = readme;
            _resultValue.routingUrl = routingUrl;
            _resultValue.supportsFederation = supportsFederation;
            return _resultValue;
        }
    }
}
