// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetFederatedGraphResult {
    private String admissionWebhookSecret;
    private String admissionWebhookUrl;
    private String id;
    private Map<String,String> labelMatchers;
    private String name;
    private String namespace;
    private String readme;
    private String routingUrl;

    private GetFederatedGraphResult() {}
    public String admissionWebhookSecret() {
        return this.admissionWebhookSecret;
    }
    public String admissionWebhookUrl() {
        return this.admissionWebhookUrl;
    }
    public String id() {
        return this.id;
    }
    public Map<String,String> labelMatchers() {
        return this.labelMatchers;
    }
    public String name() {
        return this.name;
    }
    public String namespace() {
        return this.namespace;
    }
    public String readme() {
        return this.readme;
    }
    public String routingUrl() {
        return this.routingUrl;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetFederatedGraphResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String admissionWebhookSecret;
        private String admissionWebhookUrl;
        private String id;
        private Map<String,String> labelMatchers;
        private String name;
        private String namespace;
        private String readme;
        private String routingUrl;
        public Builder() {}
        public Builder(GetFederatedGraphResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.admissionWebhookSecret = defaults.admissionWebhookSecret;
    	      this.admissionWebhookUrl = defaults.admissionWebhookUrl;
    	      this.id = defaults.id;
    	      this.labelMatchers = defaults.labelMatchers;
    	      this.name = defaults.name;
    	      this.namespace = defaults.namespace;
    	      this.readme = defaults.readme;
    	      this.routingUrl = defaults.routingUrl;
        }

        @CustomType.Setter
        public Builder admissionWebhookSecret(String admissionWebhookSecret) {
            if (admissionWebhookSecret == null) {
              throw new MissingRequiredPropertyException("GetFederatedGraphResult", "admissionWebhookSecret");
            }
            this.admissionWebhookSecret = admissionWebhookSecret;
            return this;
        }
        @CustomType.Setter
        public Builder admissionWebhookUrl(String admissionWebhookUrl) {
            if (admissionWebhookUrl == null) {
              throw new MissingRequiredPropertyException("GetFederatedGraphResult", "admissionWebhookUrl");
            }
            this.admissionWebhookUrl = admissionWebhookUrl;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetFederatedGraphResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder labelMatchers(Map<String,String> labelMatchers) {
            if (labelMatchers == null) {
              throw new MissingRequiredPropertyException("GetFederatedGraphResult", "labelMatchers");
            }
            this.labelMatchers = labelMatchers;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetFederatedGraphResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder namespace(String namespace) {
            if (namespace == null) {
              throw new MissingRequiredPropertyException("GetFederatedGraphResult", "namespace");
            }
            this.namespace = namespace;
            return this;
        }
        @CustomType.Setter
        public Builder readme(String readme) {
            if (readme == null) {
              throw new MissingRequiredPropertyException("GetFederatedGraphResult", "readme");
            }
            this.readme = readme;
            return this;
        }
        @CustomType.Setter
        public Builder routingUrl(String routingUrl) {
            if (routingUrl == null) {
              throw new MissingRequiredPropertyException("GetFederatedGraphResult", "routingUrl");
            }
            this.routingUrl = routingUrl;
            return this;
        }
        public GetFederatedGraphResult build() {
            final var _resultValue = new GetFederatedGraphResult();
            _resultValue.admissionWebhookSecret = admissionWebhookSecret;
            _resultValue.admissionWebhookUrl = admissionWebhookUrl;
            _resultValue.id = id;
            _resultValue.labelMatchers = labelMatchers;
            _resultValue.name = name;
            _resultValue.namespace = namespace;
            _resultValue.readme = readme;
            _resultValue.routingUrl = routingUrl;
            return _resultValue;
        }
    }
}
