// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetMonographResult {
    private String admissionWebhookSecret;
    private String admissionWebhookUrl;
    private String id;
    private List<String> labelMatchers;
    private String name;
    private @Nullable String namespace;
    private String readme;
    private String routingUrl;
    private String subscriptionProtocol;
    private String websocketSubprotocol;

    private GetMonographResult() {}
    public String admissionWebhookSecret() {
        return this.admissionWebhookSecret;
    }
    public String admissionWebhookUrl() {
        return this.admissionWebhookUrl;
    }
    public String id() {
        return this.id;
    }
    public List<String> labelMatchers() {
        return this.labelMatchers;
    }
    public String name() {
        return this.name;
    }
    public Optional<String> namespace() {
        return Optional.ofNullable(this.namespace);
    }
    public String readme() {
        return this.readme;
    }
    public String routingUrl() {
        return this.routingUrl;
    }
    public String subscriptionProtocol() {
        return this.subscriptionProtocol;
    }
    public String websocketSubprotocol() {
        return this.websocketSubprotocol;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMonographResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String admissionWebhookSecret;
        private String admissionWebhookUrl;
        private String id;
        private List<String> labelMatchers;
        private String name;
        private @Nullable String namespace;
        private String readme;
        private String routingUrl;
        private String subscriptionProtocol;
        private String websocketSubprotocol;
        public Builder() {}
        public Builder(GetMonographResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.admissionWebhookSecret = defaults.admissionWebhookSecret;
    	      this.admissionWebhookUrl = defaults.admissionWebhookUrl;
    	      this.id = defaults.id;
    	      this.labelMatchers = defaults.labelMatchers;
    	      this.name = defaults.name;
    	      this.namespace = defaults.namespace;
    	      this.readme = defaults.readme;
    	      this.routingUrl = defaults.routingUrl;
    	      this.subscriptionProtocol = defaults.subscriptionProtocol;
    	      this.websocketSubprotocol = defaults.websocketSubprotocol;
        }

        @CustomType.Setter
        public Builder admissionWebhookSecret(String admissionWebhookSecret) {
            if (admissionWebhookSecret == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "admissionWebhookSecret");
            }
            this.admissionWebhookSecret = admissionWebhookSecret;
            return this;
        }
        @CustomType.Setter
        public Builder admissionWebhookUrl(String admissionWebhookUrl) {
            if (admissionWebhookUrl == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "admissionWebhookUrl");
            }
            this.admissionWebhookUrl = admissionWebhookUrl;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder labelMatchers(List<String> labelMatchers) {
            if (labelMatchers == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "labelMatchers");
            }
            this.labelMatchers = labelMatchers;
            return this;
        }
        public Builder labelMatchers(String... labelMatchers) {
            return labelMatchers(List.of(labelMatchers));
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder namespace(@Nullable String namespace) {

            this.namespace = namespace;
            return this;
        }
        @CustomType.Setter
        public Builder readme(String readme) {
            if (readme == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "readme");
            }
            this.readme = readme;
            return this;
        }
        @CustomType.Setter
        public Builder routingUrl(String routingUrl) {
            if (routingUrl == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "routingUrl");
            }
            this.routingUrl = routingUrl;
            return this;
        }
        @CustomType.Setter
        public Builder subscriptionProtocol(String subscriptionProtocol) {
            if (subscriptionProtocol == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "subscriptionProtocol");
            }
            this.subscriptionProtocol = subscriptionProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder websocketSubprotocol(String websocketSubprotocol) {
            if (websocketSubprotocol == null) {
              throw new MissingRequiredPropertyException("GetMonographResult", "websocketSubprotocol");
            }
            this.websocketSubprotocol = websocketSubprotocol;
            return this;
        }
        public GetMonographResult build() {
            final var _resultValue = new GetMonographResult();
            _resultValue.admissionWebhookSecret = admissionWebhookSecret;
            _resultValue.admissionWebhookUrl = admissionWebhookUrl;
            _resultValue.id = id;
            _resultValue.labelMatchers = labelMatchers;
            _resultValue.name = name;
            _resultValue.namespace = namespace;
            _resultValue.readme = readme;
            _resultValue.routingUrl = routingUrl;
            _resultValue.subscriptionProtocol = subscriptionProtocol;
            _resultValue.websocketSubprotocol = websocketSubprotocol;
            return _resultValue;
        }
    }
}
