// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cosmo.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetSubgraphResult {
    private String baseSubgraphName;
    private List<String> headers;
    private String id;
    private Boolean isEventDrivenGraph;
    private Map<String,String> labels;
    private String name;
    private String namespace;
    private String readme;
    private String routingUrl;
    private String schema;
    private String subscriptionProtocol;
    private String subscriptionUrl;
    private String websocketSubprotocol;

    private GetSubgraphResult() {}
    public String baseSubgraphName() {
        return this.baseSubgraphName;
    }
    public List<String> headers() {
        return this.headers;
    }
    public String id() {
        return this.id;
    }
    public Boolean isEventDrivenGraph() {
        return this.isEventDrivenGraph;
    }
    public Map<String,String> labels() {
        return this.labels;
    }
    public String name() {
        return this.name;
    }
    public String namespace() {
        return this.namespace;
    }
    public String readme() {
        return this.readme;
    }
    public String routingUrl() {
        return this.routingUrl;
    }
    public String schema() {
        return this.schema;
    }
    public String subscriptionProtocol() {
        return this.subscriptionProtocol;
    }
    public String subscriptionUrl() {
        return this.subscriptionUrl;
    }
    public String websocketSubprotocol() {
        return this.websocketSubprotocol;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSubgraphResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String baseSubgraphName;
        private List<String> headers;
        private String id;
        private Boolean isEventDrivenGraph;
        private Map<String,String> labels;
        private String name;
        private String namespace;
        private String readme;
        private String routingUrl;
        private String schema;
        private String subscriptionProtocol;
        private String subscriptionUrl;
        private String websocketSubprotocol;
        public Builder() {}
        public Builder(GetSubgraphResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.baseSubgraphName = defaults.baseSubgraphName;
    	      this.headers = defaults.headers;
    	      this.id = defaults.id;
    	      this.isEventDrivenGraph = defaults.isEventDrivenGraph;
    	      this.labels = defaults.labels;
    	      this.name = defaults.name;
    	      this.namespace = defaults.namespace;
    	      this.readme = defaults.readme;
    	      this.routingUrl = defaults.routingUrl;
    	      this.schema = defaults.schema;
    	      this.subscriptionProtocol = defaults.subscriptionProtocol;
    	      this.subscriptionUrl = defaults.subscriptionUrl;
    	      this.websocketSubprotocol = defaults.websocketSubprotocol;
        }

        @CustomType.Setter
        public Builder baseSubgraphName(String baseSubgraphName) {
            if (baseSubgraphName == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "baseSubgraphName");
            }
            this.baseSubgraphName = baseSubgraphName;
            return this;
        }
        @CustomType.Setter
        public Builder headers(List<String> headers) {
            if (headers == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "headers");
            }
            this.headers = headers;
            return this;
        }
        public Builder headers(String... headers) {
            return headers(List.of(headers));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder isEventDrivenGraph(Boolean isEventDrivenGraph) {
            if (isEventDrivenGraph == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "isEventDrivenGraph");
            }
            this.isEventDrivenGraph = isEventDrivenGraph;
            return this;
        }
        @CustomType.Setter
        public Builder labels(Map<String,String> labels) {
            if (labels == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "labels");
            }
            this.labels = labels;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder namespace(String namespace) {
            if (namespace == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "namespace");
            }
            this.namespace = namespace;
            return this;
        }
        @CustomType.Setter
        public Builder readme(String readme) {
            if (readme == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "readme");
            }
            this.readme = readme;
            return this;
        }
        @CustomType.Setter
        public Builder routingUrl(String routingUrl) {
            if (routingUrl == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "routingUrl");
            }
            this.routingUrl = routingUrl;
            return this;
        }
        @CustomType.Setter
        public Builder schema(String schema) {
            if (schema == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "schema");
            }
            this.schema = schema;
            return this;
        }
        @CustomType.Setter
        public Builder subscriptionProtocol(String subscriptionProtocol) {
            if (subscriptionProtocol == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "subscriptionProtocol");
            }
            this.subscriptionProtocol = subscriptionProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder subscriptionUrl(String subscriptionUrl) {
            if (subscriptionUrl == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "subscriptionUrl");
            }
            this.subscriptionUrl = subscriptionUrl;
            return this;
        }
        @CustomType.Setter
        public Builder websocketSubprotocol(String websocketSubprotocol) {
            if (websocketSubprotocol == null) {
              throw new MissingRequiredPropertyException("GetSubgraphResult", "websocketSubprotocol");
            }
            this.websocketSubprotocol = websocketSubprotocol;
            return this;
        }
        public GetSubgraphResult build() {
            final var _resultValue = new GetSubgraphResult();
            _resultValue.baseSubgraphName = baseSubgraphName;
            _resultValue.headers = headers;
            _resultValue.id = id;
            _resultValue.isEventDrivenGraph = isEventDrivenGraph;
            _resultValue.labels = labels;
            _resultValue.name = name;
            _resultValue.namespace = namespace;
            _resultValue.readme = readme;
            _resultValue.routingUrl = routingUrl;
            _resultValue.schema = schema;
            _resultValue.subscriptionProtocol = subscriptionProtocol;
            _resultValue.subscriptionUrl = subscriptionUrl;
            _resultValue.websocketSubprotocol = websocketSubprotocol;
            return _resultValue;
        }
    }
}
