// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

type Contract struct {
	pulumi.CustomResourceState

	AdmissionWebhookSecret pulumi.StringPtrOutput   `pulumi:"admissionWebhookSecret"`
	AdmissionWebhookUrl    pulumi.StringPtrOutput   `pulumi:"admissionWebhookUrl"`
	ExcludeTags            pulumi.StringArrayOutput `pulumi:"excludeTags"`
	IncludeTags            pulumi.StringArrayOutput `pulumi:"includeTags"`
	Name                   pulumi.StringOutput      `pulumi:"name"`
	Namespace              pulumi.StringOutput      `pulumi:"namespace"`
	Readme                 pulumi.StringPtrOutput   `pulumi:"readme"`
	RoutingUrl             pulumi.StringOutput      `pulumi:"routingUrl"`
	Source                 pulumi.StringOutput      `pulumi:"source"`
	SupportsFederation     pulumi.BoolOutput        `pulumi:"supportsFederation"`
}

// NewContract registers a new resource with the given unique name, arguments, and options.
func NewContract(ctx *pulumi.Context,
	name string, args *ContractArgs, opts ...pulumi.ResourceOption) (*Contract, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Namespace == nil {
		return nil, errors.New("invalid value for required argument 'Namespace'")
	}
	if args.RoutingUrl == nil {
		return nil, errors.New("invalid value for required argument 'RoutingUrl'")
	}
	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Contract
	err := ctx.RegisterResource("cosmo:index/contract:Contract", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetContract gets an existing Contract resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetContract(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ContractState, opts ...pulumi.ResourceOption) (*Contract, error) {
	var resource Contract
	err := ctx.ReadResource("cosmo:index/contract:Contract", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Contract resources.
type contractState struct {
	AdmissionWebhookSecret *string  `pulumi:"admissionWebhookSecret"`
	AdmissionWebhookUrl    *string  `pulumi:"admissionWebhookUrl"`
	ExcludeTags            []string `pulumi:"excludeTags"`
	IncludeTags            []string `pulumi:"includeTags"`
	Name                   *string  `pulumi:"name"`
	Namespace              *string  `pulumi:"namespace"`
	Readme                 *string  `pulumi:"readme"`
	RoutingUrl             *string  `pulumi:"routingUrl"`
	Source                 *string  `pulumi:"source"`
	SupportsFederation     *bool    `pulumi:"supportsFederation"`
}

type ContractState struct {
	AdmissionWebhookSecret pulumi.StringPtrInput
	AdmissionWebhookUrl    pulumi.StringPtrInput
	ExcludeTags            pulumi.StringArrayInput
	IncludeTags            pulumi.StringArrayInput
	Name                   pulumi.StringPtrInput
	Namespace              pulumi.StringPtrInput
	Readme                 pulumi.StringPtrInput
	RoutingUrl             pulumi.StringPtrInput
	Source                 pulumi.StringPtrInput
	SupportsFederation     pulumi.BoolPtrInput
}

func (ContractState) ElementType() reflect.Type {
	return reflect.TypeOf((*contractState)(nil)).Elem()
}

type contractArgs struct {
	AdmissionWebhookSecret *string  `pulumi:"admissionWebhookSecret"`
	AdmissionWebhookUrl    *string  `pulumi:"admissionWebhookUrl"`
	ExcludeTags            []string `pulumi:"excludeTags"`
	IncludeTags            []string `pulumi:"includeTags"`
	Name                   *string  `pulumi:"name"`
	Namespace              string   `pulumi:"namespace"`
	Readme                 *string  `pulumi:"readme"`
	RoutingUrl             string   `pulumi:"routingUrl"`
	Source                 string   `pulumi:"source"`
	SupportsFederation     *bool    `pulumi:"supportsFederation"`
}

// The set of arguments for constructing a Contract resource.
type ContractArgs struct {
	AdmissionWebhookSecret pulumi.StringPtrInput
	AdmissionWebhookUrl    pulumi.StringPtrInput
	ExcludeTags            pulumi.StringArrayInput
	IncludeTags            pulumi.StringArrayInput
	Name                   pulumi.StringPtrInput
	Namespace              pulumi.StringInput
	Readme                 pulumi.StringPtrInput
	RoutingUrl             pulumi.StringInput
	Source                 pulumi.StringInput
	SupportsFederation     pulumi.BoolPtrInput
}

func (ContractArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*contractArgs)(nil)).Elem()
}

type ContractInput interface {
	pulumi.Input

	ToContractOutput() ContractOutput
	ToContractOutputWithContext(ctx context.Context) ContractOutput
}

func (*Contract) ElementType() reflect.Type {
	return reflect.TypeOf((**Contract)(nil)).Elem()
}

func (i *Contract) ToContractOutput() ContractOutput {
	return i.ToContractOutputWithContext(context.Background())
}

func (i *Contract) ToContractOutputWithContext(ctx context.Context) ContractOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContractOutput)
}

// ContractArrayInput is an input type that accepts ContractArray and ContractArrayOutput values.
// You can construct a concrete instance of `ContractArrayInput` via:
//
//	ContractArray{ ContractArgs{...} }
type ContractArrayInput interface {
	pulumi.Input

	ToContractArrayOutput() ContractArrayOutput
	ToContractArrayOutputWithContext(context.Context) ContractArrayOutput
}

type ContractArray []ContractInput

func (ContractArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Contract)(nil)).Elem()
}

func (i ContractArray) ToContractArrayOutput() ContractArrayOutput {
	return i.ToContractArrayOutputWithContext(context.Background())
}

func (i ContractArray) ToContractArrayOutputWithContext(ctx context.Context) ContractArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContractArrayOutput)
}

// ContractMapInput is an input type that accepts ContractMap and ContractMapOutput values.
// You can construct a concrete instance of `ContractMapInput` via:
//
//	ContractMap{ "key": ContractArgs{...} }
type ContractMapInput interface {
	pulumi.Input

	ToContractMapOutput() ContractMapOutput
	ToContractMapOutputWithContext(context.Context) ContractMapOutput
}

type ContractMap map[string]ContractInput

func (ContractMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Contract)(nil)).Elem()
}

func (i ContractMap) ToContractMapOutput() ContractMapOutput {
	return i.ToContractMapOutputWithContext(context.Background())
}

func (i ContractMap) ToContractMapOutputWithContext(ctx context.Context) ContractMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContractMapOutput)
}

type ContractOutput struct{ *pulumi.OutputState }

func (ContractOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Contract)(nil)).Elem()
}

func (o ContractOutput) ToContractOutput() ContractOutput {
	return o
}

func (o ContractOutput) ToContractOutputWithContext(ctx context.Context) ContractOutput {
	return o
}

func (o ContractOutput) AdmissionWebhookSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringPtrOutput { return v.AdmissionWebhookSecret }).(pulumi.StringPtrOutput)
}

func (o ContractOutput) AdmissionWebhookUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringPtrOutput { return v.AdmissionWebhookUrl }).(pulumi.StringPtrOutput)
}

func (o ContractOutput) ExcludeTags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringArrayOutput { return v.ExcludeTags }).(pulumi.StringArrayOutput)
}

func (o ContractOutput) IncludeTags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringArrayOutput { return v.IncludeTags }).(pulumi.StringArrayOutput)
}

func (o ContractOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ContractOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringOutput { return v.Namespace }).(pulumi.StringOutput)
}

func (o ContractOutput) Readme() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringPtrOutput { return v.Readme }).(pulumi.StringPtrOutput)
}

func (o ContractOutput) RoutingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringOutput { return v.RoutingUrl }).(pulumi.StringOutput)
}

func (o ContractOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Contract) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

func (o ContractOutput) SupportsFederation() pulumi.BoolOutput {
	return o.ApplyT(func(v *Contract) pulumi.BoolOutput { return v.SupportsFederation }).(pulumi.BoolOutput)
}

type ContractArrayOutput struct{ *pulumi.OutputState }

func (ContractArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Contract)(nil)).Elem()
}

func (o ContractArrayOutput) ToContractArrayOutput() ContractArrayOutput {
	return o
}

func (o ContractArrayOutput) ToContractArrayOutputWithContext(ctx context.Context) ContractArrayOutput {
	return o
}

func (o ContractArrayOutput) Index(i pulumi.IntInput) ContractOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Contract {
		return vs[0].([]*Contract)[vs[1].(int)]
	}).(ContractOutput)
}

type ContractMapOutput struct{ *pulumi.OutputState }

func (ContractMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Contract)(nil)).Elem()
}

func (o ContractMapOutput) ToContractMapOutput() ContractMapOutput {
	return o
}

func (o ContractMapOutput) ToContractMapOutputWithContext(ctx context.Context) ContractMapOutput {
	return o
}

func (o ContractMapOutput) MapIndex(k pulumi.StringInput) ContractOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Contract {
		return vs[0].(map[string]*Contract)[vs[1].(string)]
	}).(ContractOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ContractInput)(nil)).Elem(), &Contract{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContractArrayInput)(nil)).Elem(), ContractArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContractMapInput)(nil)).Elem(), ContractMap{})
	pulumi.RegisterOutputType(ContractOutput{})
	pulumi.RegisterOutputType(ContractArrayOutput{})
	pulumi.RegisterOutputType(ContractMapOutput{})
}
