// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

type FeatureFlag struct {
	pulumi.CustomResourceState

	// The timestamp when the feature flag was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The user who created the feature flag.
	CreatedBy pulumi.StringOutput `pulumi:"createdBy"`
	// The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	FeatureSubgraphs pulumi.StringArrayOutput `pulumi:"featureSubgraphs"`
	// Indicates whether the feature flag is enabled.
	IsEnabled pulumi.BoolPtrOutput `pulumi:"isEnabled"`
	// The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// The name of the feature flag.
	Name pulumi.StringOutput `pulumi:"name"`
	// The namespace of the feature flag.
	Namespace pulumi.StringOutput `pulumi:"namespace"`
	// The timestamp when the feature flag was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewFeatureFlag registers a new resource with the given unique name, arguments, and options.
func NewFeatureFlag(ctx *pulumi.Context,
	name string, args *FeatureFlagArgs, opts ...pulumi.ResourceOption) (*FeatureFlag, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.FeatureSubgraphs == nil {
		return nil, errors.New("invalid value for required argument 'FeatureSubgraphs'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FeatureFlag
	err := ctx.RegisterResource("cosmo:index/featureFlag:FeatureFlag", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFeatureFlag gets an existing FeatureFlag resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFeatureFlag(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FeatureFlagState, opts ...pulumi.ResourceOption) (*FeatureFlag, error) {
	var resource FeatureFlag
	err := ctx.ReadResource("cosmo:index/featureFlag:FeatureFlag", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FeatureFlag resources.
type featureFlagState struct {
	// The timestamp when the feature flag was created.
	CreatedAt *string `pulumi:"createdAt"`
	// The user who created the feature flag.
	CreatedBy *string `pulumi:"createdBy"`
	// The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	FeatureSubgraphs []string `pulumi:"featureSubgraphs"`
	// Indicates whether the feature flag is enabled.
	IsEnabled *bool `pulumi:"isEnabled"`
	// The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	Labels map[string]string `pulumi:"labels"`
	// The name of the feature flag.
	Name *string `pulumi:"name"`
	// The namespace of the feature flag.
	Namespace *string `pulumi:"namespace"`
	// The timestamp when the feature flag was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type FeatureFlagState struct {
	// The timestamp when the feature flag was created.
	CreatedAt pulumi.StringPtrInput
	// The user who created the feature flag.
	CreatedBy pulumi.StringPtrInput
	// The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	FeatureSubgraphs pulumi.StringArrayInput
	// Indicates whether the feature flag is enabled.
	IsEnabled pulumi.BoolPtrInput
	// The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	Labels pulumi.StringMapInput
	// The name of the feature flag.
	Name pulumi.StringPtrInput
	// The namespace of the feature flag.
	Namespace pulumi.StringPtrInput
	// The timestamp when the feature flag was last updated.
	UpdatedAt pulumi.StringPtrInput
}

func (FeatureFlagState) ElementType() reflect.Type {
	return reflect.TypeOf((*featureFlagState)(nil)).Elem()
}

type featureFlagArgs struct {
	// The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	FeatureSubgraphs []string `pulumi:"featureSubgraphs"`
	// Indicates whether the feature flag is enabled.
	IsEnabled *bool `pulumi:"isEnabled"`
	// The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	Labels map[string]string `pulumi:"labels"`
	// The name of the feature flag.
	Name *string `pulumi:"name"`
	// The namespace of the feature flag.
	Namespace *string `pulumi:"namespace"`
}

// The set of arguments for constructing a FeatureFlag resource.
type FeatureFlagArgs struct {
	// The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	FeatureSubgraphs pulumi.StringArrayInput
	// Indicates whether the feature flag is enabled.
	IsEnabled pulumi.BoolPtrInput
	// The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	Labels pulumi.StringMapInput
	// The name of the feature flag.
	Name pulumi.StringPtrInput
	// The namespace of the feature flag.
	Namespace pulumi.StringPtrInput
}

func (FeatureFlagArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*featureFlagArgs)(nil)).Elem()
}

type FeatureFlagInput interface {
	pulumi.Input

	ToFeatureFlagOutput() FeatureFlagOutput
	ToFeatureFlagOutputWithContext(ctx context.Context) FeatureFlagOutput
}

func (*FeatureFlag) ElementType() reflect.Type {
	return reflect.TypeOf((**FeatureFlag)(nil)).Elem()
}

func (i *FeatureFlag) ToFeatureFlagOutput() FeatureFlagOutput {
	return i.ToFeatureFlagOutputWithContext(context.Background())
}

func (i *FeatureFlag) ToFeatureFlagOutputWithContext(ctx context.Context) FeatureFlagOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FeatureFlagOutput)
}

// FeatureFlagArrayInput is an input type that accepts FeatureFlagArray and FeatureFlagArrayOutput values.
// You can construct a concrete instance of `FeatureFlagArrayInput` via:
//
//	FeatureFlagArray{ FeatureFlagArgs{...} }
type FeatureFlagArrayInput interface {
	pulumi.Input

	ToFeatureFlagArrayOutput() FeatureFlagArrayOutput
	ToFeatureFlagArrayOutputWithContext(context.Context) FeatureFlagArrayOutput
}

type FeatureFlagArray []FeatureFlagInput

func (FeatureFlagArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FeatureFlag)(nil)).Elem()
}

func (i FeatureFlagArray) ToFeatureFlagArrayOutput() FeatureFlagArrayOutput {
	return i.ToFeatureFlagArrayOutputWithContext(context.Background())
}

func (i FeatureFlagArray) ToFeatureFlagArrayOutputWithContext(ctx context.Context) FeatureFlagArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FeatureFlagArrayOutput)
}

// FeatureFlagMapInput is an input type that accepts FeatureFlagMap and FeatureFlagMapOutput values.
// You can construct a concrete instance of `FeatureFlagMapInput` via:
//
//	FeatureFlagMap{ "key": FeatureFlagArgs{...} }
type FeatureFlagMapInput interface {
	pulumi.Input

	ToFeatureFlagMapOutput() FeatureFlagMapOutput
	ToFeatureFlagMapOutputWithContext(context.Context) FeatureFlagMapOutput
}

type FeatureFlagMap map[string]FeatureFlagInput

func (FeatureFlagMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FeatureFlag)(nil)).Elem()
}

func (i FeatureFlagMap) ToFeatureFlagMapOutput() FeatureFlagMapOutput {
	return i.ToFeatureFlagMapOutputWithContext(context.Background())
}

func (i FeatureFlagMap) ToFeatureFlagMapOutputWithContext(ctx context.Context) FeatureFlagMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FeatureFlagMapOutput)
}

type FeatureFlagOutput struct{ *pulumi.OutputState }

func (FeatureFlagOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FeatureFlag)(nil)).Elem()
}

func (o FeatureFlagOutput) ToFeatureFlagOutput() FeatureFlagOutput {
	return o
}

func (o FeatureFlagOutput) ToFeatureFlagOutputWithContext(ctx context.Context) FeatureFlagOutput {
	return o
}

// The timestamp when the feature flag was created.
func (o FeatureFlagOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureFlag) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The user who created the feature flag.
func (o FeatureFlagOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureFlag) pulumi.StringOutput { return v.CreatedBy }).(pulumi.StringOutput)
}

// The list of feature subgraphs associated with the feature flag.
// At least one feature subgraph must be provided.
func (o FeatureFlagOutput) FeatureSubgraphs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *FeatureFlag) pulumi.StringArrayOutput { return v.FeatureSubgraphs }).(pulumi.StringArrayOutput)
}

// Indicates whether the feature flag is enabled.
func (o FeatureFlagOutput) IsEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *FeatureFlag) pulumi.BoolPtrOutput { return v.IsEnabled }).(pulumi.BoolPtrOutput)
}

// The labels associated with the feature flag. These labels indicate which
// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
func (o FeatureFlagOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *FeatureFlag) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// The name of the feature flag.
func (o FeatureFlagOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureFlag) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The namespace of the feature flag.
func (o FeatureFlagOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureFlag) pulumi.StringOutput { return v.Namespace }).(pulumi.StringOutput)
}

// The timestamp when the feature flag was last updated.
func (o FeatureFlagOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureFlag) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type FeatureFlagArrayOutput struct{ *pulumi.OutputState }

func (FeatureFlagArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FeatureFlag)(nil)).Elem()
}

func (o FeatureFlagArrayOutput) ToFeatureFlagArrayOutput() FeatureFlagArrayOutput {
	return o
}

func (o FeatureFlagArrayOutput) ToFeatureFlagArrayOutputWithContext(ctx context.Context) FeatureFlagArrayOutput {
	return o
}

func (o FeatureFlagArrayOutput) Index(i pulumi.IntInput) FeatureFlagOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FeatureFlag {
		return vs[0].([]*FeatureFlag)[vs[1].(int)]
	}).(FeatureFlagOutput)
}

type FeatureFlagMapOutput struct{ *pulumi.OutputState }

func (FeatureFlagMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FeatureFlag)(nil)).Elem()
}

func (o FeatureFlagMapOutput) ToFeatureFlagMapOutput() FeatureFlagMapOutput {
	return o
}

func (o FeatureFlagMapOutput) ToFeatureFlagMapOutputWithContext(ctx context.Context) FeatureFlagMapOutput {
	return o
}

func (o FeatureFlagMapOutput) MapIndex(k pulumi.StringInput) FeatureFlagOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FeatureFlag {
		return vs[0].(map[string]*FeatureFlag)[vs[1].(string)]
	}).(FeatureFlagOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FeatureFlagInput)(nil)).Elem(), &FeatureFlag{})
	pulumi.RegisterInputType(reflect.TypeOf((*FeatureFlagArrayInput)(nil)).Elem(), FeatureFlagArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FeatureFlagMapInput)(nil)).Elem(), FeatureFlagMap{})
	pulumi.RegisterOutputType(FeatureFlagOutput{})
	pulumi.RegisterOutputType(FeatureFlagArrayOutput{})
	pulumi.RegisterOutputType(FeatureFlagMapOutput{})
}
