// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

type FeatureSubgraph struct {
	pulumi.CustomResourceState

	// The name of the base subgraph that this feature subgraph extends.
	BaseSubgraphName pulumi.StringOutput `pulumi:"baseSubgraphName"`
	// The name of the feature subgraph.
	Name pulumi.StringOutput `pulumi:"name"`
	// The namespace to create the feature subgraph in.
	Namespace pulumi.StringOutput `pulumi:"namespace"`
	// The readme for the subgraph.
	Readme pulumi.StringPtrOutput `pulumi:"readme"`
	// The routing URL of the feature subgraph.
	RoutingUrl pulumi.StringOutput `pulumi:"routingUrl"`
	// The schema for the subgraph.
	Schema pulumi.StringPtrOutput `pulumi:"schema"`
	// The subscription protocol for the subgraph.
	SubscriptionProtocol pulumi.StringOutput `pulumi:"subscriptionProtocol"`
	// The subscription URL for the subgraph.
	SubscriptionUrl pulumi.StringPtrOutput `pulumi:"subscriptionUrl"`
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol pulumi.StringOutput `pulumi:"websocketSubprotocol"`
}

// NewFeatureSubgraph registers a new resource with the given unique name, arguments, and options.
func NewFeatureSubgraph(ctx *pulumi.Context,
	name string, args *FeatureSubgraphArgs, opts ...pulumi.ResourceOption) (*FeatureSubgraph, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BaseSubgraphName == nil {
		return nil, errors.New("invalid value for required argument 'BaseSubgraphName'")
	}
	if args.RoutingUrl == nil {
		return nil, errors.New("invalid value for required argument 'RoutingUrl'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FeatureSubgraph
	err := ctx.RegisterResource("cosmo:index/featureSubgraph:FeatureSubgraph", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFeatureSubgraph gets an existing FeatureSubgraph resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFeatureSubgraph(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FeatureSubgraphState, opts ...pulumi.ResourceOption) (*FeatureSubgraph, error) {
	var resource FeatureSubgraph
	err := ctx.ReadResource("cosmo:index/featureSubgraph:FeatureSubgraph", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FeatureSubgraph resources.
type featureSubgraphState struct {
	// The name of the base subgraph that this feature subgraph extends.
	BaseSubgraphName *string `pulumi:"baseSubgraphName"`
	// The name of the feature subgraph.
	Name *string `pulumi:"name"`
	// The namespace to create the feature subgraph in.
	Namespace *string `pulumi:"namespace"`
	// The readme for the subgraph.
	Readme *string `pulumi:"readme"`
	// The routing URL of the feature subgraph.
	RoutingUrl *string `pulumi:"routingUrl"`
	// The schema for the subgraph.
	Schema *string `pulumi:"schema"`
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `pulumi:"subscriptionProtocol"`
	// The subscription URL for the subgraph.
	SubscriptionUrl *string `pulumi:"subscriptionUrl"`
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `pulumi:"websocketSubprotocol"`
}

type FeatureSubgraphState struct {
	// The name of the base subgraph that this feature subgraph extends.
	BaseSubgraphName pulumi.StringPtrInput
	// The name of the feature subgraph.
	Name pulumi.StringPtrInput
	// The namespace to create the feature subgraph in.
	Namespace pulumi.StringPtrInput
	// The readme for the subgraph.
	Readme pulumi.StringPtrInput
	// The routing URL of the feature subgraph.
	RoutingUrl pulumi.StringPtrInput
	// The schema for the subgraph.
	Schema pulumi.StringPtrInput
	// The subscription protocol for the subgraph.
	SubscriptionProtocol pulumi.StringPtrInput
	// The subscription URL for the subgraph.
	SubscriptionUrl pulumi.StringPtrInput
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol pulumi.StringPtrInput
}

func (FeatureSubgraphState) ElementType() reflect.Type {
	return reflect.TypeOf((*featureSubgraphState)(nil)).Elem()
}

type featureSubgraphArgs struct {
	// The name of the base subgraph that this feature subgraph extends.
	BaseSubgraphName string `pulumi:"baseSubgraphName"`
	// The name of the feature subgraph.
	Name *string `pulumi:"name"`
	// The namespace to create the feature subgraph in.
	Namespace *string `pulumi:"namespace"`
	// The readme for the subgraph.
	Readme *string `pulumi:"readme"`
	// The routing URL of the feature subgraph.
	RoutingUrl string `pulumi:"routingUrl"`
	// The schema for the subgraph.
	Schema *string `pulumi:"schema"`
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `pulumi:"subscriptionProtocol"`
	// The subscription URL for the subgraph.
	SubscriptionUrl *string `pulumi:"subscriptionUrl"`
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `pulumi:"websocketSubprotocol"`
}

// The set of arguments for constructing a FeatureSubgraph resource.
type FeatureSubgraphArgs struct {
	// The name of the base subgraph that this feature subgraph extends.
	BaseSubgraphName pulumi.StringInput
	// The name of the feature subgraph.
	Name pulumi.StringPtrInput
	// The namespace to create the feature subgraph in.
	Namespace pulumi.StringPtrInput
	// The readme for the subgraph.
	Readme pulumi.StringPtrInput
	// The routing URL of the feature subgraph.
	RoutingUrl pulumi.StringInput
	// The schema for the subgraph.
	Schema pulumi.StringPtrInput
	// The subscription protocol for the subgraph.
	SubscriptionProtocol pulumi.StringPtrInput
	// The subscription URL for the subgraph.
	SubscriptionUrl pulumi.StringPtrInput
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol pulumi.StringPtrInput
}

func (FeatureSubgraphArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*featureSubgraphArgs)(nil)).Elem()
}

type FeatureSubgraphInput interface {
	pulumi.Input

	ToFeatureSubgraphOutput() FeatureSubgraphOutput
	ToFeatureSubgraphOutputWithContext(ctx context.Context) FeatureSubgraphOutput
}

func (*FeatureSubgraph) ElementType() reflect.Type {
	return reflect.TypeOf((**FeatureSubgraph)(nil)).Elem()
}

func (i *FeatureSubgraph) ToFeatureSubgraphOutput() FeatureSubgraphOutput {
	return i.ToFeatureSubgraphOutputWithContext(context.Background())
}

func (i *FeatureSubgraph) ToFeatureSubgraphOutputWithContext(ctx context.Context) FeatureSubgraphOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FeatureSubgraphOutput)
}

// FeatureSubgraphArrayInput is an input type that accepts FeatureSubgraphArray and FeatureSubgraphArrayOutput values.
// You can construct a concrete instance of `FeatureSubgraphArrayInput` via:
//
//	FeatureSubgraphArray{ FeatureSubgraphArgs{...} }
type FeatureSubgraphArrayInput interface {
	pulumi.Input

	ToFeatureSubgraphArrayOutput() FeatureSubgraphArrayOutput
	ToFeatureSubgraphArrayOutputWithContext(context.Context) FeatureSubgraphArrayOutput
}

type FeatureSubgraphArray []FeatureSubgraphInput

func (FeatureSubgraphArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FeatureSubgraph)(nil)).Elem()
}

func (i FeatureSubgraphArray) ToFeatureSubgraphArrayOutput() FeatureSubgraphArrayOutput {
	return i.ToFeatureSubgraphArrayOutputWithContext(context.Background())
}

func (i FeatureSubgraphArray) ToFeatureSubgraphArrayOutputWithContext(ctx context.Context) FeatureSubgraphArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FeatureSubgraphArrayOutput)
}

// FeatureSubgraphMapInput is an input type that accepts FeatureSubgraphMap and FeatureSubgraphMapOutput values.
// You can construct a concrete instance of `FeatureSubgraphMapInput` via:
//
//	FeatureSubgraphMap{ "key": FeatureSubgraphArgs{...} }
type FeatureSubgraphMapInput interface {
	pulumi.Input

	ToFeatureSubgraphMapOutput() FeatureSubgraphMapOutput
	ToFeatureSubgraphMapOutputWithContext(context.Context) FeatureSubgraphMapOutput
}

type FeatureSubgraphMap map[string]FeatureSubgraphInput

func (FeatureSubgraphMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FeatureSubgraph)(nil)).Elem()
}

func (i FeatureSubgraphMap) ToFeatureSubgraphMapOutput() FeatureSubgraphMapOutput {
	return i.ToFeatureSubgraphMapOutputWithContext(context.Background())
}

func (i FeatureSubgraphMap) ToFeatureSubgraphMapOutputWithContext(ctx context.Context) FeatureSubgraphMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FeatureSubgraphMapOutput)
}

type FeatureSubgraphOutput struct{ *pulumi.OutputState }

func (FeatureSubgraphOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FeatureSubgraph)(nil)).Elem()
}

func (o FeatureSubgraphOutput) ToFeatureSubgraphOutput() FeatureSubgraphOutput {
	return o
}

func (o FeatureSubgraphOutput) ToFeatureSubgraphOutputWithContext(ctx context.Context) FeatureSubgraphOutput {
	return o
}

// The name of the base subgraph that this feature subgraph extends.
func (o FeatureSubgraphOutput) BaseSubgraphName() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringOutput { return v.BaseSubgraphName }).(pulumi.StringOutput)
}

// The name of the feature subgraph.
func (o FeatureSubgraphOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The namespace to create the feature subgraph in.
func (o FeatureSubgraphOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringOutput { return v.Namespace }).(pulumi.StringOutput)
}

// The readme for the subgraph.
func (o FeatureSubgraphOutput) Readme() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringPtrOutput { return v.Readme }).(pulumi.StringPtrOutput)
}

// The routing URL of the feature subgraph.
func (o FeatureSubgraphOutput) RoutingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringOutput { return v.RoutingUrl }).(pulumi.StringOutput)
}

// The schema for the subgraph.
func (o FeatureSubgraphOutput) Schema() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringPtrOutput { return v.Schema }).(pulumi.StringPtrOutput)
}

// The subscription protocol for the subgraph.
func (o FeatureSubgraphOutput) SubscriptionProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringOutput { return v.SubscriptionProtocol }).(pulumi.StringOutput)
}

// The subscription URL for the subgraph.
func (o FeatureSubgraphOutput) SubscriptionUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringPtrOutput { return v.SubscriptionUrl }).(pulumi.StringPtrOutput)
}

// The websocket subprotocol for the subgraph.
func (o FeatureSubgraphOutput) WebsocketSubprotocol() pulumi.StringOutput {
	return o.ApplyT(func(v *FeatureSubgraph) pulumi.StringOutput { return v.WebsocketSubprotocol }).(pulumi.StringOutput)
}

type FeatureSubgraphArrayOutput struct{ *pulumi.OutputState }

func (FeatureSubgraphArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FeatureSubgraph)(nil)).Elem()
}

func (o FeatureSubgraphArrayOutput) ToFeatureSubgraphArrayOutput() FeatureSubgraphArrayOutput {
	return o
}

func (o FeatureSubgraphArrayOutput) ToFeatureSubgraphArrayOutputWithContext(ctx context.Context) FeatureSubgraphArrayOutput {
	return o
}

func (o FeatureSubgraphArrayOutput) Index(i pulumi.IntInput) FeatureSubgraphOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FeatureSubgraph {
		return vs[0].([]*FeatureSubgraph)[vs[1].(int)]
	}).(FeatureSubgraphOutput)
}

type FeatureSubgraphMapOutput struct{ *pulumi.OutputState }

func (FeatureSubgraphMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FeatureSubgraph)(nil)).Elem()
}

func (o FeatureSubgraphMapOutput) ToFeatureSubgraphMapOutput() FeatureSubgraphMapOutput {
	return o
}

func (o FeatureSubgraphMapOutput) ToFeatureSubgraphMapOutputWithContext(ctx context.Context) FeatureSubgraphMapOutput {
	return o
}

func (o FeatureSubgraphMapOutput) MapIndex(k pulumi.StringInput) FeatureSubgraphOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FeatureSubgraph {
		return vs[0].(map[string]*FeatureSubgraph)[vs[1].(string)]
	}).(FeatureSubgraphOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FeatureSubgraphInput)(nil)).Elem(), &FeatureSubgraph{})
	pulumi.RegisterInputType(reflect.TypeOf((*FeatureSubgraphArrayInput)(nil)).Elem(), FeatureSubgraphArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FeatureSubgraphMapInput)(nil)).Elem(), FeatureSubgraphMap{})
	pulumi.RegisterOutputType(FeatureSubgraphOutput{})
	pulumi.RegisterOutputType(FeatureSubgraphArrayOutput{})
	pulumi.RegisterOutputType(FeatureSubgraphMapOutput{})
}
