// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

func LookupContract(ctx *pulumi.Context, args *LookupContractArgs, opts ...pulumi.InvokeOption) (*LookupContractResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupContractResult
	err := ctx.Invoke("cosmo:index/getContract:getContract", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getContract.
type LookupContractArgs struct {
	Name      string `pulumi:"name"`
	Namespace string `pulumi:"namespace"`
}

// A collection of values returned by getContract.
type LookupContractResult struct {
	AdmissionWebhookSecret string            `pulumi:"admissionWebhookSecret"`
	AdmissionWebhookUrl    string            `pulumi:"admissionWebhookUrl"`
	ExcludeTags            []string          `pulumi:"excludeTags"`
	Id                     string            `pulumi:"id"`
	IncludeTags            []string          `pulumi:"includeTags"`
	LabelMatchers          map[string]string `pulumi:"labelMatchers"`
	Name                   string            `pulumi:"name"`
	Namespace              string            `pulumi:"namespace"`
	Readme                 string            `pulumi:"readme"`
	RoutingUrl             string            `pulumi:"routingUrl"`
	SupportsFederation     bool              `pulumi:"supportsFederation"`
}

func LookupContractOutput(ctx *pulumi.Context, args LookupContractOutputArgs, opts ...pulumi.InvokeOption) LookupContractResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupContractResultOutput, error) {
			args := v.(LookupContractArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cosmo:index/getContract:getContract", args, LookupContractResultOutput{}, options).(LookupContractResultOutput), nil
		}).(LookupContractResultOutput)
}

// A collection of arguments for invoking getContract.
type LookupContractOutputArgs struct {
	Name      pulumi.StringInput `pulumi:"name"`
	Namespace pulumi.StringInput `pulumi:"namespace"`
}

func (LookupContractOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContractArgs)(nil)).Elem()
}

// A collection of values returned by getContract.
type LookupContractResultOutput struct{ *pulumi.OutputState }

func (LookupContractResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContractResult)(nil)).Elem()
}

func (o LookupContractResultOutput) ToLookupContractResultOutput() LookupContractResultOutput {
	return o
}

func (o LookupContractResultOutput) ToLookupContractResultOutputWithContext(ctx context.Context) LookupContractResultOutput {
	return o
}

func (o LookupContractResultOutput) AdmissionWebhookSecret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContractResult) string { return v.AdmissionWebhookSecret }).(pulumi.StringOutput)
}

func (o LookupContractResultOutput) AdmissionWebhookUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContractResult) string { return v.AdmissionWebhookUrl }).(pulumi.StringOutput)
}

func (o LookupContractResultOutput) ExcludeTags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupContractResult) []string { return v.ExcludeTags }).(pulumi.StringArrayOutput)
}

func (o LookupContractResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContractResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupContractResultOutput) IncludeTags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupContractResult) []string { return v.IncludeTags }).(pulumi.StringArrayOutput)
}

func (o LookupContractResultOutput) LabelMatchers() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupContractResult) map[string]string { return v.LabelMatchers }).(pulumi.StringMapOutput)
}

func (o LookupContractResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContractResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupContractResultOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContractResult) string { return v.Namespace }).(pulumi.StringOutput)
}

func (o LookupContractResultOutput) Readme() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContractResult) string { return v.Readme }).(pulumi.StringOutput)
}

func (o LookupContractResultOutput) RoutingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContractResult) string { return v.RoutingUrl }).(pulumi.StringOutput)
}

func (o LookupContractResultOutput) SupportsFederation() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupContractResult) bool { return v.SupportsFederation }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupContractResultOutput{})
}
