// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

func LookupFederatedGraph(ctx *pulumi.Context, args *LookupFederatedGraphArgs, opts ...pulumi.InvokeOption) (*LookupFederatedGraphResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFederatedGraphResult
	err := ctx.Invoke("cosmo:index/getFederatedGraph:getFederatedGraph", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFederatedGraph.
type LookupFederatedGraphArgs struct {
	Name      string `pulumi:"name"`
	Namespace string `pulumi:"namespace"`
}

// A collection of values returned by getFederatedGraph.
type LookupFederatedGraphResult struct {
	AdmissionWebhookSecret string            `pulumi:"admissionWebhookSecret"`
	AdmissionWebhookUrl    string            `pulumi:"admissionWebhookUrl"`
	Id                     string            `pulumi:"id"`
	LabelMatchers          map[string]string `pulumi:"labelMatchers"`
	Name                   string            `pulumi:"name"`
	Namespace              string            `pulumi:"namespace"`
	Readme                 string            `pulumi:"readme"`
	RoutingUrl             string            `pulumi:"routingUrl"`
}

func LookupFederatedGraphOutput(ctx *pulumi.Context, args LookupFederatedGraphOutputArgs, opts ...pulumi.InvokeOption) LookupFederatedGraphResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupFederatedGraphResultOutput, error) {
			args := v.(LookupFederatedGraphArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cosmo:index/getFederatedGraph:getFederatedGraph", args, LookupFederatedGraphResultOutput{}, options).(LookupFederatedGraphResultOutput), nil
		}).(LookupFederatedGraphResultOutput)
}

// A collection of arguments for invoking getFederatedGraph.
type LookupFederatedGraphOutputArgs struct {
	Name      pulumi.StringInput `pulumi:"name"`
	Namespace pulumi.StringInput `pulumi:"namespace"`
}

func (LookupFederatedGraphOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFederatedGraphArgs)(nil)).Elem()
}

// A collection of values returned by getFederatedGraph.
type LookupFederatedGraphResultOutput struct{ *pulumi.OutputState }

func (LookupFederatedGraphResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFederatedGraphResult)(nil)).Elem()
}

func (o LookupFederatedGraphResultOutput) ToLookupFederatedGraphResultOutput() LookupFederatedGraphResultOutput {
	return o
}

func (o LookupFederatedGraphResultOutput) ToLookupFederatedGraphResultOutputWithContext(ctx context.Context) LookupFederatedGraphResultOutput {
	return o
}

func (o LookupFederatedGraphResultOutput) AdmissionWebhookSecret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFederatedGraphResult) string { return v.AdmissionWebhookSecret }).(pulumi.StringOutput)
}

func (o LookupFederatedGraphResultOutput) AdmissionWebhookUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFederatedGraphResult) string { return v.AdmissionWebhookUrl }).(pulumi.StringOutput)
}

func (o LookupFederatedGraphResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFederatedGraphResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFederatedGraphResultOutput) LabelMatchers() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupFederatedGraphResult) map[string]string { return v.LabelMatchers }).(pulumi.StringMapOutput)
}

func (o LookupFederatedGraphResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFederatedGraphResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupFederatedGraphResultOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFederatedGraphResult) string { return v.Namespace }).(pulumi.StringOutput)
}

func (o LookupFederatedGraphResultOutput) Readme() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFederatedGraphResult) string { return v.Readme }).(pulumi.StringOutput)
}

func (o LookupFederatedGraphResultOutput) RoutingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFederatedGraphResult) string { return v.RoutingUrl }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFederatedGraphResultOutput{})
}
