// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

func LookupFeatureFlag(ctx *pulumi.Context, args *LookupFeatureFlagArgs, opts ...pulumi.InvokeOption) (*LookupFeatureFlagResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFeatureFlagResult
	err := ctx.Invoke("cosmo:index/getFeatureFlag:getFeatureFlag", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFeatureFlag.
type LookupFeatureFlagArgs struct {
	Name      string  `pulumi:"name"`
	Namespace *string `pulumi:"namespace"`
}

// A collection of values returned by getFeatureFlag.
type LookupFeatureFlagResult struct {
	CreatedAt        string            `pulumi:"createdAt"`
	CreatedBy        string            `pulumi:"createdBy"`
	FeatureSubgraphs []string          `pulumi:"featureSubgraphs"`
	Id               string            `pulumi:"id"`
	IsEnabled        bool              `pulumi:"isEnabled"`
	Labels           map[string]string `pulumi:"labels"`
	Name             string            `pulumi:"name"`
	Namespace        *string           `pulumi:"namespace"`
	UpdatedAt        string            `pulumi:"updatedAt"`
}

func LookupFeatureFlagOutput(ctx *pulumi.Context, args LookupFeatureFlagOutputArgs, opts ...pulumi.InvokeOption) LookupFeatureFlagResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupFeatureFlagResultOutput, error) {
			args := v.(LookupFeatureFlagArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cosmo:index/getFeatureFlag:getFeatureFlag", args, LookupFeatureFlagResultOutput{}, options).(LookupFeatureFlagResultOutput), nil
		}).(LookupFeatureFlagResultOutput)
}

// A collection of arguments for invoking getFeatureFlag.
type LookupFeatureFlagOutputArgs struct {
	Name      pulumi.StringInput    `pulumi:"name"`
	Namespace pulumi.StringPtrInput `pulumi:"namespace"`
}

func (LookupFeatureFlagOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFeatureFlagArgs)(nil)).Elem()
}

// A collection of values returned by getFeatureFlag.
type LookupFeatureFlagResultOutput struct{ *pulumi.OutputState }

func (LookupFeatureFlagResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFeatureFlagResult)(nil)).Elem()
}

func (o LookupFeatureFlagResultOutput) ToLookupFeatureFlagResultOutput() LookupFeatureFlagResultOutput {
	return o
}

func (o LookupFeatureFlagResultOutput) ToLookupFeatureFlagResultOutputWithContext(ctx context.Context) LookupFeatureFlagResultOutput {
	return o
}

func (o LookupFeatureFlagResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupFeatureFlagResultOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) string { return v.CreatedBy }).(pulumi.StringOutput)
}

func (o LookupFeatureFlagResultOutput) FeatureSubgraphs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) []string { return v.FeatureSubgraphs }).(pulumi.StringArrayOutput)
}

func (o LookupFeatureFlagResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFeatureFlagResultOutput) IsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) bool { return v.IsEnabled }).(pulumi.BoolOutput)
}

func (o LookupFeatureFlagResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupFeatureFlagResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupFeatureFlagResultOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

func (o LookupFeatureFlagResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureFlagResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFeatureFlagResultOutput{})
}
