// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

func LookupFeatureSubgraph(ctx *pulumi.Context, args *LookupFeatureSubgraphArgs, opts ...pulumi.InvokeOption) (*LookupFeatureSubgraphResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFeatureSubgraphResult
	err := ctx.Invoke("cosmo:index/getFeatureSubgraph:getFeatureSubgraph", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFeatureSubgraph.
type LookupFeatureSubgraphArgs struct {
	Name      string  `pulumi:"name"`
	Namespace *string `pulumi:"namespace"`
}

// A collection of values returned by getFeatureSubgraph.
type LookupFeatureSubgraphResult struct {
	BaseSubgraphName     string  `pulumi:"baseSubgraphName"`
	Id                   string  `pulumi:"id"`
	Name                 string  `pulumi:"name"`
	Namespace            *string `pulumi:"namespace"`
	Readme               string  `pulumi:"readme"`
	RoutingUrl           string  `pulumi:"routingUrl"`
	Schema               string  `pulumi:"schema"`
	SubscriptionProtocol string  `pulumi:"subscriptionProtocol"`
	SubscriptionUrl      string  `pulumi:"subscriptionUrl"`
	WebsocketSubprotocol string  `pulumi:"websocketSubprotocol"`
}

func LookupFeatureSubgraphOutput(ctx *pulumi.Context, args LookupFeatureSubgraphOutputArgs, opts ...pulumi.InvokeOption) LookupFeatureSubgraphResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupFeatureSubgraphResultOutput, error) {
			args := v.(LookupFeatureSubgraphArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cosmo:index/getFeatureSubgraph:getFeatureSubgraph", args, LookupFeatureSubgraphResultOutput{}, options).(LookupFeatureSubgraphResultOutput), nil
		}).(LookupFeatureSubgraphResultOutput)
}

// A collection of arguments for invoking getFeatureSubgraph.
type LookupFeatureSubgraphOutputArgs struct {
	Name      pulumi.StringInput    `pulumi:"name"`
	Namespace pulumi.StringPtrInput `pulumi:"namespace"`
}

func (LookupFeatureSubgraphOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFeatureSubgraphArgs)(nil)).Elem()
}

// A collection of values returned by getFeatureSubgraph.
type LookupFeatureSubgraphResultOutput struct{ *pulumi.OutputState }

func (LookupFeatureSubgraphResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFeatureSubgraphResult)(nil)).Elem()
}

func (o LookupFeatureSubgraphResultOutput) ToLookupFeatureSubgraphResultOutput() LookupFeatureSubgraphResultOutput {
	return o
}

func (o LookupFeatureSubgraphResultOutput) ToLookupFeatureSubgraphResultOutputWithContext(ctx context.Context) LookupFeatureSubgraphResultOutput {
	return o
}

func (o LookupFeatureSubgraphResultOutput) BaseSubgraphName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.BaseSubgraphName }).(pulumi.StringOutput)
}

func (o LookupFeatureSubgraphResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFeatureSubgraphResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupFeatureSubgraphResultOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

func (o LookupFeatureSubgraphResultOutput) Readme() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.Readme }).(pulumi.StringOutput)
}

func (o LookupFeatureSubgraphResultOutput) RoutingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.RoutingUrl }).(pulumi.StringOutput)
}

func (o LookupFeatureSubgraphResultOutput) Schema() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.Schema }).(pulumi.StringOutput)
}

func (o LookupFeatureSubgraphResultOutput) SubscriptionProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.SubscriptionProtocol }).(pulumi.StringOutput)
}

func (o LookupFeatureSubgraphResultOutput) SubscriptionUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.SubscriptionUrl }).(pulumi.StringOutput)
}

func (o LookupFeatureSubgraphResultOutput) WebsocketSubprotocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFeatureSubgraphResult) string { return v.WebsocketSubprotocol }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFeatureSubgraphResultOutput{})
}
