// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

func LookupMonograph(ctx *pulumi.Context, args *LookupMonographArgs, opts ...pulumi.InvokeOption) (*LookupMonographResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupMonographResult
	err := ctx.Invoke("cosmo:index/getMonograph:getMonograph", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMonograph.
type LookupMonographArgs struct {
	Name      string  `pulumi:"name"`
	Namespace *string `pulumi:"namespace"`
}

// A collection of values returned by getMonograph.
type LookupMonographResult struct {
	AdmissionWebhookSecret string   `pulumi:"admissionWebhookSecret"`
	AdmissionWebhookUrl    string   `pulumi:"admissionWebhookUrl"`
	Id                     string   `pulumi:"id"`
	LabelMatchers          []string `pulumi:"labelMatchers"`
	Name                   string   `pulumi:"name"`
	Namespace              *string  `pulumi:"namespace"`
	Readme                 string   `pulumi:"readme"`
	RoutingUrl             string   `pulumi:"routingUrl"`
	SubscriptionProtocol   string   `pulumi:"subscriptionProtocol"`
	WebsocketSubprotocol   string   `pulumi:"websocketSubprotocol"`
}

func LookupMonographOutput(ctx *pulumi.Context, args LookupMonographOutputArgs, opts ...pulumi.InvokeOption) LookupMonographResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupMonographResultOutput, error) {
			args := v.(LookupMonographArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cosmo:index/getMonograph:getMonograph", args, LookupMonographResultOutput{}, options).(LookupMonographResultOutput), nil
		}).(LookupMonographResultOutput)
}

// A collection of arguments for invoking getMonograph.
type LookupMonographOutputArgs struct {
	Name      pulumi.StringInput    `pulumi:"name"`
	Namespace pulumi.StringPtrInput `pulumi:"namespace"`
}

func (LookupMonographOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMonographArgs)(nil)).Elem()
}

// A collection of values returned by getMonograph.
type LookupMonographResultOutput struct{ *pulumi.OutputState }

func (LookupMonographResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMonographResult)(nil)).Elem()
}

func (o LookupMonographResultOutput) ToLookupMonographResultOutput() LookupMonographResultOutput {
	return o
}

func (o LookupMonographResultOutput) ToLookupMonographResultOutputWithContext(ctx context.Context) LookupMonographResultOutput {
	return o
}

func (o LookupMonographResultOutput) AdmissionWebhookSecret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonographResult) string { return v.AdmissionWebhookSecret }).(pulumi.StringOutput)
}

func (o LookupMonographResultOutput) AdmissionWebhookUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonographResult) string { return v.AdmissionWebhookUrl }).(pulumi.StringOutput)
}

func (o LookupMonographResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonographResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupMonographResultOutput) LabelMatchers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupMonographResult) []string { return v.LabelMatchers }).(pulumi.StringArrayOutput)
}

func (o LookupMonographResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonographResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupMonographResultOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMonographResult) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

func (o LookupMonographResultOutput) Readme() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonographResult) string { return v.Readme }).(pulumi.StringOutput)
}

func (o LookupMonographResultOutput) RoutingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonographResult) string { return v.RoutingUrl }).(pulumi.StringOutput)
}

func (o LookupMonographResultOutput) SubscriptionProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonographResult) string { return v.SubscriptionProtocol }).(pulumi.StringOutput)
}

func (o LookupMonographResultOutput) WebsocketSubprotocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMonographResult) string { return v.WebsocketSubprotocol }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMonographResultOutput{})
}
