// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

func LookupSubgraph(ctx *pulumi.Context, args *LookupSubgraphArgs, opts ...pulumi.InvokeOption) (*LookupSubgraphResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSubgraphResult
	err := ctx.Invoke("cosmo:index/getSubgraph:getSubgraph", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSubgraph.
type LookupSubgraphArgs struct {
	Name      string `pulumi:"name"`
	Namespace string `pulumi:"namespace"`
}

// A collection of values returned by getSubgraph.
type LookupSubgraphResult struct {
	BaseSubgraphName     string            `pulumi:"baseSubgraphName"`
	Headers              []string          `pulumi:"headers"`
	Id                   string            `pulumi:"id"`
	IsEventDrivenGraph   bool              `pulumi:"isEventDrivenGraph"`
	Labels               map[string]string `pulumi:"labels"`
	Name                 string            `pulumi:"name"`
	Namespace            string            `pulumi:"namespace"`
	Readme               string            `pulumi:"readme"`
	RoutingUrl           string            `pulumi:"routingUrl"`
	Schema               string            `pulumi:"schema"`
	SubscriptionProtocol string            `pulumi:"subscriptionProtocol"`
	SubscriptionUrl      string            `pulumi:"subscriptionUrl"`
	WebsocketSubprotocol string            `pulumi:"websocketSubprotocol"`
}

func LookupSubgraphOutput(ctx *pulumi.Context, args LookupSubgraphOutputArgs, opts ...pulumi.InvokeOption) LookupSubgraphResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSubgraphResultOutput, error) {
			args := v.(LookupSubgraphArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cosmo:index/getSubgraph:getSubgraph", args, LookupSubgraphResultOutput{}, options).(LookupSubgraphResultOutput), nil
		}).(LookupSubgraphResultOutput)
}

// A collection of arguments for invoking getSubgraph.
type LookupSubgraphOutputArgs struct {
	Name      pulumi.StringInput `pulumi:"name"`
	Namespace pulumi.StringInput `pulumi:"namespace"`
}

func (LookupSubgraphOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSubgraphArgs)(nil)).Elem()
}

// A collection of values returned by getSubgraph.
type LookupSubgraphResultOutput struct{ *pulumi.OutputState }

func (LookupSubgraphResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSubgraphResult)(nil)).Elem()
}

func (o LookupSubgraphResultOutput) ToLookupSubgraphResultOutput() LookupSubgraphResultOutput {
	return o
}

func (o LookupSubgraphResultOutput) ToLookupSubgraphResultOutputWithContext(ctx context.Context) LookupSubgraphResultOutput {
	return o
}

func (o LookupSubgraphResultOutput) BaseSubgraphName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.BaseSubgraphName }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) Headers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSubgraphResult) []string { return v.Headers }).(pulumi.StringArrayOutput)
}

func (o LookupSubgraphResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) IsEventDrivenGraph() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSubgraphResult) bool { return v.IsEventDrivenGraph }).(pulumi.BoolOutput)
}

func (o LookupSubgraphResultOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupSubgraphResult) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o LookupSubgraphResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.Namespace }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) Readme() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.Readme }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) RoutingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.RoutingUrl }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) Schema() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.Schema }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) SubscriptionProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.SubscriptionProtocol }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) SubscriptionUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.SubscriptionUrl }).(pulumi.StringOutput)
}

func (o LookupSubgraphResultOutput) WebsocketSubprotocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubgraphResult) string { return v.WebsocketSubprotocol }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSubgraphResultOutput{})
}
