// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "cosmo:index/contract:Contract":
		r = &Contract{}
	case "cosmo:index/featureFlag:FeatureFlag":
		r = &FeatureFlag{}
	case "cosmo:index/featureSubgraph:FeatureSubgraph":
		r = &FeatureSubgraph{}
	case "cosmo:index/federatedGraph:FederatedGraph":
		r = &FederatedGraph{}
	case "cosmo:index/monograph:Monograph":
		r = &Monograph{}
	case "cosmo:index/namespace:Namespace":
		r = &Namespace{}
	case "cosmo:index/routerToken:RouterToken":
		r = &RouterToken{}
	case "cosmo:index/subgraph:Subgraph":
		r = &Subgraph{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:cosmo" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"cosmo",
		"index/contract",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cosmo",
		"index/featureFlag",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cosmo",
		"index/featureSubgraph",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cosmo",
		"index/federatedGraph",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cosmo",
		"index/monograph",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cosmo",
		"index/namespace",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cosmo",
		"index/routerToken",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cosmo",
		"index/subgraph",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"cosmo",
		&pkg{version},
	)
}
