// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

var _ = internal.GetEnvOrDefault

type GetClientsClient struct {
	// The time the client was created.
	CreatedAt string `pulumi:"createdAt"`
	// The user that created the client.
	CreatedBy string `pulumi:"createdBy"`
	// The unique identifier of the client.
	Id string `pulumi:"id"`
	// The time the client was last updated.
	LastUpdatedAt string `pulumi:"lastUpdatedAt"`
	// The user that last updated the client.
	LastUpdatedBy string `pulumi:"lastUpdatedBy"`
	// The name of the client.
	Name string `pulumi:"name"`
	// The number of persisted operations registered for the client.
	PersistedOperationsCount int `pulumi:"persistedOperationsCount"`
}

// GetClientsClientInput is an input type that accepts GetClientsClientArgs and GetClientsClientOutput values.
// You can construct a concrete instance of `GetClientsClientInput` via:
//
//	GetClientsClientArgs{...}
type GetClientsClientInput interface {
	pulumi.Input

	ToGetClientsClientOutput() GetClientsClientOutput
	ToGetClientsClientOutputWithContext(context.Context) GetClientsClientOutput
}

type GetClientsClientArgs struct {
	// The time the client was created.
	CreatedAt pulumi.StringInput `pulumi:"createdAt"`
	// The user that created the client.
	CreatedBy pulumi.StringInput `pulumi:"createdBy"`
	// The unique identifier of the client.
	Id pulumi.StringInput `pulumi:"id"`
	// The time the client was last updated.
	LastUpdatedAt pulumi.StringInput `pulumi:"lastUpdatedAt"`
	// The user that last updated the client.
	LastUpdatedBy pulumi.StringInput `pulumi:"lastUpdatedBy"`
	// The name of the client.
	Name pulumi.StringInput `pulumi:"name"`
	// The number of persisted operations registered for the client.
	PersistedOperationsCount pulumi.IntInput `pulumi:"persistedOperationsCount"`
}

func (GetClientsClientArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClientsClient)(nil)).Elem()
}

func (i GetClientsClientArgs) ToGetClientsClientOutput() GetClientsClientOutput {
	return i.ToGetClientsClientOutputWithContext(context.Background())
}

func (i GetClientsClientArgs) ToGetClientsClientOutputWithContext(ctx context.Context) GetClientsClientOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClientsClientOutput)
}

// GetClientsClientArrayInput is an input type that accepts GetClientsClientArray and GetClientsClientArrayOutput values.
// You can construct a concrete instance of `GetClientsClientArrayInput` via:
//
//	GetClientsClientArray{ GetClientsClientArgs{...} }
type GetClientsClientArrayInput interface {
	pulumi.Input

	ToGetClientsClientArrayOutput() GetClientsClientArrayOutput
	ToGetClientsClientArrayOutputWithContext(context.Context) GetClientsClientArrayOutput
}

type GetClientsClientArray []GetClientsClientInput

func (GetClientsClientArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetClientsClient)(nil)).Elem()
}

func (i GetClientsClientArray) ToGetClientsClientArrayOutput() GetClientsClientArrayOutput {
	return i.ToGetClientsClientArrayOutputWithContext(context.Background())
}

func (i GetClientsClientArray) ToGetClientsClientArrayOutputWithContext(ctx context.Context) GetClientsClientArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClientsClientArrayOutput)
}

type GetClientsClientOutput struct{ *pulumi.OutputState }

func (GetClientsClientOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClientsClient)(nil)).Elem()
}

func (o GetClientsClientOutput) ToGetClientsClientOutput() GetClientsClientOutput {
	return o
}

func (o GetClientsClientOutput) ToGetClientsClientOutputWithContext(ctx context.Context) GetClientsClientOutput {
	return o
}

// The time the client was created.
func (o GetClientsClientOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientsClient) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The user that created the client.
func (o GetClientsClientOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientsClient) string { return v.CreatedBy }).(pulumi.StringOutput)
}

// The unique identifier of the client.
func (o GetClientsClientOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientsClient) string { return v.Id }).(pulumi.StringOutput)
}

// The time the client was last updated.
func (o GetClientsClientOutput) LastUpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientsClient) string { return v.LastUpdatedAt }).(pulumi.StringOutput)
}

// The user that last updated the client.
func (o GetClientsClientOutput) LastUpdatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientsClient) string { return v.LastUpdatedBy }).(pulumi.StringOutput)
}

// The name of the client.
func (o GetClientsClientOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientsClient) string { return v.Name }).(pulumi.StringOutput)
}

// The number of persisted operations registered for the client.
func (o GetClientsClientOutput) PersistedOperationsCount() pulumi.IntOutput {
	return o.ApplyT(func(v GetClientsClient) int { return v.PersistedOperationsCount }).(pulumi.IntOutput)
}

type GetClientsClientArrayOutput struct{ *pulumi.OutputState }

func (GetClientsClientArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetClientsClient)(nil)).Elem()
}

func (o GetClientsClientArrayOutput) ToGetClientsClientArrayOutput() GetClientsClientArrayOutput {
	return o
}

func (o GetClientsClientArrayOutput) ToGetClientsClientArrayOutputWithContext(ctx context.Context) GetClientsClientArrayOutput {
	return o
}

func (o GetClientsClientArrayOutput) Index(i pulumi.IntInput) GetClientsClientOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetClientsClient {
		return vs[0].([]GetClientsClient)[vs[1].(int)]
	}).(GetClientsClientOutput)
}

type GetPersistedOperationsOperation struct {
	// The GraphQL operation contents.
	Contents string `pulumi:"contents"`
	// The time the operation was created.
	CreatedAt string `pulumi:"createdAt"`
	// The unique identifier of the operation (the SHA-256 hash of its contents).
	Id string `pulumi:"id"`
	// The time the operation was last updated.
	LastUpdatedAt string `pulumi:"lastUpdatedAt"`
	// The names of the operations contained in the document.
	OperationNames []string `pulumi:"operationNames"`
}

// GetPersistedOperationsOperationInput is an input type that accepts GetPersistedOperationsOperationArgs and GetPersistedOperationsOperationOutput values.
// You can construct a concrete instance of `GetPersistedOperationsOperationInput` via:
//
//	GetPersistedOperationsOperationArgs{...}
type GetPersistedOperationsOperationInput interface {
	pulumi.Input

	ToGetPersistedOperationsOperationOutput() GetPersistedOperationsOperationOutput
	ToGetPersistedOperationsOperationOutputWithContext(context.Context) GetPersistedOperationsOperationOutput
}

type GetPersistedOperationsOperationArgs struct {
	// The GraphQL operation contents.
	Contents pulumi.StringInput `pulumi:"contents"`
	// The time the operation was created.
	CreatedAt pulumi.StringInput `pulumi:"createdAt"`
	// The unique identifier of the operation (the SHA-256 hash of its contents).
	Id pulumi.StringInput `pulumi:"id"`
	// The time the operation was last updated.
	LastUpdatedAt pulumi.StringInput `pulumi:"lastUpdatedAt"`
	// The names of the operations contained in the document.
	OperationNames pulumi.StringArrayInput `pulumi:"operationNames"`
}

func (GetPersistedOperationsOperationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPersistedOperationsOperation)(nil)).Elem()
}

func (i GetPersistedOperationsOperationArgs) ToGetPersistedOperationsOperationOutput() GetPersistedOperationsOperationOutput {
	return i.ToGetPersistedOperationsOperationOutputWithContext(context.Background())
}

func (i GetPersistedOperationsOperationArgs) ToGetPersistedOperationsOperationOutputWithContext(ctx context.Context) GetPersistedOperationsOperationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPersistedOperationsOperationOutput)
}

// GetPersistedOperationsOperationArrayInput is an input type that accepts GetPersistedOperationsOperationArray and GetPersistedOperationsOperationArrayOutput values.
// You can construct a concrete instance of `GetPersistedOperationsOperationArrayInput` via:
//
//	GetPersistedOperationsOperationArray{ GetPersistedOperationsOperationArgs{...} }
type GetPersistedOperationsOperationArrayInput interface {
	pulumi.Input

	ToGetPersistedOperationsOperationArrayOutput() GetPersistedOperationsOperationArrayOutput
	ToGetPersistedOperationsOperationArrayOutputWithContext(context.Context) GetPersistedOperationsOperationArrayOutput
}

type GetPersistedOperationsOperationArray []GetPersistedOperationsOperationInput

func (GetPersistedOperationsOperationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPersistedOperationsOperation)(nil)).Elem()
}

func (i GetPersistedOperationsOperationArray) ToGetPersistedOperationsOperationArrayOutput() GetPersistedOperationsOperationArrayOutput {
	return i.ToGetPersistedOperationsOperationArrayOutputWithContext(context.Background())
}

func (i GetPersistedOperationsOperationArray) ToGetPersistedOperationsOperationArrayOutputWithContext(ctx context.Context) GetPersistedOperationsOperationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPersistedOperationsOperationArrayOutput)
}

type GetPersistedOperationsOperationOutput struct{ *pulumi.OutputState }

func (GetPersistedOperationsOperationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPersistedOperationsOperation)(nil)).Elem()
}

func (o GetPersistedOperationsOperationOutput) ToGetPersistedOperationsOperationOutput() GetPersistedOperationsOperationOutput {
	return o
}

func (o GetPersistedOperationsOperationOutput) ToGetPersistedOperationsOperationOutputWithContext(ctx context.Context) GetPersistedOperationsOperationOutput {
	return o
}

// The GraphQL operation contents.
func (o GetPersistedOperationsOperationOutput) Contents() pulumi.StringOutput {
	return o.ApplyT(func(v GetPersistedOperationsOperation) string { return v.Contents }).(pulumi.StringOutput)
}

// The time the operation was created.
func (o GetPersistedOperationsOperationOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetPersistedOperationsOperation) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The unique identifier of the operation (the SHA-256 hash of its contents).
func (o GetPersistedOperationsOperationOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPersistedOperationsOperation) string { return v.Id }).(pulumi.StringOutput)
}

// The time the operation was last updated.
func (o GetPersistedOperationsOperationOutput) LastUpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetPersistedOperationsOperation) string { return v.LastUpdatedAt }).(pulumi.StringOutput)
}

// The names of the operations contained in the document.
func (o GetPersistedOperationsOperationOutput) OperationNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPersistedOperationsOperation) []string { return v.OperationNames }).(pulumi.StringArrayOutput)
}

type GetPersistedOperationsOperationArrayOutput struct{ *pulumi.OutputState }

func (GetPersistedOperationsOperationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPersistedOperationsOperation)(nil)).Elem()
}

func (o GetPersistedOperationsOperationArrayOutput) ToGetPersistedOperationsOperationArrayOutput() GetPersistedOperationsOperationArrayOutput {
	return o
}

func (o GetPersistedOperationsOperationArrayOutput) ToGetPersistedOperationsOperationArrayOutputWithContext(ctx context.Context) GetPersistedOperationsOperationArrayOutput {
	return o
}

func (o GetPersistedOperationsOperationArrayOutput) Index(i pulumi.IntInput) GetPersistedOperationsOperationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPersistedOperationsOperation {
		return vs[0].([]GetPersistedOperationsOperation)[vs[1].(int)]
	}).(GetPersistedOperationsOperationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetClientsClientInput)(nil)).Elem(), GetClientsClientArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetClientsClientArrayInput)(nil)).Elem(), GetClientsClientArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPersistedOperationsOperationInput)(nil)).Elem(), GetPersistedOperationsOperationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPersistedOperationsOperationArrayInput)(nil)).Elem(), GetPersistedOperationsOperationArray{})
	pulumi.RegisterOutputType(GetClientsClientOutput{})
	pulumi.RegisterOutputType(GetClientsClientArrayOutput{})
	pulumi.RegisterOutputType(GetPersistedOperationsOperationOutput{})
	pulumi.RegisterOutputType(GetPersistedOperationsOperationArrayOutput{})
}
