// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

type RouterToken struct {
	pulumi.CustomResourceState

	// The name of the graph to create the token for.
	GraphName pulumi.StringOutput `pulumi:"graphName"`
	// The name of the router token.
	Name pulumi.StringOutput `pulumi:"name"`
	// The namespace to create the token in.
	Namespace pulumi.StringOutput `pulumi:"namespace"`
	// The token to be used for the router.
	Token pulumi.StringOutput `pulumi:"token"`
}

// NewRouterToken registers a new resource with the given unique name, arguments, and options.
func NewRouterToken(ctx *pulumi.Context,
	name string, args *RouterTokenArgs, opts ...pulumi.ResourceOption) (*RouterToken, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.GraphName == nil {
		return nil, errors.New("invalid value for required argument 'GraphName'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RouterToken
	err := ctx.RegisterResource("cosmo:index/routerToken:RouterToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRouterToken gets an existing RouterToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRouterToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RouterTokenState, opts ...pulumi.ResourceOption) (*RouterToken, error) {
	var resource RouterToken
	err := ctx.ReadResource("cosmo:index/routerToken:RouterToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RouterToken resources.
type routerTokenState struct {
	// The name of the graph to create the token for.
	GraphName *string `pulumi:"graphName"`
	// The name of the router token.
	Name *string `pulumi:"name"`
	// The namespace to create the token in.
	Namespace *string `pulumi:"namespace"`
	// The token to be used for the router.
	Token *string `pulumi:"token"`
}

type RouterTokenState struct {
	// The name of the graph to create the token for.
	GraphName pulumi.StringPtrInput
	// The name of the router token.
	Name pulumi.StringPtrInput
	// The namespace to create the token in.
	Namespace pulumi.StringPtrInput
	// The token to be used for the router.
	Token pulumi.StringPtrInput
}

func (RouterTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*routerTokenState)(nil)).Elem()
}

type routerTokenArgs struct {
	// The name of the graph to create the token for.
	GraphName string `pulumi:"graphName"`
	// The name of the router token.
	Name *string `pulumi:"name"`
	// The namespace to create the token in.
	Namespace *string `pulumi:"namespace"`
}

// The set of arguments for constructing a RouterToken resource.
type RouterTokenArgs struct {
	// The name of the graph to create the token for.
	GraphName pulumi.StringInput
	// The name of the router token.
	Name pulumi.StringPtrInput
	// The namespace to create the token in.
	Namespace pulumi.StringPtrInput
}

func (RouterTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*routerTokenArgs)(nil)).Elem()
}

type RouterTokenInput interface {
	pulumi.Input

	ToRouterTokenOutput() RouterTokenOutput
	ToRouterTokenOutputWithContext(ctx context.Context) RouterTokenOutput
}

func (*RouterToken) ElementType() reflect.Type {
	return reflect.TypeOf((**RouterToken)(nil)).Elem()
}

func (i *RouterToken) ToRouterTokenOutput() RouterTokenOutput {
	return i.ToRouterTokenOutputWithContext(context.Background())
}

func (i *RouterToken) ToRouterTokenOutputWithContext(ctx context.Context) RouterTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RouterTokenOutput)
}

// RouterTokenArrayInput is an input type that accepts RouterTokenArray and RouterTokenArrayOutput values.
// You can construct a concrete instance of `RouterTokenArrayInput` via:
//
//	RouterTokenArray{ RouterTokenArgs{...} }
type RouterTokenArrayInput interface {
	pulumi.Input

	ToRouterTokenArrayOutput() RouterTokenArrayOutput
	ToRouterTokenArrayOutputWithContext(context.Context) RouterTokenArrayOutput
}

type RouterTokenArray []RouterTokenInput

func (RouterTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RouterToken)(nil)).Elem()
}

func (i RouterTokenArray) ToRouterTokenArrayOutput() RouterTokenArrayOutput {
	return i.ToRouterTokenArrayOutputWithContext(context.Background())
}

func (i RouterTokenArray) ToRouterTokenArrayOutputWithContext(ctx context.Context) RouterTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RouterTokenArrayOutput)
}

// RouterTokenMapInput is an input type that accepts RouterTokenMap and RouterTokenMapOutput values.
// You can construct a concrete instance of `RouterTokenMapInput` via:
//
//	RouterTokenMap{ "key": RouterTokenArgs{...} }
type RouterTokenMapInput interface {
	pulumi.Input

	ToRouterTokenMapOutput() RouterTokenMapOutput
	ToRouterTokenMapOutputWithContext(context.Context) RouterTokenMapOutput
}

type RouterTokenMap map[string]RouterTokenInput

func (RouterTokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RouterToken)(nil)).Elem()
}

func (i RouterTokenMap) ToRouterTokenMapOutput() RouterTokenMapOutput {
	return i.ToRouterTokenMapOutputWithContext(context.Background())
}

func (i RouterTokenMap) ToRouterTokenMapOutputWithContext(ctx context.Context) RouterTokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RouterTokenMapOutput)
}

type RouterTokenOutput struct{ *pulumi.OutputState }

func (RouterTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RouterToken)(nil)).Elem()
}

func (o RouterTokenOutput) ToRouterTokenOutput() RouterTokenOutput {
	return o
}

func (o RouterTokenOutput) ToRouterTokenOutputWithContext(ctx context.Context) RouterTokenOutput {
	return o
}

// The name of the graph to create the token for.
func (o RouterTokenOutput) GraphName() pulumi.StringOutput {
	return o.ApplyT(func(v *RouterToken) pulumi.StringOutput { return v.GraphName }).(pulumi.StringOutput)
}

// The name of the router token.
func (o RouterTokenOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RouterToken) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The namespace to create the token in.
func (o RouterTokenOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v *RouterToken) pulumi.StringOutput { return v.Namespace }).(pulumi.StringOutput)
}

// The token to be used for the router.
func (o RouterTokenOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *RouterToken) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

type RouterTokenArrayOutput struct{ *pulumi.OutputState }

func (RouterTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RouterToken)(nil)).Elem()
}

func (o RouterTokenArrayOutput) ToRouterTokenArrayOutput() RouterTokenArrayOutput {
	return o
}

func (o RouterTokenArrayOutput) ToRouterTokenArrayOutputWithContext(ctx context.Context) RouterTokenArrayOutput {
	return o
}

func (o RouterTokenArrayOutput) Index(i pulumi.IntInput) RouterTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RouterToken {
		return vs[0].([]*RouterToken)[vs[1].(int)]
	}).(RouterTokenOutput)
}

type RouterTokenMapOutput struct{ *pulumi.OutputState }

func (RouterTokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RouterToken)(nil)).Elem()
}

func (o RouterTokenMapOutput) ToRouterTokenMapOutput() RouterTokenMapOutput {
	return o
}

func (o RouterTokenMapOutput) ToRouterTokenMapOutputWithContext(ctx context.Context) RouterTokenMapOutput {
	return o
}

func (o RouterTokenMapOutput) MapIndex(k pulumi.StringInput) RouterTokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RouterToken {
		return vs[0].(map[string]*RouterToken)[vs[1].(string)]
	}).(RouterTokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RouterTokenInput)(nil)).Elem(), &RouterToken{})
	pulumi.RegisterInputType(reflect.TypeOf((*RouterTokenArrayInput)(nil)).Elem(), RouterTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RouterTokenMapInput)(nil)).Elem(), RouterTokenMap{})
	pulumi.RegisterOutputType(RouterTokenOutput{})
	pulumi.RegisterOutputType(RouterTokenArrayOutput{})
	pulumi.RegisterOutputType(RouterTokenMapOutput{})
}
