// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cosmo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wundergraph/pulumi-cosmo/sdk/go/cosmo/internal"
)

type Subgraph struct {
	pulumi.CustomResourceState

	// Indicates if the subgraph is event-driven.
	IsEventDrivenGraph pulumi.BoolOutput `pulumi:"isEventDrivenGraph"`
	// Labels for the subgraph.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// The name of the subgraph.
	Name pulumi.StringOutput `pulumi:"name"`
	// The namespace in which the subgraph is located.
	Namespace pulumi.StringOutput `pulumi:"namespace"`
	// The readme for the subgraph.
	Readme pulumi.StringPtrOutput `pulumi:"readme"`
	// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	RoutingUrl pulumi.StringOutput `pulumi:"routingUrl"`
	// The schema for the subgraph.
	Schema pulumi.StringPtrOutput `pulumi:"schema"`
	// The subscription protocol for the subgraph.
	SubscriptionProtocol pulumi.StringOutput `pulumi:"subscriptionProtocol"`
	// The subscription URL for the subgraph.
	SubscriptionUrl pulumi.StringPtrOutput `pulumi:"subscriptionUrl"`
	// Unset labels for the subgraph.
	UnsetLabels pulumi.BoolPtrOutput `pulumi:"unsetLabels"`
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol pulumi.StringOutput `pulumi:"websocketSubprotocol"`
}

// NewSubgraph registers a new resource with the given unique name, arguments, and options.
func NewSubgraph(ctx *pulumi.Context,
	name string, args *SubgraphArgs, opts ...pulumi.ResourceOption) (*Subgraph, error) {
	if args == nil {
		args = &SubgraphArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Subgraph
	err := ctx.RegisterResource("cosmo:index/subgraph:Subgraph", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSubgraph gets an existing Subgraph resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSubgraph(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SubgraphState, opts ...pulumi.ResourceOption) (*Subgraph, error) {
	var resource Subgraph
	err := ctx.ReadResource("cosmo:index/subgraph:Subgraph", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Subgraph resources.
type subgraphState struct {
	// Indicates if the subgraph is event-driven.
	IsEventDrivenGraph *bool `pulumi:"isEventDrivenGraph"`
	// Labels for the subgraph.
	Labels map[string]string `pulumi:"labels"`
	// The name of the subgraph.
	Name *string `pulumi:"name"`
	// The namespace in which the subgraph is located.
	Namespace *string `pulumi:"namespace"`
	// The readme for the subgraph.
	Readme *string `pulumi:"readme"`
	// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	RoutingUrl *string `pulumi:"routingUrl"`
	// The schema for the subgraph.
	Schema *string `pulumi:"schema"`
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `pulumi:"subscriptionProtocol"`
	// The subscription URL for the subgraph.
	SubscriptionUrl *string `pulumi:"subscriptionUrl"`
	// Unset labels for the subgraph.
	UnsetLabels *bool `pulumi:"unsetLabels"`
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `pulumi:"websocketSubprotocol"`
}

type SubgraphState struct {
	// Indicates if the subgraph is event-driven.
	IsEventDrivenGraph pulumi.BoolPtrInput
	// Labels for the subgraph.
	Labels pulumi.StringMapInput
	// The name of the subgraph.
	Name pulumi.StringPtrInput
	// The namespace in which the subgraph is located.
	Namespace pulumi.StringPtrInput
	// The readme for the subgraph.
	Readme pulumi.StringPtrInput
	// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	RoutingUrl pulumi.StringPtrInput
	// The schema for the subgraph.
	Schema pulumi.StringPtrInput
	// The subscription protocol for the subgraph.
	SubscriptionProtocol pulumi.StringPtrInput
	// The subscription URL for the subgraph.
	SubscriptionUrl pulumi.StringPtrInput
	// Unset labels for the subgraph.
	UnsetLabels pulumi.BoolPtrInput
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol pulumi.StringPtrInput
}

func (SubgraphState) ElementType() reflect.Type {
	return reflect.TypeOf((*subgraphState)(nil)).Elem()
}

type subgraphArgs struct {
	// Indicates if the subgraph is event-driven.
	IsEventDrivenGraph *bool `pulumi:"isEventDrivenGraph"`
	// Labels for the subgraph.
	Labels map[string]string `pulumi:"labels"`
	// The name of the subgraph.
	Name *string `pulumi:"name"`
	// The namespace in which the subgraph is located.
	Namespace *string `pulumi:"namespace"`
	// The readme for the subgraph.
	Readme *string `pulumi:"readme"`
	// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	RoutingUrl *string `pulumi:"routingUrl"`
	// The schema for the subgraph.
	Schema *string `pulumi:"schema"`
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `pulumi:"subscriptionProtocol"`
	// The subscription URL for the subgraph.
	SubscriptionUrl *string `pulumi:"subscriptionUrl"`
	// Unset labels for the subgraph.
	UnsetLabels *bool `pulumi:"unsetLabels"`
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `pulumi:"websocketSubprotocol"`
}

// The set of arguments for constructing a Subgraph resource.
type SubgraphArgs struct {
	// Indicates if the subgraph is event-driven.
	IsEventDrivenGraph pulumi.BoolPtrInput
	// Labels for the subgraph.
	Labels pulumi.StringMapInput
	// The name of the subgraph.
	Name pulumi.StringPtrInput
	// The namespace in which the subgraph is located.
	Namespace pulumi.StringPtrInput
	// The readme for the subgraph.
	Readme pulumi.StringPtrInput
	// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	RoutingUrl pulumi.StringPtrInput
	// The schema for the subgraph.
	Schema pulumi.StringPtrInput
	// The subscription protocol for the subgraph.
	SubscriptionProtocol pulumi.StringPtrInput
	// The subscription URL for the subgraph.
	SubscriptionUrl pulumi.StringPtrInput
	// Unset labels for the subgraph.
	UnsetLabels pulumi.BoolPtrInput
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol pulumi.StringPtrInput
}

func (SubgraphArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*subgraphArgs)(nil)).Elem()
}

type SubgraphInput interface {
	pulumi.Input

	ToSubgraphOutput() SubgraphOutput
	ToSubgraphOutputWithContext(ctx context.Context) SubgraphOutput
}

func (*Subgraph) ElementType() reflect.Type {
	return reflect.TypeOf((**Subgraph)(nil)).Elem()
}

func (i *Subgraph) ToSubgraphOutput() SubgraphOutput {
	return i.ToSubgraphOutputWithContext(context.Background())
}

func (i *Subgraph) ToSubgraphOutputWithContext(ctx context.Context) SubgraphOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubgraphOutput)
}

// SubgraphArrayInput is an input type that accepts SubgraphArray and SubgraphArrayOutput values.
// You can construct a concrete instance of `SubgraphArrayInput` via:
//
//	SubgraphArray{ SubgraphArgs{...} }
type SubgraphArrayInput interface {
	pulumi.Input

	ToSubgraphArrayOutput() SubgraphArrayOutput
	ToSubgraphArrayOutputWithContext(context.Context) SubgraphArrayOutput
}

type SubgraphArray []SubgraphInput

func (SubgraphArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Subgraph)(nil)).Elem()
}

func (i SubgraphArray) ToSubgraphArrayOutput() SubgraphArrayOutput {
	return i.ToSubgraphArrayOutputWithContext(context.Background())
}

func (i SubgraphArray) ToSubgraphArrayOutputWithContext(ctx context.Context) SubgraphArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubgraphArrayOutput)
}

// SubgraphMapInput is an input type that accepts SubgraphMap and SubgraphMapOutput values.
// You can construct a concrete instance of `SubgraphMapInput` via:
//
//	SubgraphMap{ "key": SubgraphArgs{...} }
type SubgraphMapInput interface {
	pulumi.Input

	ToSubgraphMapOutput() SubgraphMapOutput
	ToSubgraphMapOutputWithContext(context.Context) SubgraphMapOutput
}

type SubgraphMap map[string]SubgraphInput

func (SubgraphMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Subgraph)(nil)).Elem()
}

func (i SubgraphMap) ToSubgraphMapOutput() SubgraphMapOutput {
	return i.ToSubgraphMapOutputWithContext(context.Background())
}

func (i SubgraphMap) ToSubgraphMapOutputWithContext(ctx context.Context) SubgraphMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubgraphMapOutput)
}

type SubgraphOutput struct{ *pulumi.OutputState }

func (SubgraphOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Subgraph)(nil)).Elem()
}

func (o SubgraphOutput) ToSubgraphOutput() SubgraphOutput {
	return o
}

func (o SubgraphOutput) ToSubgraphOutputWithContext(ctx context.Context) SubgraphOutput {
	return o
}

// Indicates if the subgraph is event-driven.
func (o SubgraphOutput) IsEventDrivenGraph() pulumi.BoolOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.BoolOutput { return v.IsEventDrivenGraph }).(pulumi.BoolOutput)
}

// Labels for the subgraph.
func (o SubgraphOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// The name of the subgraph.
func (o SubgraphOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The namespace in which the subgraph is located.
func (o SubgraphOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringOutput { return v.Namespace }).(pulumi.StringOutput)
}

// The readme for the subgraph.
func (o SubgraphOutput) Readme() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringPtrOutput { return v.Readme }).(pulumi.StringPtrOutput)
}

// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
func (o SubgraphOutput) RoutingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringOutput { return v.RoutingUrl }).(pulumi.StringOutput)
}

// The schema for the subgraph.
func (o SubgraphOutput) Schema() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringPtrOutput { return v.Schema }).(pulumi.StringPtrOutput)
}

// The subscription protocol for the subgraph.
func (o SubgraphOutput) SubscriptionProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringOutput { return v.SubscriptionProtocol }).(pulumi.StringOutput)
}

// The subscription URL for the subgraph.
func (o SubgraphOutput) SubscriptionUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringPtrOutput { return v.SubscriptionUrl }).(pulumi.StringPtrOutput)
}

// Unset labels for the subgraph.
func (o SubgraphOutput) UnsetLabels() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.BoolPtrOutput { return v.UnsetLabels }).(pulumi.BoolPtrOutput)
}

// The websocket subprotocol for the subgraph.
func (o SubgraphOutput) WebsocketSubprotocol() pulumi.StringOutput {
	return o.ApplyT(func(v *Subgraph) pulumi.StringOutput { return v.WebsocketSubprotocol }).(pulumi.StringOutput)
}

type SubgraphArrayOutput struct{ *pulumi.OutputState }

func (SubgraphArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Subgraph)(nil)).Elem()
}

func (o SubgraphArrayOutput) ToSubgraphArrayOutput() SubgraphArrayOutput {
	return o
}

func (o SubgraphArrayOutput) ToSubgraphArrayOutputWithContext(ctx context.Context) SubgraphArrayOutput {
	return o
}

func (o SubgraphArrayOutput) Index(i pulumi.IntInput) SubgraphOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Subgraph {
		return vs[0].([]*Subgraph)[vs[1].(int)]
	}).(SubgraphOutput)
}

type SubgraphMapOutput struct{ *pulumi.OutputState }

func (SubgraphMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Subgraph)(nil)).Elem()
}

func (o SubgraphMapOutput) ToSubgraphMapOutput() SubgraphMapOutput {
	return o
}

func (o SubgraphMapOutput) ToSubgraphMapOutputWithContext(ctx context.Context) SubgraphMapOutput {
	return o
}

func (o SubgraphMapOutput) MapIndex(k pulumi.StringInput) SubgraphOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Subgraph {
		return vs[0].(map[string]*Subgraph)[vs[1].(string)]
	}).(SubgraphOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SubgraphInput)(nil)).Elem(), &Subgraph{})
	pulumi.RegisterInputType(reflect.TypeOf((*SubgraphArrayInput)(nil)).Elem(), SubgraphArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SubgraphMapInput)(nil)).Elem(), SubgraphMap{})
	pulumi.RegisterOutputType(SubgraphOutput{})
	pulumi.RegisterOutputType(SubgraphArrayOutput{})
	pulumi.RegisterOutputType(SubgraphMapOutput{})
}
