// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetClientsClient {
    /**
     * The time the client was created.
     */
    createdAt: string;
    /**
     * The user that created the client.
     */
    createdBy: string;
    /**
     * The unique identifier of the client.
     */
    id: string;
    /**
     * The time the client was last updated.
     */
    lastUpdatedAt: string;
    /**
     * The user that last updated the client.
     */
    lastUpdatedBy: string;
    /**
     * The name of the client.
     */
    name: string;
    /**
     * The number of persisted operations registered for the client.
     */
    persistedOperationsCount: number;
}

export interface GetPersistedOperationsOperation {
    /**
     * The GraphQL operation contents.
     */
    contents: string;
    /**
     * The time the operation was created.
     */
    createdAt: string;
    /**
     * The unique identifier of the operation (the SHA-256 hash of its contents).
     */
    id: string;
    /**
     * The time the operation was last updated.
     */
    lastUpdatedAt: string;
    /**
     * The names of the operations contained in the document.
     */
    operationNames: string[];
}

