// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Contract extends pulumi.CustomResource {
    /**
     * Get an existing Contract resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ContractState, opts?: pulumi.CustomResourceOptions): Contract {
        return new Contract(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cosmo:index/contract:Contract';

    /**
     * Returns true if the given object is an instance of Contract.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Contract {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Contract.__pulumiType;
    }

    declare public readonly admissionWebhookSecret: pulumi.Output<string | undefined>;
    declare public readonly admissionWebhookUrl: pulumi.Output<string | undefined>;
    declare public readonly excludeTags: pulumi.Output<string[] | undefined>;
    declare public readonly includeTags: pulumi.Output<string[] | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly namespace: pulumi.Output<string>;
    declare public readonly readme: pulumi.Output<string | undefined>;
    declare public readonly routingUrl: pulumi.Output<string>;
    declare public readonly source: pulumi.Output<string>;
    declare public readonly supportsFederation: pulumi.Output<boolean>;

    /**
     * Create a Contract resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ContractArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ContractArgs | ContractState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ContractState | undefined;
            resourceInputs["admissionWebhookSecret"] = state?.admissionWebhookSecret;
            resourceInputs["admissionWebhookUrl"] = state?.admissionWebhookUrl;
            resourceInputs["excludeTags"] = state?.excludeTags;
            resourceInputs["includeTags"] = state?.includeTags;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["readme"] = state?.readme;
            resourceInputs["routingUrl"] = state?.routingUrl;
            resourceInputs["source"] = state?.source;
            resourceInputs["supportsFederation"] = state?.supportsFederation;
        } else {
            const args = argsOrState as ContractArgs | undefined;
            if (args?.namespace === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespace'");
            }
            if (args?.routingUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'routingUrl'");
            }
            if (args?.source === undefined && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["admissionWebhookSecret"] = args?.admissionWebhookSecret;
            resourceInputs["admissionWebhookUrl"] = args?.admissionWebhookUrl;
            resourceInputs["excludeTags"] = args?.excludeTags;
            resourceInputs["includeTags"] = args?.includeTags;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["readme"] = args?.readme;
            resourceInputs["routingUrl"] = args?.routingUrl;
            resourceInputs["source"] = args?.source;
            resourceInputs["supportsFederation"] = args?.supportsFederation;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Contract.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Contract resources.
 */
export interface ContractState {
    admissionWebhookSecret?: pulumi.Input<string>;
    admissionWebhookUrl?: pulumi.Input<string>;
    excludeTags?: pulumi.Input<pulumi.Input<string>[]>;
    includeTags?: pulumi.Input<pulumi.Input<string>[]>;
    name?: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    readme?: pulumi.Input<string>;
    routingUrl?: pulumi.Input<string>;
    source?: pulumi.Input<string>;
    supportsFederation?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Contract resource.
 */
export interface ContractArgs {
    admissionWebhookSecret?: pulumi.Input<string>;
    admissionWebhookUrl?: pulumi.Input<string>;
    excludeTags?: pulumi.Input<pulumi.Input<string>[]>;
    includeTags?: pulumi.Input<pulumi.Input<string>[]>;
    name?: pulumi.Input<string>;
    namespace: pulumi.Input<string>;
    readme?: pulumi.Input<string>;
    routingUrl: pulumi.Input<string>;
    source: pulumi.Input<string>;
    supportsFederation?: pulumi.Input<boolean>;
}
