// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class FederatedGraph extends pulumi.CustomResource {
    /**
     * Get an existing FederatedGraph resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FederatedGraphState, opts?: pulumi.CustomResourceOptions): FederatedGraph {
        return new FederatedGraph(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cosmo:index/federatedGraph:FederatedGraph';

    /**
     * Returns true if the given object is an instance of FederatedGraph.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FederatedGraph {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FederatedGraph.__pulumiType;
    }

    /**
     * The secret token used to authenticate the admission webhook requests.
     */
    declare public readonly admissionWebhookSecret: pulumi.Output<string | undefined>;
    /**
     * The URL for the admission webhook that will be triggered during graph operations.
     */
    declare public readonly admissionWebhookUrl: pulumi.Output<string | undefined>;
    /**
     * A list of label matchers used to select the services that will form the federated graph.
     */
    declare public readonly labelMatchers: pulumi.Output<string[]>;
    /**
     * The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The namespace in which the federated graph is located. Defaults to 'default' if not provided.
     */
    declare public readonly namespace: pulumi.Output<string>;
    /**
     * Readme content for the federated graph.
     */
    declare public readonly readme: pulumi.Output<string | undefined>;
    /**
     * The URL of the service that routes requests to the federated graph.
     */
    declare public readonly routingUrl: pulumi.Output<string>;

    /**
     * Create a FederatedGraph resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FederatedGraphArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FederatedGraphArgs | FederatedGraphState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FederatedGraphState | undefined;
            resourceInputs["admissionWebhookSecret"] = state?.admissionWebhookSecret;
            resourceInputs["admissionWebhookUrl"] = state?.admissionWebhookUrl;
            resourceInputs["labelMatchers"] = state?.labelMatchers;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["readme"] = state?.readme;
            resourceInputs["routingUrl"] = state?.routingUrl;
        } else {
            const args = argsOrState as FederatedGraphArgs | undefined;
            if (args?.routingUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'routingUrl'");
            }
            resourceInputs["admissionWebhookSecret"] = args?.admissionWebhookSecret ? pulumi.secret(args.admissionWebhookSecret) : undefined;
            resourceInputs["admissionWebhookUrl"] = args?.admissionWebhookUrl;
            resourceInputs["labelMatchers"] = args?.labelMatchers;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["readme"] = args?.readme;
            resourceInputs["routingUrl"] = args?.routingUrl;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["admissionWebhookSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(FederatedGraph.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FederatedGraph resources.
 */
export interface FederatedGraphState {
    /**
     * The secret token used to authenticate the admission webhook requests.
     */
    admissionWebhookSecret?: pulumi.Input<string>;
    /**
     * The URL for the admission webhook that will be triggered during graph operations.
     */
    admissionWebhookUrl?: pulumi.Input<string>;
    /**
     * A list of label matchers used to select the services that will form the federated graph.
     */
    labelMatchers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
     */
    name?: pulumi.Input<string>;
    /**
     * The namespace in which the federated graph is located. Defaults to 'default' if not provided.
     */
    namespace?: pulumi.Input<string>;
    /**
     * Readme content for the federated graph.
     */
    readme?: pulumi.Input<string>;
    /**
     * The URL of the service that routes requests to the federated graph.
     */
    routingUrl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FederatedGraph resource.
 */
export interface FederatedGraphArgs {
    /**
     * The secret token used to authenticate the admission webhook requests.
     */
    admissionWebhookSecret?: pulumi.Input<string>;
    /**
     * The URL for the admission webhook that will be triggered during graph operations.
     */
    admissionWebhookUrl?: pulumi.Input<string>;
    /**
     * A list of label matchers used to select the services that will form the federated graph.
     */
    labelMatchers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
     */
    name?: pulumi.Input<string>;
    /**
     * The namespace in which the federated graph is located. Defaults to 'default' if not provided.
     */
    namespace?: pulumi.Input<string>;
    /**
     * Readme content for the federated graph.
     */
    readme?: pulumi.Input<string>;
    /**
     * The URL of the service that routes requests to the federated graph.
     */
    routingUrl: pulumi.Input<string>;
}
