// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getContract(args: GetContractArgs, opts?: pulumi.InvokeOptions): Promise<GetContractResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cosmo:index/getContract:getContract", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getContract.
 */
export interface GetContractArgs {
    name: string;
    namespace: string;
}

/**
 * A collection of values returned by getContract.
 */
export interface GetContractResult {
    readonly admissionWebhookSecret: string;
    readonly admissionWebhookUrl: string;
    readonly excludeTags: string[];
    readonly id: string;
    readonly includeTags: string[];
    readonly labelMatchers: {[key: string]: string};
    readonly name: string;
    readonly namespace: string;
    readonly readme: string;
    readonly routingUrl: string;
    readonly supportsFederation: boolean;
}
export function getContractOutput(args: GetContractOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetContractResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cosmo:index/getContract:getContract", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getContract.
 */
export interface GetContractOutputArgs {
    name: pulumi.Input<string>;
    namespace: pulumi.Input<string>;
}
