// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getFederatedGraph(args: GetFederatedGraphArgs, opts?: pulumi.InvokeOptions): Promise<GetFederatedGraphResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cosmo:index/getFederatedGraph:getFederatedGraph", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getFederatedGraph.
 */
export interface GetFederatedGraphArgs {
    name: string;
    namespace: string;
}

/**
 * A collection of values returned by getFederatedGraph.
 */
export interface GetFederatedGraphResult {
    readonly admissionWebhookSecret: string;
    readonly admissionWebhookUrl: string;
    readonly id: string;
    readonly labelMatchers: {[key: string]: string};
    readonly name: string;
    readonly namespace: string;
    readonly readme: string;
    readonly routingUrl: string;
}
export function getFederatedGraphOutput(args: GetFederatedGraphOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetFederatedGraphResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cosmo:index/getFederatedGraph:getFederatedGraph", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getFederatedGraph.
 */
export interface GetFederatedGraphOutputArgs {
    name: pulumi.Input<string>;
    namespace: pulumi.Input<string>;
}
