// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getMonograph(args: GetMonographArgs, opts?: pulumi.InvokeOptions): Promise<GetMonographResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cosmo:index/getMonograph:getMonograph", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getMonograph.
 */
export interface GetMonographArgs {
    name: string;
    namespace?: string;
}

/**
 * A collection of values returned by getMonograph.
 */
export interface GetMonographResult {
    readonly admissionWebhookSecret: string;
    readonly admissionWebhookUrl: string;
    readonly id: string;
    readonly labelMatchers: string[];
    readonly name: string;
    readonly namespace?: string;
    readonly readme: string;
    readonly routingUrl: string;
    readonly subscriptionProtocol: string;
    readonly websocketSubprotocol: string;
}
export function getMonographOutput(args: GetMonographOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMonographResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cosmo:index/getMonograph:getMonograph", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getMonograph.
 */
export interface GetMonographOutputArgs {
    name: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
}
