// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPersistedOperations(args: GetPersistedOperationsArgs, opts?: pulumi.InvokeOptions): Promise<GetPersistedOperationsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cosmo:index/getPersistedOperations:getPersistedOperations", {
        "clientName": args.clientName,
        "federatedGraphName": args.federatedGraphName,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getPersistedOperations.
 */
export interface GetPersistedOperationsArgs {
    clientName: string;
    federatedGraphName: string;
    namespace?: string;
}

/**
 * A collection of values returned by getPersistedOperations.
 */
export interface GetPersistedOperationsResult {
    readonly clientId: string;
    readonly clientName: string;
    readonly federatedGraphName: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly namespace: string;
    readonly operations: outputs.GetPersistedOperationsOperation[];
}
export function getPersistedOperationsOutput(args: GetPersistedOperationsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPersistedOperationsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cosmo:index/getPersistedOperations:getPersistedOperations", {
        "clientName": args.clientName,
        "federatedGraphName": args.federatedGraphName,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getPersistedOperations.
 */
export interface GetPersistedOperationsOutputArgs {
    clientName: pulumi.Input<string>;
    federatedGraphName: pulumi.Input<string>;
    namespace?: pulumi.Input<string | undefined>;
}
