// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSubgraph(args: GetSubgraphArgs, opts?: pulumi.InvokeOptions): Promise<GetSubgraphResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cosmo:index/getSubgraph:getSubgraph", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getSubgraph.
 */
export interface GetSubgraphArgs {
    name: string;
    namespace: string;
}

/**
 * A collection of values returned by getSubgraph.
 */
export interface GetSubgraphResult {
    readonly baseSubgraphName: string;
    readonly headers: string[];
    readonly id: string;
    readonly isEventDrivenGraph: boolean;
    readonly labels: {[key: string]: string};
    readonly name: string;
    readonly namespace: string;
    readonly readme: string;
    readonly routingUrl: string;
    readonly schema: string;
    readonly subscriptionProtocol: string;
    readonly subscriptionUrl: string;
    readonly websocketSubprotocol: string;
}
export function getSubgraphOutput(args: GetSubgraphOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSubgraphResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cosmo:index/getSubgraph:getSubgraph", {
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getSubgraph.
 */
export interface GetSubgraphOutputArgs {
    name: pulumi.Input<string>;
    namespace: pulumi.Input<string>;
}
