// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RouterToken extends pulumi.CustomResource {
    /**
     * Get an existing RouterToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RouterTokenState, opts?: pulumi.CustomResourceOptions): RouterToken {
        return new RouterToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cosmo:index/routerToken:RouterToken';

    /**
     * Returns true if the given object is an instance of RouterToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RouterToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RouterToken.__pulumiType;
    }

    /**
     * The name of the graph to create the token for.
     */
    declare public readonly graphName: pulumi.Output<string>;
    /**
     * The name of the router token.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The namespace to create the token in.
     */
    declare public readonly namespace: pulumi.Output<string>;
    /**
     * The token to be used for the router.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;

    /**
     * Create a RouterToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RouterTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RouterTokenArgs | RouterTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RouterTokenState | undefined;
            resourceInputs["graphName"] = state?.graphName;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["token"] = state?.token;
        } else {
            const args = argsOrState as RouterTokenArgs | undefined;
            if (args?.graphName === undefined && !opts.urn) {
                throw new Error("Missing required property 'graphName'");
            }
            resourceInputs["graphName"] = args?.graphName;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(RouterToken.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RouterToken resources.
 */
export interface RouterTokenState {
    /**
     * The name of the graph to create the token for.
     */
    graphName?: pulumi.Input<string>;
    /**
     * The name of the router token.
     */
    name?: pulumi.Input<string>;
    /**
     * The namespace to create the token in.
     */
    namespace?: pulumi.Input<string>;
    /**
     * The token to be used for the router.
     */
    token?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RouterToken resource.
 */
export interface RouterTokenArgs {
    /**
     * The name of the graph to create the token for.
     */
    graphName: pulumi.Input<string>;
    /**
     * The name of the router token.
     */
    name?: pulumi.Input<string>;
    /**
     * The namespace to create the token in.
     */
    namespace?: pulumi.Input<string>;
}
