// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Subgraph extends pulumi.CustomResource {
    /**
     * Get an existing Subgraph resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SubgraphState, opts?: pulumi.CustomResourceOptions): Subgraph {
        return new Subgraph(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cosmo:index/subgraph:Subgraph';

    /**
     * Returns true if the given object is an instance of Subgraph.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Subgraph {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Subgraph.__pulumiType;
    }

    /**
     * Indicates if the subgraph is event-driven.
     */
    declare public readonly isEventDrivenGraph: pulumi.Output<boolean>;
    /**
     * Labels for the subgraph.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string}>;
    /**
     * The name of the subgraph.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The namespace in which the subgraph is located.
     */
    declare public readonly namespace: pulumi.Output<string>;
    /**
     * The readme for the subgraph.
     */
    declare public readonly readme: pulumi.Output<string | undefined>;
    /**
     * The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
     */
    declare public readonly routingUrl: pulumi.Output<string>;
    /**
     * The schema for the subgraph.
     */
    declare public readonly schema: pulumi.Output<string | undefined>;
    /**
     * The subscription protocol for the subgraph.
     */
    declare public readonly subscriptionProtocol: pulumi.Output<string>;
    /**
     * The subscription URL for the subgraph.
     */
    declare public readonly subscriptionUrl: pulumi.Output<string | undefined>;
    /**
     * Unset labels for the subgraph.
     */
    declare public readonly unsetLabels: pulumi.Output<boolean | undefined>;
    /**
     * The websocket subprotocol for the subgraph.
     */
    declare public readonly websocketSubprotocol: pulumi.Output<string>;

    /**
     * Create a Subgraph resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SubgraphArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SubgraphArgs | SubgraphState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SubgraphState | undefined;
            resourceInputs["isEventDrivenGraph"] = state?.isEventDrivenGraph;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["readme"] = state?.readme;
            resourceInputs["routingUrl"] = state?.routingUrl;
            resourceInputs["schema"] = state?.schema;
            resourceInputs["subscriptionProtocol"] = state?.subscriptionProtocol;
            resourceInputs["subscriptionUrl"] = state?.subscriptionUrl;
            resourceInputs["unsetLabels"] = state?.unsetLabels;
            resourceInputs["websocketSubprotocol"] = state?.websocketSubprotocol;
        } else {
            const args = argsOrState as SubgraphArgs | undefined;
            resourceInputs["isEventDrivenGraph"] = args?.isEventDrivenGraph;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["readme"] = args?.readme;
            resourceInputs["routingUrl"] = args?.routingUrl;
            resourceInputs["schema"] = args?.schema;
            resourceInputs["subscriptionProtocol"] = args?.subscriptionProtocol;
            resourceInputs["subscriptionUrl"] = args?.subscriptionUrl;
            resourceInputs["unsetLabels"] = args?.unsetLabels;
            resourceInputs["websocketSubprotocol"] = args?.websocketSubprotocol;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Subgraph.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Subgraph resources.
 */
export interface SubgraphState {
    /**
     * Indicates if the subgraph is event-driven.
     */
    isEventDrivenGraph?: pulumi.Input<boolean>;
    /**
     * Labels for the subgraph.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the subgraph.
     */
    name?: pulumi.Input<string>;
    /**
     * The namespace in which the subgraph is located.
     */
    namespace?: pulumi.Input<string>;
    /**
     * The readme for the subgraph.
     */
    readme?: pulumi.Input<string>;
    /**
     * The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
     */
    routingUrl?: pulumi.Input<string>;
    /**
     * The schema for the subgraph.
     */
    schema?: pulumi.Input<string>;
    /**
     * The subscription protocol for the subgraph.
     */
    subscriptionProtocol?: pulumi.Input<string>;
    /**
     * The subscription URL for the subgraph.
     */
    subscriptionUrl?: pulumi.Input<string>;
    /**
     * Unset labels for the subgraph.
     */
    unsetLabels?: pulumi.Input<boolean>;
    /**
     * The websocket subprotocol for the subgraph.
     */
    websocketSubprotocol?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Subgraph resource.
 */
export interface SubgraphArgs {
    /**
     * Indicates if the subgraph is event-driven.
     */
    isEventDrivenGraph?: pulumi.Input<boolean>;
    /**
     * Labels for the subgraph.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the subgraph.
     */
    name?: pulumi.Input<string>;
    /**
     * The namespace in which the subgraph is located.
     */
    namespace?: pulumi.Input<string>;
    /**
     * The readme for the subgraph.
     */
    readme?: pulumi.Input<string>;
    /**
     * The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
     */
    routingUrl?: pulumi.Input<string>;
    /**
     * The schema for the subgraph.
     */
    schema?: pulumi.Input<string>;
    /**
     * The subscription protocol for the subgraph.
     */
    subscriptionProtocol?: pulumi.Input<string>;
    /**
     * The subscription URL for the subgraph.
     */
    subscriptionUrl?: pulumi.Input<string>;
    /**
     * Unset labels for the subgraph.
     */
    unsetLabels?: pulumi.Input<boolean>;
    /**
     * The websocket subprotocol for the subgraph.
     */
    websocketSubprotocol?: pulumi.Input<string>;
}
