# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ContractArgs', 'Contract']

@pulumi.input_type
class ContractArgs:
    def __init__(__self__, *,
                 namespace: pulumi.Input[_builtins.str],
                 routing_url: pulumi.Input[_builtins.str],
                 source: pulumi.Input[_builtins.str],
                 admission_webhook_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 admission_webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 exclude_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 include_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 readme: Optional[pulumi.Input[_builtins.str]] = None,
                 supports_federation: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Contract resource.
        """
        pulumi.set(__self__, "namespace", namespace)
        pulumi.set(__self__, "routing_url", routing_url)
        pulumi.set(__self__, "source", source)
        if admission_webhook_secret is not None:
            pulumi.set(__self__, "admission_webhook_secret", admission_webhook_secret)
        if admission_webhook_url is not None:
            pulumi.set(__self__, "admission_webhook_url", admission_webhook_url)
        if exclude_tags is not None:
            pulumi.set(__self__, "exclude_tags", exclude_tags)
        if include_tags is not None:
            pulumi.set(__self__, "include_tags", include_tags)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if readme is not None:
            pulumi.set(__self__, "readme", readme)
        if supports_federation is not None:
            pulumi.set(__self__, "supports_federation", supports_federation)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter(name="routingUrl")
    def routing_url(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "routing_url")

    @routing_url.setter
    def routing_url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "routing_url", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter(name="admissionWebhookSecret")
    def admission_webhook_secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "admission_webhook_secret")

    @admission_webhook_secret.setter
    def admission_webhook_secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "admission_webhook_secret", value)

    @_builtins.property
    @pulumi.getter(name="admissionWebhookUrl")
    def admission_webhook_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "admission_webhook_url")

    @admission_webhook_url.setter
    def admission_webhook_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "admission_webhook_url", value)

    @_builtins.property
    @pulumi.getter(name="excludeTags")
    def exclude_tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "exclude_tags")

    @exclude_tags.setter
    def exclude_tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "exclude_tags", value)

    @_builtins.property
    @pulumi.getter(name="includeTags")
    def include_tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "include_tags")

    @include_tags.setter
    def include_tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "include_tags", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def readme(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "readme")

    @readme.setter
    def readme(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "readme", value)

    @_builtins.property
    @pulumi.getter(name="supportsFederation")
    def supports_federation(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "supports_federation")

    @supports_federation.setter
    def supports_federation(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "supports_federation", value)


@pulumi.input_type
class _ContractState:
    def __init__(__self__, *,
                 admission_webhook_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 admission_webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 exclude_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 include_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 readme: Optional[pulumi.Input[_builtins.str]] = None,
                 routing_url: Optional[pulumi.Input[_builtins.str]] = None,
                 source: Optional[pulumi.Input[_builtins.str]] = None,
                 supports_federation: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering Contract resources.
        """
        if admission_webhook_secret is not None:
            pulumi.set(__self__, "admission_webhook_secret", admission_webhook_secret)
        if admission_webhook_url is not None:
            pulumi.set(__self__, "admission_webhook_url", admission_webhook_url)
        if exclude_tags is not None:
            pulumi.set(__self__, "exclude_tags", exclude_tags)
        if include_tags is not None:
            pulumi.set(__self__, "include_tags", include_tags)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if readme is not None:
            pulumi.set(__self__, "readme", readme)
        if routing_url is not None:
            pulumi.set(__self__, "routing_url", routing_url)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if supports_federation is not None:
            pulumi.set(__self__, "supports_federation", supports_federation)

    @_builtins.property
    @pulumi.getter(name="admissionWebhookSecret")
    def admission_webhook_secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "admission_webhook_secret")

    @admission_webhook_secret.setter
    def admission_webhook_secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "admission_webhook_secret", value)

    @_builtins.property
    @pulumi.getter(name="admissionWebhookUrl")
    def admission_webhook_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "admission_webhook_url")

    @admission_webhook_url.setter
    def admission_webhook_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "admission_webhook_url", value)

    @_builtins.property
    @pulumi.getter(name="excludeTags")
    def exclude_tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "exclude_tags")

    @exclude_tags.setter
    def exclude_tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "exclude_tags", value)

    @_builtins.property
    @pulumi.getter(name="includeTags")
    def include_tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "include_tags")

    @include_tags.setter
    def include_tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "include_tags", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter
    def readme(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "readme")

    @readme.setter
    def readme(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "readme", value)

    @_builtins.property
    @pulumi.getter(name="routingUrl")
    def routing_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "routing_url")

    @routing_url.setter
    def routing_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "routing_url", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter(name="supportsFederation")
    def supports_federation(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "supports_federation")

    @supports_federation.setter
    def supports_federation(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "supports_federation", value)


@pulumi.type_token("cosmo:index/contract:Contract")
class Contract(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 admission_webhook_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 admission_webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 exclude_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 include_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 readme: Optional[pulumi.Input[_builtins.str]] = None,
                 routing_url: Optional[pulumi.Input[_builtins.str]] = None,
                 source: Optional[pulumi.Input[_builtins.str]] = None,
                 supports_federation: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a Contract resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ContractArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Contract resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ContractArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ContractArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 admission_webhook_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 admission_webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 exclude_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 include_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 readme: Optional[pulumi.Input[_builtins.str]] = None,
                 routing_url: Optional[pulumi.Input[_builtins.str]] = None,
                 source: Optional[pulumi.Input[_builtins.str]] = None,
                 supports_federation: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ContractArgs.__new__(ContractArgs)

            __props__.__dict__["admission_webhook_secret"] = admission_webhook_secret
            __props__.__dict__["admission_webhook_url"] = admission_webhook_url
            __props__.__dict__["exclude_tags"] = exclude_tags
            __props__.__dict__["include_tags"] = include_tags
            __props__.__dict__["name"] = name
            if namespace is None and not opts.urn:
                raise TypeError("Missing required property 'namespace'")
            __props__.__dict__["namespace"] = namespace
            __props__.__dict__["readme"] = readme
            if routing_url is None and not opts.urn:
                raise TypeError("Missing required property 'routing_url'")
            __props__.__dict__["routing_url"] = routing_url
            if source is None and not opts.urn:
                raise TypeError("Missing required property 'source'")
            __props__.__dict__["source"] = source
            __props__.__dict__["supports_federation"] = supports_federation
        super(Contract, __self__).__init__(
            'cosmo:index/contract:Contract',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            admission_webhook_secret: Optional[pulumi.Input[_builtins.str]] = None,
            admission_webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
            exclude_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            include_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            namespace: Optional[pulumi.Input[_builtins.str]] = None,
            readme: Optional[pulumi.Input[_builtins.str]] = None,
            routing_url: Optional[pulumi.Input[_builtins.str]] = None,
            source: Optional[pulumi.Input[_builtins.str]] = None,
            supports_federation: Optional[pulumi.Input[_builtins.bool]] = None) -> 'Contract':
        """
        Get an existing Contract resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ContractState.__new__(_ContractState)

        __props__.__dict__["admission_webhook_secret"] = admission_webhook_secret
        __props__.__dict__["admission_webhook_url"] = admission_webhook_url
        __props__.__dict__["exclude_tags"] = exclude_tags
        __props__.__dict__["include_tags"] = include_tags
        __props__.__dict__["name"] = name
        __props__.__dict__["namespace"] = namespace
        __props__.__dict__["readme"] = readme
        __props__.__dict__["routing_url"] = routing_url
        __props__.__dict__["source"] = source
        __props__.__dict__["supports_federation"] = supports_federation
        return Contract(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="admissionWebhookSecret")
    def admission_webhook_secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "admission_webhook_secret")

    @_builtins.property
    @pulumi.getter(name="admissionWebhookUrl")
    def admission_webhook_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "admission_webhook_url")

    @_builtins.property
    @pulumi.getter(name="excludeTags")
    def exclude_tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "exclude_tags")

    @_builtins.property
    @pulumi.getter(name="includeTags")
    def include_tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "include_tags")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "namespace")

    @_builtins.property
    @pulumi.getter
    def readme(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "readme")

    @_builtins.property
    @pulumi.getter(name="routingUrl")
    def routing_url(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "routing_url")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter(name="supportsFederation")
    def supports_federation(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "supports_federation")

