# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['FeatureSubgraphArgs', 'FeatureSubgraph']

@pulumi.input_type
class FeatureSubgraphArgs:
    def __init__(__self__, *,
                 base_subgraph_name: pulumi.Input[_builtins.str],
                 routing_url: pulumi.Input[_builtins.str],
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 readme: Optional[pulumi.Input[_builtins.str]] = None,
                 schema: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_url: Optional[pulumi.Input[_builtins.str]] = None,
                 websocket_subprotocol: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a FeatureSubgraph resource.

        :param pulumi.Input[_builtins.str] base_subgraph_name: The name of the base subgraph that this feature subgraph extends.
        :param pulumi.Input[_builtins.str] routing_url: The routing URL of the feature subgraph.
        :param pulumi.Input[_builtins.str] name: The name of the feature subgraph.
        :param pulumi.Input[_builtins.str] namespace: The namespace to create the feature subgraph in.
        :param pulumi.Input[_builtins.str] readme: The readme for the subgraph.
        :param pulumi.Input[_builtins.str] schema: The schema for the subgraph.
        :param pulumi.Input[_builtins.str] subscription_protocol: The subscription protocol for the subgraph.
        :param pulumi.Input[_builtins.str] subscription_url: The subscription URL for the subgraph.
        :param pulumi.Input[_builtins.str] websocket_subprotocol: The websocket subprotocol for the subgraph.
        """
        pulumi.set(__self__, "base_subgraph_name", base_subgraph_name)
        pulumi.set(__self__, "routing_url", routing_url)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if readme is not None:
            pulumi.set(__self__, "readme", readme)
        if schema is not None:
            pulumi.set(__self__, "schema", schema)
        if subscription_protocol is not None:
            pulumi.set(__self__, "subscription_protocol", subscription_protocol)
        if subscription_url is not None:
            pulumi.set(__self__, "subscription_url", subscription_url)
        if websocket_subprotocol is not None:
            pulumi.set(__self__, "websocket_subprotocol", websocket_subprotocol)

    @_builtins.property
    @pulumi.getter(name="baseSubgraphName")
    def base_subgraph_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the base subgraph that this feature subgraph extends.
        """
        return pulumi.get(self, "base_subgraph_name")

    @base_subgraph_name.setter
    def base_subgraph_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "base_subgraph_name", value)

    @_builtins.property
    @pulumi.getter(name="routingUrl")
    def routing_url(self) -> pulumi.Input[_builtins.str]:
        """
        The routing URL of the feature subgraph.
        """
        return pulumi.get(self, "routing_url")

    @routing_url.setter
    def routing_url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "routing_url", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the feature subgraph.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The namespace to create the feature subgraph in.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter
    def readme(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The readme for the subgraph.
        """
        return pulumi.get(self, "readme")

    @readme.setter
    def readme(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "readme", value)

    @_builtins.property
    @pulumi.getter
    def schema(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The schema for the subgraph.
        """
        return pulumi.get(self, "schema")

    @schema.setter
    def schema(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schema", value)

    @_builtins.property
    @pulumi.getter(name="subscriptionProtocol")
    def subscription_protocol(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The subscription protocol for the subgraph.
        """
        return pulumi.get(self, "subscription_protocol")

    @subscription_protocol.setter
    def subscription_protocol(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "subscription_protocol", value)

    @_builtins.property
    @pulumi.getter(name="subscriptionUrl")
    def subscription_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The subscription URL for the subgraph.
        """
        return pulumi.get(self, "subscription_url")

    @subscription_url.setter
    def subscription_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "subscription_url", value)

    @_builtins.property
    @pulumi.getter(name="websocketSubprotocol")
    def websocket_subprotocol(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The websocket subprotocol for the subgraph.
        """
        return pulumi.get(self, "websocket_subprotocol")

    @websocket_subprotocol.setter
    def websocket_subprotocol(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "websocket_subprotocol", value)


@pulumi.input_type
class _FeatureSubgraphState:
    def __init__(__self__, *,
                 base_subgraph_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 readme: Optional[pulumi.Input[_builtins.str]] = None,
                 routing_url: Optional[pulumi.Input[_builtins.str]] = None,
                 schema: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_url: Optional[pulumi.Input[_builtins.str]] = None,
                 websocket_subprotocol: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering FeatureSubgraph resources.

        :param pulumi.Input[_builtins.str] base_subgraph_name: The name of the base subgraph that this feature subgraph extends.
        :param pulumi.Input[_builtins.str] name: The name of the feature subgraph.
        :param pulumi.Input[_builtins.str] namespace: The namespace to create the feature subgraph in.
        :param pulumi.Input[_builtins.str] readme: The readme for the subgraph.
        :param pulumi.Input[_builtins.str] routing_url: The routing URL of the feature subgraph.
        :param pulumi.Input[_builtins.str] schema: The schema for the subgraph.
        :param pulumi.Input[_builtins.str] subscription_protocol: The subscription protocol for the subgraph.
        :param pulumi.Input[_builtins.str] subscription_url: The subscription URL for the subgraph.
        :param pulumi.Input[_builtins.str] websocket_subprotocol: The websocket subprotocol for the subgraph.
        """
        if base_subgraph_name is not None:
            pulumi.set(__self__, "base_subgraph_name", base_subgraph_name)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if readme is not None:
            pulumi.set(__self__, "readme", readme)
        if routing_url is not None:
            pulumi.set(__self__, "routing_url", routing_url)
        if schema is not None:
            pulumi.set(__self__, "schema", schema)
        if subscription_protocol is not None:
            pulumi.set(__self__, "subscription_protocol", subscription_protocol)
        if subscription_url is not None:
            pulumi.set(__self__, "subscription_url", subscription_url)
        if websocket_subprotocol is not None:
            pulumi.set(__self__, "websocket_subprotocol", websocket_subprotocol)

    @_builtins.property
    @pulumi.getter(name="baseSubgraphName")
    def base_subgraph_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the base subgraph that this feature subgraph extends.
        """
        return pulumi.get(self, "base_subgraph_name")

    @base_subgraph_name.setter
    def base_subgraph_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "base_subgraph_name", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the feature subgraph.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The namespace to create the feature subgraph in.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter
    def readme(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The readme for the subgraph.
        """
        return pulumi.get(self, "readme")

    @readme.setter
    def readme(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "readme", value)

    @_builtins.property
    @pulumi.getter(name="routingUrl")
    def routing_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The routing URL of the feature subgraph.
        """
        return pulumi.get(self, "routing_url")

    @routing_url.setter
    def routing_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "routing_url", value)

    @_builtins.property
    @pulumi.getter
    def schema(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The schema for the subgraph.
        """
        return pulumi.get(self, "schema")

    @schema.setter
    def schema(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schema", value)

    @_builtins.property
    @pulumi.getter(name="subscriptionProtocol")
    def subscription_protocol(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The subscription protocol for the subgraph.
        """
        return pulumi.get(self, "subscription_protocol")

    @subscription_protocol.setter
    def subscription_protocol(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "subscription_protocol", value)

    @_builtins.property
    @pulumi.getter(name="subscriptionUrl")
    def subscription_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The subscription URL for the subgraph.
        """
        return pulumi.get(self, "subscription_url")

    @subscription_url.setter
    def subscription_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "subscription_url", value)

    @_builtins.property
    @pulumi.getter(name="websocketSubprotocol")
    def websocket_subprotocol(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The websocket subprotocol for the subgraph.
        """
        return pulumi.get(self, "websocket_subprotocol")

    @websocket_subprotocol.setter
    def websocket_subprotocol(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "websocket_subprotocol", value)


@pulumi.type_token("cosmo:index/featureSubgraph:FeatureSubgraph")
class FeatureSubgraph(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 base_subgraph_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 readme: Optional[pulumi.Input[_builtins.str]] = None,
                 routing_url: Optional[pulumi.Input[_builtins.str]] = None,
                 schema: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_url: Optional[pulumi.Input[_builtins.str]] = None,
                 websocket_subprotocol: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a FeatureSubgraph resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] base_subgraph_name: The name of the base subgraph that this feature subgraph extends.
        :param pulumi.Input[_builtins.str] name: The name of the feature subgraph.
        :param pulumi.Input[_builtins.str] namespace: The namespace to create the feature subgraph in.
        :param pulumi.Input[_builtins.str] readme: The readme for the subgraph.
        :param pulumi.Input[_builtins.str] routing_url: The routing URL of the feature subgraph.
        :param pulumi.Input[_builtins.str] schema: The schema for the subgraph.
        :param pulumi.Input[_builtins.str] subscription_protocol: The subscription protocol for the subgraph.
        :param pulumi.Input[_builtins.str] subscription_url: The subscription URL for the subgraph.
        :param pulumi.Input[_builtins.str] websocket_subprotocol: The websocket subprotocol for the subgraph.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FeatureSubgraphArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a FeatureSubgraph resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param FeatureSubgraphArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FeatureSubgraphArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 base_subgraph_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 readme: Optional[pulumi.Input[_builtins.str]] = None,
                 routing_url: Optional[pulumi.Input[_builtins.str]] = None,
                 schema: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_url: Optional[pulumi.Input[_builtins.str]] = None,
                 websocket_subprotocol: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FeatureSubgraphArgs.__new__(FeatureSubgraphArgs)

            if base_subgraph_name is None and not opts.urn:
                raise TypeError("Missing required property 'base_subgraph_name'")
            __props__.__dict__["base_subgraph_name"] = base_subgraph_name
            __props__.__dict__["name"] = name
            __props__.__dict__["namespace"] = namespace
            __props__.__dict__["readme"] = readme
            if routing_url is None and not opts.urn:
                raise TypeError("Missing required property 'routing_url'")
            __props__.__dict__["routing_url"] = routing_url
            __props__.__dict__["schema"] = schema
            __props__.__dict__["subscription_protocol"] = subscription_protocol
            __props__.__dict__["subscription_url"] = subscription_url
            __props__.__dict__["websocket_subprotocol"] = websocket_subprotocol
        super(FeatureSubgraph, __self__).__init__(
            'cosmo:index/featureSubgraph:FeatureSubgraph',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            base_subgraph_name: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            namespace: Optional[pulumi.Input[_builtins.str]] = None,
            readme: Optional[pulumi.Input[_builtins.str]] = None,
            routing_url: Optional[pulumi.Input[_builtins.str]] = None,
            schema: Optional[pulumi.Input[_builtins.str]] = None,
            subscription_protocol: Optional[pulumi.Input[_builtins.str]] = None,
            subscription_url: Optional[pulumi.Input[_builtins.str]] = None,
            websocket_subprotocol: Optional[pulumi.Input[_builtins.str]] = None) -> 'FeatureSubgraph':
        """
        Get an existing FeatureSubgraph resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] base_subgraph_name: The name of the base subgraph that this feature subgraph extends.
        :param pulumi.Input[_builtins.str] name: The name of the feature subgraph.
        :param pulumi.Input[_builtins.str] namespace: The namespace to create the feature subgraph in.
        :param pulumi.Input[_builtins.str] readme: The readme for the subgraph.
        :param pulumi.Input[_builtins.str] routing_url: The routing URL of the feature subgraph.
        :param pulumi.Input[_builtins.str] schema: The schema for the subgraph.
        :param pulumi.Input[_builtins.str] subscription_protocol: The subscription protocol for the subgraph.
        :param pulumi.Input[_builtins.str] subscription_url: The subscription URL for the subgraph.
        :param pulumi.Input[_builtins.str] websocket_subprotocol: The websocket subprotocol for the subgraph.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _FeatureSubgraphState.__new__(_FeatureSubgraphState)

        __props__.__dict__["base_subgraph_name"] = base_subgraph_name
        __props__.__dict__["name"] = name
        __props__.__dict__["namespace"] = namespace
        __props__.__dict__["readme"] = readme
        __props__.__dict__["routing_url"] = routing_url
        __props__.__dict__["schema"] = schema
        __props__.__dict__["subscription_protocol"] = subscription_protocol
        __props__.__dict__["subscription_url"] = subscription_url
        __props__.__dict__["websocket_subprotocol"] = websocket_subprotocol
        return FeatureSubgraph(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="baseSubgraphName")
    def base_subgraph_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the base subgraph that this feature subgraph extends.
        """
        return pulumi.get(self, "base_subgraph_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the feature subgraph.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Output[_builtins.str]:
        """
        The namespace to create the feature subgraph in.
        """
        return pulumi.get(self, "namespace")

    @_builtins.property
    @pulumi.getter
    def readme(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The readme for the subgraph.
        """
        return pulumi.get(self, "readme")

    @_builtins.property
    @pulumi.getter(name="routingUrl")
    def routing_url(self) -> pulumi.Output[_builtins.str]:
        """
        The routing URL of the feature subgraph.
        """
        return pulumi.get(self, "routing_url")

    @_builtins.property
    @pulumi.getter
    def schema(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The schema for the subgraph.
        """
        return pulumi.get(self, "schema")

    @_builtins.property
    @pulumi.getter(name="subscriptionProtocol")
    def subscription_protocol(self) -> pulumi.Output[_builtins.str]:
        """
        The subscription protocol for the subgraph.
        """
        return pulumi.get(self, "subscription_protocol")

    @_builtins.property
    @pulumi.getter(name="subscriptionUrl")
    def subscription_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The subscription URL for the subgraph.
        """
        return pulumi.get(self, "subscription_url")

    @_builtins.property
    @pulumi.getter(name="websocketSubprotocol")
    def websocket_subprotocol(self) -> pulumi.Output[_builtins.str]:
        """
        The websocket subprotocol for the subgraph.
        """
        return pulumi.get(self, "websocket_subprotocol")

