# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetClientsResult',
    'AwaitableGetClientsResult',
    'get_clients',
    'get_clients_output',
]

@pulumi.output_type
class GetClientsResult:
    """
    A collection of values returned by getClients.
    """
    def __init__(__self__, clients=None, federated_graph_name=None, id=None, namespace=None):
        if clients and not isinstance(clients, list):
            raise TypeError("Expected argument 'clients' to be a list")
        pulumi.set(__self__, "clients", clients)
        if federated_graph_name and not isinstance(federated_graph_name, str):
            raise TypeError("Expected argument 'federated_graph_name' to be a str")
        pulumi.set(__self__, "federated_graph_name", federated_graph_name)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if namespace and not isinstance(namespace, str):
            raise TypeError("Expected argument 'namespace' to be a str")
        pulumi.set(__self__, "namespace", namespace)

    @_builtins.property
    @pulumi.getter
    def clients(self) -> Sequence['outputs.GetClientsClientResult']:
        return pulumi.get(self, "clients")

    @_builtins.property
    @pulumi.getter(name="federatedGraphName")
    def federated_graph_name(self) -> _builtins.str:
        return pulumi.get(self, "federated_graph_name")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> _builtins.str:
        return pulumi.get(self, "namespace")


class AwaitableGetClientsResult(GetClientsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetClientsResult(
            clients=self.clients,
            federated_graph_name=self.federated_graph_name,
            id=self.id,
            namespace=self.namespace)


def get_clients(federated_graph_name: Optional[_builtins.str] = None,
                namespace: Optional[_builtins.str] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetClientsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['federatedGraphName'] = federated_graph_name
    __args__['namespace'] = namespace
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('cosmo:index/getClients:getClients', __args__, opts=opts, typ=GetClientsResult).value

    return AwaitableGetClientsResult(
        clients=pulumi.get(__ret__, 'clients'),
        federated_graph_name=pulumi.get(__ret__, 'federated_graph_name'),
        id=pulumi.get(__ret__, 'id'),
        namespace=pulumi.get(__ret__, 'namespace'))
def get_clients_output(federated_graph_name: pulumi.Input[Optional[_builtins.str]] = None,
                       namespace: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetClientsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['federatedGraphName'] = federated_graph_name
    __args__['namespace'] = namespace
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('cosmo:index/getClients:getClients', __args__, opts=opts, typ=GetClientsResult)
    return __ret__.apply(lambda __response__: GetClientsResult(
        clients=pulumi.get(__response__, 'clients'),
        federated_graph_name=pulumi.get(__response__, 'federated_graph_name'),
        id=pulumi.get(__response__, 'id'),
        namespace=pulumi.get(__response__, 'namespace')))
