# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetClientsClientResult',
    'GetPersistedOperationsOperationResult',
]

@pulumi.output_type
class GetClientsClientResult(dict):
    def __init__(__self__, *,
                 created_at: _builtins.str,
                 created_by: _builtins.str,
                 id: _builtins.str,
                 last_updated_at: _builtins.str,
                 last_updated_by: _builtins.str,
                 name: _builtins.str,
                 persisted_operations_count: _builtins.int):
        """
        :param _builtins.str created_at: The time the client was created.
        :param _builtins.str created_by: The user that created the client.
        :param _builtins.str id: The unique identifier of the client.
        :param _builtins.str last_updated_at: The time the client was last updated.
        :param _builtins.str last_updated_by: The user that last updated the client.
        :param _builtins.str name: The name of the client.
        :param _builtins.int persisted_operations_count: The number of persisted operations registered for the client.
        """
        pulumi.set(__self__, "created_at", created_at)
        pulumi.set(__self__, "created_by", created_by)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "last_updated_at", last_updated_at)
        pulumi.set(__self__, "last_updated_by", last_updated_by)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "persisted_operations_count", persisted_operations_count)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        The time the client was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="createdBy")
    def created_by(self) -> _builtins.str:
        """
        The user that created the client.
        """
        return pulumi.get(self, "created_by")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the client.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="lastUpdatedAt")
    def last_updated_at(self) -> _builtins.str:
        """
        The time the client was last updated.
        """
        return pulumi.get(self, "last_updated_at")

    @_builtins.property
    @pulumi.getter(name="lastUpdatedBy")
    def last_updated_by(self) -> _builtins.str:
        """
        The user that last updated the client.
        """
        return pulumi.get(self, "last_updated_by")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the client.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="persistedOperationsCount")
    def persisted_operations_count(self) -> _builtins.int:
        """
        The number of persisted operations registered for the client.
        """
        return pulumi.get(self, "persisted_operations_count")


@pulumi.output_type
class GetPersistedOperationsOperationResult(dict):
    def __init__(__self__, *,
                 contents: _builtins.str,
                 created_at: _builtins.str,
                 id: _builtins.str,
                 last_updated_at: _builtins.str,
                 operation_names: Sequence[_builtins.str]):
        """
        :param _builtins.str contents: The GraphQL operation contents.
        :param _builtins.str created_at: The time the operation was created.
        :param _builtins.str id: The unique identifier of the operation (the SHA-256 hash of its contents).
        :param _builtins.str last_updated_at: The time the operation was last updated.
        :param Sequence[_builtins.str] operation_names: The names of the operations contained in the document.
        """
        pulumi.set(__self__, "contents", contents)
        pulumi.set(__self__, "created_at", created_at)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "last_updated_at", last_updated_at)
        pulumi.set(__self__, "operation_names", operation_names)

    @_builtins.property
    @pulumi.getter
    def contents(self) -> _builtins.str:
        """
        The GraphQL operation contents.
        """
        return pulumi.get(self, "contents")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        The time the operation was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the operation (the SHA-256 hash of its contents).
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="lastUpdatedAt")
    def last_updated_at(self) -> _builtins.str:
        """
        The time the operation was last updated.
        """
        return pulumi.get(self, "last_updated_at")

    @_builtins.property
    @pulumi.getter(name="operationNames")
    def operation_names(self) -> Sequence[_builtins.str]:
        """
        The names of the operations contained in the document.
        """
        return pulumi.get(self, "operation_names")


