# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PersistedOperationsArgs', 'PersistedOperations']

@pulumi.input_type
class PersistedOperationsArgs:
    def __init__(__self__, *,
                 client_name: pulumi.Input[_builtins.str],
                 federated_graph_name: pulumi.Input[_builtins.str],
                 operations: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]],
                 namespace: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a PersistedOperations resource.

        :param pulumi.Input[_builtins.str] client_name: The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
        :param pulumi.Input[_builtins.str] federated_graph_name: The name of the federated graph to register the operations on.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] operations: The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        :param pulumi.Input[_builtins.str] namespace: The namespace of the federated graph.
        """
        pulumi.set(__self__, "client_name", client_name)
        pulumi.set(__self__, "federated_graph_name", federated_graph_name)
        pulumi.set(__self__, "operations", operations)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)

    @_builtins.property
    @pulumi.getter(name="clientName")
    def client_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
        """
        return pulumi.get(self, "client_name")

    @client_name.setter
    def client_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "client_name", value)

    @_builtins.property
    @pulumi.getter(name="federatedGraphName")
    def federated_graph_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the federated graph to register the operations on.
        """
        return pulumi.get(self, "federated_graph_name")

    @federated_graph_name.setter
    def federated_graph_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "federated_graph_name", value)

    @_builtins.property
    @pulumi.getter
    def operations(self) -> pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]:
        """
        The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        """
        return pulumi.get(self, "operations")

    @operations.setter
    def operations(self, value: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "operations", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The namespace of the federated graph.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "namespace", value)


@pulumi.input_type
class _PersistedOperationsState:
    def __init__(__self__, *,
                 client_name: pulumi.Input[Optional[_builtins.str]] = None,
                 federated_graph_name: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 operations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering PersistedOperations resources.

        :param pulumi.Input[_builtins.str] client_name: The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
        :param pulumi.Input[_builtins.str] federated_graph_name: The name of the federated graph to register the operations on.
        :param pulumi.Input[_builtins.str] namespace: The namespace of the federated graph.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] operations: The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        """
        if client_name is not None:
            pulumi.set(__self__, "client_name", client_name)
        if federated_graph_name is not None:
            pulumi.set(__self__, "federated_graph_name", federated_graph_name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if operations is not None:
            pulumi.set(__self__, "operations", operations)

    @_builtins.property
    @pulumi.getter(name="clientName")
    def client_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
        """
        return pulumi.get(self, "client_name")

    @client_name.setter
    def client_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "client_name", value)

    @_builtins.property
    @pulumi.getter(name="federatedGraphName")
    def federated_graph_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the federated graph to register the operations on.
        """
        return pulumi.get(self, "federated_graph_name")

    @federated_graph_name.setter
    def federated_graph_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "federated_graph_name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The namespace of the federated graph.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter
    def operations(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        """
        return pulumi.get(self, "operations")

    @operations.setter
    def operations(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "operations", value)


@pulumi.type_token("cosmo:index/persistedOperations:PersistedOperations")
class PersistedOperations(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_name: pulumi.Input[Optional[_builtins.str]] = None,
                 federated_graph_name: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 operations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a PersistedOperations resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] client_name: The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
        :param pulumi.Input[_builtins.str] federated_graph_name: The name of the federated graph to register the operations on.
        :param pulumi.Input[_builtins.str] namespace: The namespace of the federated graph.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] operations: The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PersistedOperationsArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a PersistedOperations resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param PersistedOperationsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PersistedOperationsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 client_name: pulumi.Input[Optional[_builtins.str]] = None,
                 federated_graph_name: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 operations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PersistedOperationsArgs.__new__(PersistedOperationsArgs)

            if client_name is None and not opts.urn:
                raise TypeError("Missing required property 'client_name'")
            __props__.__dict__["client_name"] = client_name
            if federated_graph_name is None and not opts.urn:
                raise TypeError("Missing required property 'federated_graph_name'")
            __props__.__dict__["federated_graph_name"] = federated_graph_name
            __props__.__dict__["namespace"] = namespace
            if operations is None and not opts.urn:
                raise TypeError("Missing required property 'operations'")
            __props__.__dict__["operations"] = operations
        super(PersistedOperations, __self__).__init__(
            'cosmo:index/persistedOperations:PersistedOperations',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            client_name: pulumi.Input[Optional[_builtins.str]] = None,
            federated_graph_name: pulumi.Input[Optional[_builtins.str]] = None,
            namespace: pulumi.Input[Optional[_builtins.str]] = None,
            operations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None) -> 'PersistedOperations':
        """
        Get an existing PersistedOperations resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] client_name: The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
        :param pulumi.Input[_builtins.str] federated_graph_name: The name of the federated graph to register the operations on.
        :param pulumi.Input[_builtins.str] namespace: The namespace of the federated graph.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] operations: The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PersistedOperationsState.__new__(_PersistedOperationsState)

        __props__.__dict__["client_name"] = client_name
        __props__.__dict__["federated_graph_name"] = federated_graph_name
        __props__.__dict__["namespace"] = namespace
        __props__.__dict__["operations"] = operations
        return PersistedOperations(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clientName")
    def client_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
        """
        return pulumi.get(self, "client_name")

    @_builtins.property
    @pulumi.getter(name="federatedGraphName")
    def federated_graph_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the federated graph to register the operations on.
        """
        return pulumi.get(self, "federated_graph_name")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Output[_builtins.str]:
        """
        The namespace of the federated graph.
        """
        return pulumi.get(self, "namespace")

    @_builtins.property
    @pulumi.getter
    def operations(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
        """
        return pulumi.get(self, "operations")

