# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['RouterTokenArgs', 'RouterToken']

@pulumi.input_type
class RouterTokenArgs:
    def __init__(__self__, *,
                 graph_name: pulumi.Input[_builtins.str],
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a RouterToken resource.

        :param pulumi.Input[_builtins.str] graph_name: The name of the graph to create the token for.
        :param pulumi.Input[_builtins.str] name: The name of the router token.
        :param pulumi.Input[_builtins.str] namespace: The namespace to create the token in.
        """
        pulumi.set(__self__, "graph_name", graph_name)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)

    @_builtins.property
    @pulumi.getter(name="graphName")
    def graph_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the graph to create the token for.
        """
        return pulumi.get(self, "graph_name")

    @graph_name.setter
    def graph_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "graph_name", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the router token.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The namespace to create the token in.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "namespace", value)


@pulumi.input_type
class _RouterTokenState:
    def __init__(__self__, *,
                 graph_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering RouterToken resources.

        :param pulumi.Input[_builtins.str] graph_name: The name of the graph to create the token for.
        :param pulumi.Input[_builtins.str] name: The name of the router token.
        :param pulumi.Input[_builtins.str] namespace: The namespace to create the token in.
        :param pulumi.Input[_builtins.str] token: The token to be used for the router.
        """
        if graph_name is not None:
            pulumi.set(__self__, "graph_name", graph_name)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="graphName")
    def graph_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the graph to create the token for.
        """
        return pulumi.get(self, "graph_name")

    @graph_name.setter
    def graph_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "graph_name", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the router token.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The namespace to create the token in.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The token to be used for the router.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("cosmo:index/routerToken:RouterToken")
class RouterToken(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 graph_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a RouterToken resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] graph_name: The name of the graph to create the token for.
        :param pulumi.Input[_builtins.str] name: The name of the router token.
        :param pulumi.Input[_builtins.str] namespace: The namespace to create the token in.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RouterTokenArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a RouterToken resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param RouterTokenArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RouterTokenArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 graph_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RouterTokenArgs.__new__(RouterTokenArgs)

            if graph_name is None and not opts.urn:
                raise TypeError("Missing required property 'graph_name'")
            __props__.__dict__["graph_name"] = graph_name
            __props__.__dict__["name"] = name
            __props__.__dict__["namespace"] = namespace
            __props__.__dict__["token"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(RouterToken, __self__).__init__(
            'cosmo:index/routerToken:RouterToken',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            graph_name: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            namespace: Optional[pulumi.Input[_builtins.str]] = None,
            token: Optional[pulumi.Input[_builtins.str]] = None) -> 'RouterToken':
        """
        Get an existing RouterToken resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] graph_name: The name of the graph to create the token for.
        :param pulumi.Input[_builtins.str] name: The name of the router token.
        :param pulumi.Input[_builtins.str] namespace: The namespace to create the token in.
        :param pulumi.Input[_builtins.str] token: The token to be used for the router.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RouterTokenState.__new__(_RouterTokenState)

        __props__.__dict__["graph_name"] = graph_name
        __props__.__dict__["name"] = name
        __props__.__dict__["namespace"] = namespace
        __props__.__dict__["token"] = token
        return RouterToken(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="graphName")
    def graph_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the graph to create the token for.
        """
        return pulumi.get(self, "graph_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the router token.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Output[_builtins.str]:
        """
        The namespace to create the token in.
        """
        return pulumi.get(self, "namespace")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[_builtins.str]:
        """
        The token to be used for the router.
        """
        return pulumi.get(self, "token")

